### ISSUE TITLE
ConcurrentModificationException when loading MavenProjects with multiple threads

### ISSUE THREAD

**Issue by timothyjward** [eclipse-m2e/m2e-core#1066]
Seen with:

    M2E - Maven Integration for Eclipse	2.0.4.20220904-1703	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

The IMavenProjectFacade explains that getMavenProject(IProgressMonitor) will lazily load the MavenProject, but it appears that doing this for multiple projects simultaneously on multiple threads exposes a bug in the ProjectRegistryManager's cache.

    java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$25(ProjectRegistryManager.java:1036)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.getMavenProject(ProjectRegistryManager.java:1036)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectFacade.getMavenProject(MavenProjectFacade.java:269)

**Comment by laeubi** [comment]
@timothyjward can you please try out the latest snapshot build, you can use this p2 repository:

https://download.eclipse.org/technology/m2e/snapshots/latest/

there where some recent changes and improvements regarding project caching.
