### ISSUE TITLE
Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.ArrayBinding.elementsType()" because "arrayBinding" is null

### ISSUE THREAD

**Issue by ahoehma** [eclipse-m2e/m2e-core#1111]
Not sure if this comes from m2e  ... but since today I got always this errors ... for any project in my ws.

Errors occurred during the build.
Errors running builder 'Java Builder' on project 'rest-service'.
Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.ArrayBinding.elementsType()" because "arrayBinding" is null

![image](https://user-images.githubusercontent.com/548214/205242083-c836c127-dba4-426c-bf7d-09f38a3d49c8.png)

Yesterday it was working ... but today .. after update ... it crashes...

![image](https://user-images.githubusercontent.com/548214/205250547-0428beda-41be-4705-8827-9c0bda8864f7.png)

May I have to update PDE/JDT too? But which update-site?

PS: https://stackoverflow.com/questions/74652558/cannot-invoke-org-eclipse-jdt-internal-compiler-lookup-arraybinding-elementstyp

**Comment by HannesWell** [comment]
Can you please provide the stack-traces from the error? That probably makes it easier to identify the root cause.

**Comment by ahoehma** [comment]
Yep...

`java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.ArrayBinding.elementsType()" because "arrayBinding" is null
at org.eclipse.jdt.internal.compiler.codegen.CodeStream.newArray(CodeStream.java:6656)
at org.eclipse.jdt.internal.compiler.codegen.TypeAnnotationCodeStream.newArray(TypeAnnotationCodeStream.java:87)
at org.eclipse.jdt.internal.compiler.ast.ArrayInitializer.generateCode(ArrayInitializer.java:82)
at org.eclipse.jdt.internal.compiler.ast.ArrayInitializer.generateCode(ArrayInitializer.java:70)
at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.generateCode(ReturnStatement.java:232)
at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:355)
at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.generateCode(AbstractMethodDeclaration.java:292)
at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:761)
at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:824)
at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:754)
at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:831)
at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:412)
at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:916)
at org.eclipse.jdt.internal.compiler.ProcessTaskManager.run(ProcessTaskManager.java:145)
at java.base/java.lang.Thread.run(Thread.java:1589)`

**Comment by HannesWell** [comment]
Indeed that does not look related.
Are you using the Eclipse latest (i.e. the Milestones and Release-Candidates) ?
And can you try to uninstall m2e and install the previous release M2E 2.1.1.
It is available here: https://download.eclipse.org/technology/m2e/releases/2.1.1/
You probably have to remove/disable the update-site https://download.eclipse.org/technology/m2e/releases/latest

If that makes the problem to vanish it was probably the bug-fix in-between. But beware that if you have the maven-enforcer-plugin configured without a `requiredJavaVersion` rule M2E 2.1.1 is flawed (that is the bug fix).
Alternativly you may want to try [2.1.0](https://download.eclipse.org/technology/m2e/releases/2.1.0/)

**Comment by ahoehma** [comment]
I'm back to 2.1.1 (1st delete m2e + 2nd install from 2.1.1)  - restart

![image](https://user-images.githubusercontent.com/548214/205276670-65f8db13-4920-4e68-9a76-a134231070cd.png)

Error is still there ...

I will try to go back to 2.1.0

**Comment by ahoehma** [comment]
Same with 2.1.0 :O So its something else ... ugly :)

**Comment by ahoehma** [comment]
I got the error ... unbelievable :-) 

It was because of adding a suggested lombok annotation into my code for an array.

![image](https://user-images.githubusercontent.com/548214/205284885-273ab081-eeda-4fbc-b090-fb66d52992c2.png)

So nothing todo with m2e ... sorry guys :)

**Comment by fbricon** [comment]
@ahoehma please open a ticket in https://github.com/eclipse-jdt/eclipse.jdt.core/issues

**Comment by ahoehma** [comment]
@fbricon  I report to lombok https://github.com/projectlombok/lombok/issues/3306 ... do you think I should report to jdt too?

**Comment by fbricon** [comment]
@ahoehma I think JDT should be made more robust in case an annotation processor like Lombok misbehaves, and not fail the build completely. At the very least, useful or actionable errors should be reported. But I'm not intimate with JDT, and the JDT team might feel differently about it though.

**Comment by ahoehma** [comment]
Done https://github.com/eclipse-jdt/eclipse.jdt.core/issues/575
