### ISSUE TITLE
StackOverflow during maven import

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-m2e/m2e-core#1115]
During import ("Import" -> "Exisitng Maven Project") of a repository that has valid [1] pom hierarchy there is an error:

```
java.lang.StackOverflowError
	at org.eclipse.m2e.core.internal.IMavenToolbox.clearProjectBuildingRequest(IMavenToolbox.java:144)
	at org.eclipse.m2e.core.internal.IMavenToolbox.clearProjectBuildingRequest(IMavenToolbox.java:144)
	at org.eclipse.m2e.core.internal.IMavenToolbox.clearProjectBuildingRequest(IMavenToolbox.java:144)
```
Unfortunately, I cannot attach the data, but it looks like M2E managed to find a cycle in a pom hierarchy.

[1] since it can produce a p2 repo after building from the root pom.xml

**Comment by HannesWell** [comment]
@laeubi any immediate idea?

@ruspl-afed can you provide a minimal reproducer for your problem? Ideally as test-case in a corresponding test-plugin.

**Comment by laeubi** [comment]
> any immediate idea?

https://github.com/eclipse-m2e/m2e-core/pull/1119

But this is just a guess, I really can't think about how such  "valid [1] pom hierarchy" could look like, it must be something like one parent in the chain references another one as the parent, so an example would be great...
