### ISSUE TITLE
m2e doesn't honor configured repositories in settings.xml when resolving target platform artifacts

### ISSUE THREAD

**Issue by henryju** [eclipse-m2e/m2e-core#1121]
Hi,

I am using m2e 2.1.2, on Eclipse 2022-09.

I'm using the recent feature allowing me to reference Maven artifacts in a PDE target platform. Something like:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="myTarget" sequenceNumber="1">
  <locations>
	  <location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" missingManifest="error" type="Maven">
		  <dependencies>
			  <dependency>
				  <groupId>my.company</groupId>
				  <artifactId>private-artifact</artifactId>
				  <version>X.Y</version>
				  <type>jar</type>
			  </dependency>
		  </dependencies>
	  </location>
  </locations>
</target>
```

I also have configured my company's repositories in my ~/.m2/settings.xml to something like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <profiles>
    <profile>
      <id>company-repo</id>
      <activation>
        <property>
          <name>!skip-company-repo</name>
        </property>
      </activation>
      <repositories>
        <repository>
          <id>company</id>
          <name>Company Central Repository</name>
          <url>https://foo</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
</settings>
```

this work fine when using Maven + Tycho from command line, but it was failing when trying to load the target platform in Eclipse. It seems like m2e was only attempting to resolve the dependency from Maven Central:

```text
org.eclipse.aether.transfer.ArtifactTransferException: my.company:private-artifact:jar:X.Y failed to transfer from https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact my.company:private-artifact:jar:X.Y from/to central (https://repo.maven.apache.org/maven2): The operation was cancelled.
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:225)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:189)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:574)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:484)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$6(MavenImpl.java:565)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:556)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:541)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveDependency(MavenTargetLocation.java:246)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveArtifacts(MavenTargetLocation.java:172)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveBundles(MavenTargetLocation.java:156)
	at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:96)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:428)
	at org.eclipse.pde.internal.ui.editor.targetdefinition.TargetEditor$TargetChangedListener$1.run(TargetEditor.java:606)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

As a workaround, I had to ensure the dependency was downloaded in my local repo using a command line build, and then remove the `_remote.repositories` file (else I guess the dependency was marked from originated from my company's repo, and m2e was still trying to get it from Maven Central.

**Comment by laeubi** [comment]
For targets, repositories must be configured in the target itself as additional repositories.

**Comment by henryju** [comment]
OK, good to know. Feel free to close this issue if you consider this is the expected user experience.

**Comment by laeubi** [comment]
It could also work via the settings, but I think you need a profile that is "active by default" like described here:

https://maven.apache.org/guides/mini/guide-multiple-repositories.html

The target platform uses the "global" settings only because a target is not connected to a project. I'm not sure if property activated profiles are actually evaluated in this case.

**Comment by henryju** [comment]
I confirm adding an "active by default" configuration in global settings.xml worked. So it seems you are right, "property activated profiles" are not supported. Should I open a separate issue?

**Comment by laeubi** [comment]
You can try to open an issue but I'm not sure if this is probably "expected" profile activation is somehow strange in maven :-)
