### ISSUE TITLE
constant exceptions when building: java.lang.AssertionError: org.eclipse.core.runtime.CoreException: container creation failed

### ISSUE THREAD

**Issue by jcompagner** [eclipse-m2e/m2e-core#1122]
below the exception i think this is because we use tycho and have configured in the .mvn dir of the (root) project dir a tycho extension file that has:

```
<extensions>
    <extension>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-build</artifactId>
        <version>${tycho.version}</version>
    </extension>
</extensions>
```

to have the version in 1 place we have also in that same .mvn dir a maven.config file:

`-Dtycho.version=2.7.5`

and i guess because of that m2e bombs out because it doesn't get the actual version..

so how can i get around that? m2e i guess could just fully ignore this..
And i don't also want to have hard tycho version in all the extensions.xml files..
because then i have it on a lot of places.

```
java.lang.AssertionError: org.eclipse.core.runtime.CoreException: container creation failed
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.flushMavenCache(MavenProjectCache.java:144)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.flushMavenCaches(MavenProjectCache.java:128)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.flushCaches(ProjectRegistryManager.java:1086)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.calculateFacadesForUpdate(ProjectRegistryManager.java:505)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:377)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:360)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:313)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:149)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:87)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:196)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.runtime.CoreException: container creation failed
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager$ExceptionalLookup.throwException(PlexusContainerManager.java:440)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager$ExceptionalLookup.lookup(PlexusContainerManager.java:430)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.flushMavenCache(MavenProjectCache.java:138)
	... 26 more
Caused by: org.codehaus.plexus.PlexusContainerException: can't create plexus container for basedir = C:\Users\jcomp\git\servoy_master\servoy-eclipse\shipplugins\pom.xml because the extension org.eclipse.tycho:tycho-build:${tycho.version} can't be loaded (defined in C:\Users\jcomp\git\servoy_master\servoy-eclipse\.mvn\extensions.xml).
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.aquire(PlexusContainerManager.java:182)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.getComponentLookup(PlexusContainerManager.java:204)
	... 27 more
Caused by: org.apache.maven.cli.internal.ExtensionResolutionException: Extension org.eclipse.tycho:tycho-build:${tycho.version} or one of its dependencies could not be resolved: org.eclipse.tycho:tycho-build:jar:${tycho.version} was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveExtension(BootstrapCoreExtensionManager.java:162)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveCoreExtensions(BootstrapCoreExtensionManager.java:108)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.loadCoreExtensions(BootstrapCoreExtensionManager.java:92)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.loadCoreExtensions(PlexusContainerManager.java:350)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.newPlexusContainer(PlexusContainerManager.java:222)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.aquire(PlexusContainerManager.java:177)
	... 28 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: org.eclipse.tycho:tycho-build:jar:${tycho.version} was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:425)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:226)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveCoreExtension(DefaultPluginDependenciesResolver.java:157)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveExtension(BootstrapCoreExtensionManager.java:153)
	... 33 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: org.eclipse.tycho:tycho-build:jar:${tycho.version} was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:217)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:189)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:574)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:484)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
	... 38 more
```

**Comment by laeubi** [comment]
> to have the version in 1 place we have also in that same .mvn dir a maven.config file:

m2e currently do not support `maven.config` at the extension level, you probably want to provide a test for this case so we can add support for it?

**Comment by HannesWell** [comment]
We started to work on this issue a while ago in https://github.com/eclipse-m2e/m2e-core/pull/852 but at the moment it staled a bit.
But I hope to be able to continue on this in the not too far future.

**Comment by laeubi** [comment]
@HannesWell this is a bit different here, because the maven config (actually only system properties) must be taken into account *before* the container is setup as `extensions.xml` is handled special in this regards!

**Comment by jcompagner** [comment]
for now i just hardcoded the version in the extentions.xml because it was not workable in eclipse (every build will trigger a dialog)

#852 seems to be covering this right?

**Comment by laeubi** [comment]
In general everything that works in maven should work in m2e. For a particular case it depends how good m2e can support that case, so at least a runable example would be required.

**Comment by laeubi** [comment]
@jcompagner this is now implemented, please try out the latest snapshot build, you can use this p2 repository:

https://download.eclipse.org/technology/m2e/snapshots/latest/
