### ISSUE TITLE
Temp project creation must be synchronized

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-m2e/m2e-core#1166]
I just ran into this when working with a selection following history and multiple editions of a POM file being opened in an editor. The part creating the temp project should be synchronized, as it can be triggered from multiple views etc. in parallel.
```
java.nio.file.FileAlreadyExistsException: C:\Users\foo\AppData\Local\Temp\maven-pom2651655955483527984.pom
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at java.base/java.nio.file.Files.copy(Files.java:3160)
	at org.eclipse.m2e.core.ui.internal.actions.SelectionUtil.getMavenProject(SelectionUtil.java:251)
	at org.eclipse.m2e.editor.pom.MavenPomEditor.readMavenProject(MavenPomEditor.java:707)
	at org.eclipse.m2e.editor.pom.MavenPomEditor$4.run(MavenPomEditor.java:1027)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by HannesWell** [comment]
Can you provide a PR to fix this?

**Comment by Bananeweizen** [comment]
Meanwhile I'm wondering if there is a good reason to copy the POM into a temp file at all. I'd expect none of the other involved classes to do any kind of file locking or similar. Does anyone a good reason for copying? Otherwise I would like to try the removal of the temp copy.

**Comment by laeubi** [comment]
I think it is copied when m2e things it is not a local file....
