### ISSUE TITLE
IDE freeze, stack seems related to m2e PDE support

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#1196]
My IDE is frozen; IIRC it happened while opening the org.eclipse.jdt.core project in my workspace.
The stack trace seems to say that the freeze may be caused by a long running operation running in UI Thread. I'm reporting it here as I see m2e involved, but maybe it's a more general PDE issue.

```
main" #1 [154073] prio=6 os_prio=0 cpu=6365860.94ms elapsed=60035.56s tid=0x00007fb71c0280e0 nid=154073 runnable  [0x00007fb720ffb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.SocketDispatcher.read0(java.base@19.0.1/Native Method)
	at sun.nio.ch.SocketDispatcher.read(java.base@19.0.1/SocketDispatcher.java:47)
	at sun.nio.ch.NioSocketImpl.tryRead(java.base@19.0.1/NioSocketImpl.java:251)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@19.0.1/NioSocketImpl.java:302)
	at sun.nio.ch.NioSocketImpl.read(java.base@19.0.1/NioSocketImpl.java:340)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@19.0.1/NioSocketImpl.java:789)
	at java.net.Socket$SocketInputStream.read(java.base@19.0.1/Socket.java:1025)
	at sun.security.ssl.SSLSocketInputRecord.read(java.base@19.0.1/SSLSocketInputRecord.java:477)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(java.base@19.0.1/SSLSocketInputRecord.java:471)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(java.base@19.0.1/SSLSocketInputRecord.java:70)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(java.base@19.0.1/SSLSocketImpl.java:1465)
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(java.base@19.0.1/SSLSocketImpl.java:1069)
	at java.io.BufferedInputStream.fill(java.base@19.0.1/BufferedInputStream.java:255)
	at java.io.BufferedInputStream.read1(java.base@19.0.1/BufferedInputStream.java:310)
	at java.io.BufferedInputStream.implRead(java.base@19.0.1/BufferedInputStream.java:382)
	at java.io.BufferedInputStream.read(java.base@19.0.1/BufferedInputStream.java:361)
	at sun.net.www.http.HttpClient.parseHTTPHeader(java.base@19.0.1/HttpClient.java:827)
	at sun.net.www.http.HttpClient.parseHTTP(java.base@19.0.1/HttpClient.java:759)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@19.0.1/HttpURLConnection.java:1684)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@19.0.1/HttpURLConnection.java:1585)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(java.base@19.0.1/HttpsURLConnectionImpl.java:224)
	at java.net.URL.openStream(java.base@19.0.1/URL.java:1162)
	at org.eclipse.m2e.core.internal.MavenArtifactIdentifier.identifyCentralSearch(MavenArtifactIdentifier.java:85)
	at org.eclipse.m2e.core.internal.MavenArtifactIdentifier.identify(MavenArtifactIdentifier.java:69)
	at org.eclipse.m2e.pde.target.MavenPluginSourcePathLocator.locateSource(MavenPluginSourcePathLocator.java:40)
	at org.eclipse.pde.internal.core.SourceLocationManager.lambda$0(SourceLocationManager.java:325)
	at org.eclipse.pde.internal.core.SourceLocationManager$$Lambda$1200/0x0000000100d1f3e0.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(java.base@19.0.1/ReferencePipeline.java:197)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(java.base@19.0.1/ArrayList.java:1602)
	at java.util.stream.ReferencePipeline.forEachWithCancel(java.base@19.0.1/ReferencePipeline.java:129)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(java.base@19.0.1/AbstractPipeline.java:527)
	at java.util.stream.AbstractPipeline.copyInto(java.base@19.0.1/AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@19.0.1/AbstractPipeline.java:499)
	at java.util.stream.FindOps$FindOp.evaluateSequential(java.base@19.0.1/FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(java.base@19.0.1/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(java.base@19.0.1/ReferencePipeline.java:647)
	at org.eclipse.pde.internal.core.SourceLocationManager.searchExtensionLocations(SourceLocationManager.java:329)
	at org.eclipse.pde.internal.core.SourceLocationManager.findSourcePath(SourceLocationManager.java:88)
	at org.eclipse.pde.internal.core.ClasspathUtilCore.getSourceAnnotation(ClasspathUtilCore.java:193)
	at org.eclipse.pde.internal.core.PDEClasspathContainer.addExternalPlugin(PDEClasspathContainer.java:90)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addPlugin(RequiredPluginsClasspathContainer.java:352)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:297)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:280)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.computePluginEntries(RequiredPluginsClasspathContainer.java:162)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.getClasspathEntries(RequiredPluginsClasspathContainer.java:112)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3277)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3435)
	at org.eclipse.jdt.internal.core.ClasspathChange.generateDelta(ClasspathChange.java:247)
	at org.eclipse.jdt.internal.core.ChangeClasspathOperation.classpathChanged(ChangeClasspathOperation.java:68)
	at org.eclipse.jdt.internal.core.SetContainerOperation.executeOperation(SetContainerOperation.java:117)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
	at org.eclipse.jdt.core.JavaCore.setClasspathContainer(JavaCore.java:6025)
	at org.eclipse.pde.internal.core.PluginModelManager.updateAffectedEntries(PluginModelManager.java:398)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChangedSynchronized(PluginModelManager.java:305)
	at org.eclipse.pde.internal.core.PluginModelManager.modelsChanged(PluginModelManager.java:244)
	- locked <0x00000000b195f430> (a java.lang.Object)
	at org.eclipse.pde.internal.core.AbstractModelManager.fireModelProviderEvent(AbstractModelManager.java:37)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.createAndFireEvent(WorkspaceModelManager.java:343)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.createAndFireEvent(WorkspacePluginModelManager.java:549)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:322)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.processModelChanges(WorkspaceModelManager.java:280)
	at org.eclipse.pde.internal.core.WorkspacePluginModelManager.processModelChanges(WorkspacePluginModelManager.java:538)
	at org.eclipse.pde.internal.core.WorkspaceModelManager.resourceChanged(WorkspaceModelManager.java:169)
	at org.eclipse.jdt.internal.core.DeltaProcessingState$1.run(DeltaProcessingState.java:496)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:489)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1514)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2394)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ui.ide.undo.AbstractWorkspaceOperation.execute(AbstractWorkspaceOperation.java:200)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:496)
	at org.eclipse.ui.internal.navigator.resources.actions.OpenFolderAsProjectAction.run(OpenFolderAsProjectAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.jface.action.ActionContributionItem$$Lambda$504/0x00000001006ae240.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.ui.internal.Workbench$$Lambda$223/0x000000010029ee58.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.base@19.0.1/DirectMethodHandle$Holder)
	at java.lang.invoke.LambdaForm$MH/0x00000001000c5800.invoke(java.base@19.0.1/LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/0x00000001000c5c00.invokeExact_MT(java.base@19.0.1/LambdaForm$MH)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@19.0.1/DirectMethodHandleAccessor.java:156)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@19.0.1/DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(java.base@19.0.1/Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by mickaelistria** [comment]
and this seems to be a blocker as the same stack prevents my IDE from starting.

**Comment by laeubi** [comment]
Seems it originates here: `org.eclipse.ui.internal.navigator.resources.actions.OpenFolderAsProjectAction` so probably on can get some idea if this should probably run as a job in the background.

**Comment by mickaelistria** [comment]
A workaround is to remove m2e PDE: `~/apps/eclipse-SDK/plugins$ mv org.eclipse.m2e.pde.target_2.0.300.20221218-1452.jar org.eclipse.m2e.pde.target_2.0.300.20221218-1452.jar_`

> Seems it originates here: org.eclipse.ui.internal.navigator.resources.actions.OpenFolderAsProjectAction so probably on can get some idea if this should probably run as a job in the background.

Most likely yes. But still, there would  be a risk the the same freeze runs in another thread and blocks the workspace; so I believe we need something to deal with it in m2e. If this is a separate job, then the "stop button"/cancel action will need to be honored.

**Comment by laeubi** [comment]
m2e can't do much here as it is not in control of the call. `org.eclipse.pde.internal.core.SourceLocationManager` is calling for a source and m2e can not delay the answer here...

**Comment by HannesWell** [comment]
> and this seems to be a blocker as the same stack prevents my IDE from starting.

Yes, I noticed that as well. This can incredibly slow down Eclipse if there are many IUs in the target that don't have another source for code-sources.

This is since https://github.com/eclipse-m2e/m2e-core/pull/853. If we don't have a fast solution, I suggest to disable at least the search in Maven-Central. I sampled my Eclipse to find out what happened with VisalVM and IIRC it could take about a second to check for the sources of one artifact this way.

However to solve this we could try if a BufferedReader makes a difference (it looks like the JASONReader only uses a buffer of 1kB while BufferedReader uses 8kB), but I don't expect much.
Besides that we could 
1. Cache the query-result in the workspace-state location of the m2e.pde plugin, as simple properties-file mapping the bundles path to the result of the look-up (the path should not change, because the artifact is probably either in the workspace-bundle-pool or the m2-folder)
2. Save the query-result in a user-global cache (maybe in `<user-home>.m2\repository\.cache\m2e`), where the file-hash is used as key so that m2e does not look up the same artifact again from different workspaces.

While the former should be relatively simple to achieve with a properties-file, latter would be more difficult because the user-global cache can be accessed and modified by multiple Eclipse+m2e instances at the same time.
Do you know a suitable file-based cache that can handle that?

Nevertheless it would be good to perform all of that in a background job so that even the first time is not blocked.
Wouldn't it be possible to just return null if the Maven-Central would really have been queried and spawn a background-thread that waits for the query results and when that arrived to set the result (if there is any) into the resolved classpath?

**Comment by laeubi** [comment]
> I suggest to disable at least the search in Maven-Central

I think in general there should be a setting for using central search that is off by default, especially as we more and more will use real maven artifacts and we should encourage people to actually use them instead of rely on m2e to find random things. As this is also used in the debugger it could slow things don there as well

> However to solve this we could try if a BufferedReader makes a difference

The slowest part will not be the transfer, but generating the hash, contacting central, waiting for a response ... we could probabbly use Java 11 Httpclient so we can take advantage of Http2, but I think the transfer itself will not be much of an issue here as most likley gzip compression is used (is it?) the size will decrease even more...

> Cache the query-result in the workspace-state location of the m2e.pde plugin

I think this would be preferable, a global cache is just too much work here

> Nevertheless it would be good to perform all of that in a background job so that even the first time is not blocked.

I rather would disable Maven Central search instead of this then... this is just too much effort as m2e really has no way to gather all information, so we also need to update PDE, so if one want this, it would better be handled there.

But instead of implementing such complex background-queue I wonder why this must be compute beforehand anyways? Why can't it be queried in that time where the source is first accessed, that way only sources will ever searched the user actually needs (e.g. when debugging or open a file) it would be probably slower then but faster in general for all those items one probably never access the source, I just don't know if JDT supports this or this would require a change to ask the Classpath Container on demand for the source.

**Comment by mickaelistria** [comment]
Could the maven-central request have a timeout? Or could PDE be changed so the Source lookup doesn't happen in the UI Thread nor in a workspace runnable?

**Comment by laeubi** [comment]
I think we can have a timeout, but does it really hang "forever" for you or is it just as hannes saying the amount of request that make it slow? I think thet JDT must be changed first, I'll propose an enhancement for that but won't be able to work on this for the next weeks, but probably others are interested as well...

**Comment by mickaelistria** [comment]
> I think we can have a timeout, but does it really hang "forever"

I really see a freeze, the IDE doesn't start. Maybe if I wait 5 minutes the IDE would start but I don't see much hope.

**Comment by laeubi** [comment]
I think it should be quite easy to replace this with Java 11 HttptClient and there one can set a timeout (e.g. 10 seconds).

**Comment by laeubi** [comment]
I have created now:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/639

what would be a prerequisite for PDE without doing a lot of special handling here.

**Comment by HannesWell** [comment]
> 
> But instead of implementing such complex background-queue I wonder why this must be compute beforehand anyways? Why can't it be queried in that time where the source is first accessed, that way only sources will ever searched the user actually needs (e.g. when debugging or open a file) it would be probably slower then but faster in general for all those items one probably never access the source, I just don't know if JDT supports this or this would require a change to ask the Classpath Container on demand for the source.

That would IMHO be the ideal case. At least for such heavy-weight look ups like querying central.

> > Nevertheless it would be good to perform all of that in a background job so that even the first time is not blocked.
> 
> I rather would disable Maven Central search instead of this then... this is just too much effort as m2e really has no way to gather all information, so we also need to update PDE, so if one want this, it would better be handled there.

For now I suggest to simply disable the search in central in case of source look ups until there is a better/more lazy solution. The debugger is not that much of a problem, because it only looks up one artifact at the time and not arbitrary many.
In https://github.com/eclipse-m2e/m2e-core/pull/1067 I already speeded that up, by first looking into the artifact jar and only then querying central.

In general I wonder how high the chances are actually, that querying central for the file hash is successful, after the look-up for maven-coordinates in the jar failed? Since it is the default in the jar-plugin to add the `pom.xml` and `pom.properties` file with the coordinates, I would assume that most artifacts on central have them. If one then has an altered jar that does not contain them the file-hash is also different and therefore the look-up on central will fail too. So that will only help if artifacts are published without the `pom.properties`.


> Could the maven-central request have a timeout? Or could PDE be changed so the Source lookup doesn't happen in the UI Thread nor in a workspace runnable?

> > I think we can have a timeout, but does it really hang "forever"
> 
> I really see a freeze, the IDE doesn't start. Maybe if I wait 5 minutes the IDE would start but I don't see much hope.

A time-out would definitely not harm, but from my experience I don't expect much improvement, unless the internet connection is the issue.

I'm about to prepare a PR to disable the central-search for the source look-up.

**Comment by mickaelistria** [comment]
> A time-out would definitely not harm, but from my experience I don't expect much improvement, unless the internet connection is the issue.

The server can be the cause of the timeout. It's currently what's happening with search.maven.org suddenly becoming slow and hurting Tycho and m2e hardly. So it's not an hypothetical case but the current problem we're (at least I am) facing..

**Comment by laeubi** [comment]
> Since it is the default in the jar-plugin to add the `pom.xml` and `pom.properties` file with the coordinates, I would assume that most artifacts on central have them.

Yeah, but platform has own "best-practices" that include:

- do not follow maven best practice
- write bogus data that actually do not map the maven coordinates

> I'm about to prepare a PR to disable the central-search for the source look-up.

I think we should just have a preference (with default off) for this.

**Comment by HannesWell** [comment]
> > A time-out would definitely not harm, but from my experience I don't expect much improvement, unless the internet connection is the issue.
> 
> The server can be the cause of the timeout. It's currently what's happening with search.maven.org suddenly becoming slow and hurting Tycho and m2e hardly. So it's not an hypothetical case but the current problem we're (at least I am) facing..

Of course, for me that is part of the connection 😅
Maybe it is also a combination of both. If you wait 10s for the sources of each artifact, it feels like waiting forever, depending on the number of units in the TP for which sources are searched. Nevertheless I experience an extreme slow-down as well.

> 
> > I'm about to prepare a PR to disable the central-search for the source look-up.
> 
> I think we should just have a preference (with default off) for this.

That would not harm, but at the moment I can barley do anything in m2e, so I would prefer to go with just disabling the central search first. Nevertheless as said above, I expect the hit-rate of the central-search to be very low in general.
