### ISSUE TITLE
Maven Update Project never completes and never cancels

### ISSUE THREAD

**Issue by davidmichaelkarr** [eclipse-m2e/m2e-core#1226]
Using Eclipse 2022-12 on Windows 11.

I work on and provide support for an enterprise with many dozens of SpringBoot Maven projects, all stored in git.  In the vast majority of cases, after I import the project if m2e is "confused" about the project, doing a "Maven"->"Update Project" cleans it all up, getting all the correct source directories and eventually getting rid of all the red marks.

There are at least a couple that I've seen that consistently give "Maven Update" problems. The one project I'm currently looking at is a project that gets to 75% in Maven Update, but never completes, and if I eventually give up and Cancel it, it stays in "Cancel Requested" state forever.  The only thing that "works" is killing the process, but when I restart Eclipse, it just resumes trying to do that Maven Update. It's slightly annoying that the Progress dialog just says "Updating Maven Project" (and now with "(Cancel Requested)"), but it doesn't say WHICH project. I assume it's the one that I requested it on earlier, but it's unfortunate that it doesn't tell me which one it is now.  At this point, it appears it will be stuck in this state forever.  It never completes the Maven Update, and it never cancels, and this blocked action blocks all other actions, so I am dead in the water.  I can't even close the project.

I'll attach the .metadata/.log file, but I've looked through it, and although it has exceptions, I don't see anything that obviously relates to this problem.

[eclipse.log](https://github.com/eclipse-m2e/m2e-core/files/10562668/eclipse.log)

I'm also including a thread dump.

[threaddump.txt](https://github.com/eclipse-m2e/m2e-core/files/10562790/threaddump.txt)

I could give someone the pom.xml, but I don't want to attach it to this issue. I'd prefer that be kept out of it.

There is also another particular project that has another odd symptom with Maven Update.  The Maven Update runs for a few seconds, and when it completes, I find that it did exactly nothing.  It never even created the .classpath file.  Fortunately, the required structure is very similar to other projects, so I'm able to simply copy the .classpath file from a similar project and make very small changes to it, and the resulting .classpath file results in no Eclipse build errors.

**Comment by laeubi** [comment]
It seems being stuck here:
```
"Worker-313: Updating Maven Project" #383 prio=5 os_prio=0 cpu=12187.50ms elapsed=3054.86s tid=0x000002943154dae0 nid=36040 in Object.wait()  [0x0000009f99dfe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@18.0.2.1/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1074)
        - locked <0x000000076508ea58> (a java.util.Collections$SynchronizedSet)
        at org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.removeFolder(GeneratedSourceFolderManager.java:508)
        at org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.folderNamePreferenceChanged(GeneratedSourceFolderManager.java:321)
        at org.eclipse.jdt.apt.core.internal.AptProject.preferenceChanged(AptProject.java:81)
        at org.eclipse.jdt.apt.core.util.AptConfig.setString(AptConfig.java:969)
        at org.eclipse.jdt.apt.core.util.AptConfig.setGenSrcDir(AptConfig.java:917)
        at org.eclipse.m2e.apt.internal.AbstractAptConfiguratorDelegate.configureProject(AbstractAptConfiguratorDelegate.java:171)
        at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.lambda$0(AbstractAptProjectConfigurator.java:95)
        at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator$$Lambda$1981/0x0000000801c99548.call(Unknown Source)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
        at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.configure(AbstractAptProjectConfigurator.java:88)
        at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:123)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:494)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1979/0x0000000801c97078.call(Unknown Source)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:488)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:416)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1978/0x0000000801c96e38.test(Unknown Source)
        at java.util.Collection.removeIf(java.base@18.0.2.1/Collection.java:576)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:410)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:340)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1964/0x0000000801c96a08.call(Unknown Source)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:364)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:213)
        at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1102)
        at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:339)
        at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by laeubi** [comment]
@davidmichaelkarr can you possibly provide a reproducer project?

**Comment by jgagnon44** [comment]
I don't think it's project related.
