### ISSUE TITLE
Source Look up 

### ISSUE THREAD

**Issue by victorkevin2** [eclipse-m2e/m2e-core#1267]
I got a lastest Release version : Version: 2022-12 (4.26.0) Build id: 20221201-1913 ，My Web project is kind of gradle builder , When debug in web runtime ,sources of web module work well but api module can't lookup the source ,and appears "edit source lookup " view , however adding source directories or project type ,still unfound it , Never met before version，that can work it well on the main application or junit s test debug environment ，other I tried it in the Version: 2022-09 (4.25.0) Build id: 20220908-1902 still same as before . I fallback to Version: 2022-06 (4.24.0) Build id: 20220609-1112 . It 's doing well ! below is relevant lookings , I hope that can help you ,THX
`!ENTRY org.eclipse.debug.core 4 125 2023-02-22 14:12:59.063
!MESSAGE Error logged from Debug Core: 
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.util.Collection.isEmpty()" because "classesArtifacts" is null
	at org.eclipse.m2e.sourcelookup.internal.launch.MavenSourceContainerResolver.resolveSourceContainers(MavenSourceContainerResolver.java:40)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.getSourceContainer(AdvancedSourceLookupParticipant.java:144)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.findSourceElements(AdvancedSourceLookupParticipant.java:72)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:138)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:473)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:714)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:303)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupTask.run(SourceLookupFacility.java:752)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:690)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

`!ENTRY org.eclipse.debug.core 4 2 2023-02-22 14:12:59.062
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.debug.core".
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.util.Collection.isEmpty()" because "classesArtifacts" is null
	at org.eclipse.m2e.sourcelookup.internal.launch.MavenSourceContainerResolver.resolveSourceContainers(MavenSourceContainerResolver.java:40)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.getSourceContainer(AdvancedSourceLookupParticipant.java:144)
	at org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedSourceLookupParticipant.findSourceElements(AdvancedSourceLookupParticipant.java:72)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector$SourceLookupQuery.run(AbstractSourceLookupDirector.java:138)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.doSourceLookup(AbstractSourceLookupDirector.java:473)
	at org.eclipse.debug.core.sourcelookup.AbstractSourceLookupDirector.getSourceElement(AbstractSourceLookupDirector.java:714)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.lookup(SourceLookupFacility.java:303)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupTask.run(SourceLookupFacility.java:752)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceLookupJob.run(SourceLookupFacility.java:690)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`

**Comment by laeubi** [comment]
Please try out the latest snapshot build, you can use this p2 repository:

https://download.eclipse.org/technology/m2e/snapshots/latest/

I think we have a bugfix for this there already!

**Comment by phinney** [comment]
I tried laeybi's suggestion and it didn't work for me! I'm using "Version: 2022-12 (4.26.0) Build id: 20221201-1913"  just as victokevin2. I think I'll try victorkevin2 suggestion of falling back to 2022-06, because it worked in prior versions. I will add one wierd comment, I reinstalled 2022-12 a second time, and the source not found problem went away for just one debug session.  I'm debugging a Tomcat servlet, and I probably restarted the Tomcat server in debug mode and that's when it stopped working. I'm able to debug and step through my servlet code, I just can't debug code that comes from the WEB-INF/lib directory.  Those are the classes that get the source not found issue.  Those jars are in the source path, and the jars themselves do contain both class and java files in them. I can step though the code and watch the stacktrace and line numbers, I just don't get to see the code that I'm stepping through. Everything I've tried to add them to the source path doesn't work.  And as I said, they actually are already on the default source path.

**Comment by laeubi** [comment]
@phinney please make sure the latest release is installed:

https://download.eclipse.org/technology/m2e/releases/latest/

then share an updated stack-trace if the problem persist, maybe with a little project+steps how to reproduce the problem.
