### ISSUE TITLE
M2E Connector for license-maven-plugin stopped working in 2022-12 and 2023-03

### ISSUE THREAD

**Issue by ctubbsii** [eclipse-m2e/m2e-core#1332]
All the details are at https://github.com/mathieucarbou/license-maven-plugin/issues/523, but essentially, Eclipse generates a lot of errors when importing a project that uses that Maven plugin.

<details>
<summary>
When I import the project into Eclipse 2023-03, I get the following errors (click to expand):
</summary>

```
Description	Resource	Path	Location	Type
Failed to execute mojo com.mycila:license-maven-plugin:4.1:format {execution: license-headers} (com.mycila:license-maven-plugin:4.1:format:license-headers:process-test-resources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo com.mycila:license-maven-plugin:4.1:format {execution: license-headers}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$1(MavenBuilderImpl.java:139)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:122)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution license-headers of goal com.mycila:license-maven-plugin:4.1:format failed: Cannot read header document /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt. Cause: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
Caused by: java.lang.IllegalArgumentException: Cannot read header document /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt. Cause: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at com.mycila.maven.plugin.license.header.HeaderSource.of(HeaderSource.java:237)
	at com.mycila.maven.plugin.license.AbstractLicenseMojo.executeForLicenseSet(AbstractLicenseMojo.java:459)
	at com.mycila.maven.plugin.license.AbstractLicenseMojo.executeForLicenseSets(AbstractLicenseMojo.java:429)
	at com.mycila.maven.plugin.license.AbstractLicenseMojo.execute(AbstractLicenseMojo.java:391)
	at com.mycila.maven.plugin.license.LicenseFormatMojo.execute(LicenseFormatMojo.java:69)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 33 more
Caused by: org.apache.maven.plugin.MojoFailureException: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:112)
	at com.mycila.maven.plugin.license.header.HeaderSource.of(HeaderSource.java:233)
	... 38 more
Caused by: java.net.MalformedURLException: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at java.base/java.net.URL.<init>(URL.java:674)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:107)
	... 39 more
	pom.xml	/accumulo-core	line 24	Maven Build Problem
```

</details>

**Comment by mickaelistria** [comment]
Does `/home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt` exist?

**Comment by ctubbsii** [comment]
> Does `/home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt` exist?

Yes.

**Comment by laeubi** [comment]
The problem is not that the file is not there, but that the maven plugin seems to require an **URL** instead of a **file**:

**MalformedURLException: no protocol:**:

```
Caused by: java.net.MalformedURLException: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at java.base/java.net.URL.<init>(URL.java:674)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:107)
```

so either the plugin should be smart enough to detect that this is a local file, or the reference should be something like:

`file:/home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt`

**Comment by ctubbsii** [comment]
This works fine in 2022-09. And, if I upgrade from Eclipse 2022-09 to 2022-12 *after* resolving this plugin, it still works. The error only appears if I use 2022-12 or 2023-03 to resolve the plugin the first time. And, it works fine from the command-line... which means it doesn't seem like it's the plugin's fault... but perhaps something in the M2E Connector. Could the M2E Connector using a different version of the plugin than the one specified in the POM?

**Comment by ctubbsii** [comment]
Also, the error only appears on the sub-modules in the multi-module build. It seems to work if it's a single Maven module. However, in that case, the plugin can't resolve, because the M2E Connector couldn't be found on the server to be added to Eclipse. But, this error didn't appear in the single-module case.

**Comment by ctubbsii** [comment]
Again, all this works on 2022-09.

**Comment by laeubi** [comment]
"worked before" could also mean it was never executed before, with a quick look I can't find that they provide a connector or mappings for their plugin so this is executed "as is" what might or might not work depending on the style / usage, e.g. the first basic test would be if you can execute a failing **submodule** on the commandline without an error.

If you can you provide a small reproducer project it might be much easier to look into this.

**Comment by ctubbsii** [comment]
@laeubi I don't know how it is resolving the connector, but when it works in 2022-09 (and earlier), it resolves to: `basepom.org	m2e extension for the Mycila license plugin.	1.1.0	org.basepom.m2e.mycila-license` (that's how it's listed in the installation details of Eclipse after resolving the M2E connector for the plugin. If it was never executed before... I'm fine with that, but it doesn't explain why the error is coming *before* resolving the connector, and why it does *not* appear *after* resolving the connector using an earlier version of Eclipse.

I'm also fine with not executing it now. I don't depend on its execution in M2E... I'm happy to have it run on the command-line only. I would add my own `<ignore/>` lifecycle mapping rule in my POM, like I have for other, similarly situated plugins. However, that would just hide this error... and I think the underlying error is probably worth fixing.

See the attached small multi-module reproducer.
[reproduce-m2e-connector-fail.tar.gz](https://github.com/eclipse-m2e/m2e-core/files/11103086/reproduce-m2e-connector-fail.tar.gz)

**Comment by laeubi** [comment]
I downloaded your example and can confirm that it gives an error (please note the additional module directory in it!)

`Caused by: java.net.MalformedURLException: no protocol: /tmp/reproduce-m2e-connector-fail/fail-module/contrib/license-header.txt`

when i navigate to that path, there is no such file, after creating the the build immediately turns to green and works.

So I think the problem is more with the configuration that uses:
` <header>${session.executionRootDirectory}/contrib/license-header.txt</header>`

The `${session.executionRootDirectory}` is most likely not useful outside of an reactor build started from the root thats why it fails for m2e becaue it executes each project independently (and thus the value changes for each of your submodules).

What can work is, that you create a `.mvn` folder in the root of your project and use `${maven.multiModuleProjectDirectory}` instead (what is supported by m2e recently), but be aware that this is also an "unofficial" property see discussion here:
- https://issues.apache.org/jira/browse/MNG-7038

**Comment by laeubi** [comment]
I can only tell that it works for the current version if the variable is pointing to a valid file (what is previously did not for submodules). I also don't get any connectors suggested to install, so probably the connector you mentioned simply suppressed the execution or did any other tricks.

As explained m2e does not (and has never) executes a multi-module build, it executes selected mojos by creating a minimal execution context and a session, and your build will fail in the same way if you execute any of the submodules directly so this is not specific to m2e

> I had thought the `${session.executionRootDirectory}` was the official way to do it,

I can't find any documentation about that, at least as explained it is dependent on where you start the execution (what must not necessarily be the folder you expect it to be), so it is a moving target and not really suited for an absolute path.

**Comment by ctubbsii** [comment]
Closing this, since the auto-magical lifecycle binding to execute the license-maven-plugin's goals seems to work fine when using the build-helper-maven-plugin to resolve the path to the root of the multi-module project.

**Comment by ctubbsii** [comment]
My previous solution to use build-helper-maven-plugin to set the property containing the root location no longer seems to be working. I'm now getting the same error that I was getting before. I think it's because `${rootlocation}` isn't being set. The strange thing is that this error is only happening for 3 of my 16 modules. The other 13 have no error. This makes no sense.

I would just set this plugin's execution to be ignored in the M2E settings in the POM, like so many other plugins that don't work in M2E, except this *did* work in previous versions without error, and there *is* an M2E connector (see comment above) whose resolution this plugin triggers in earlier versions of Eclipse, and this *does* work if I install the older version of Eclipse and upgrade to the latest... it just doesn't work if I install the latest directly. It'd be really nice to not have to downgrade to things working every time again.

**Comment by laeubi** [comment]
I provided you with a working solution, so its up to you choosing another one that is only working in certain circumstances, but you probably need to debug the [build-helper-maven-plugin](https://www.mojohaus.org/build-helper-maven-plugin/rootlocation-mojo.html) to understand whats going on.

>  It'd be really nice to not have to downgrade to things working every time again.

You can always use an older version of Eclipse/m2e or provide a valid example, your previous one was not valid as explained.

**Comment by ctubbsii** [comment]
> I provided you with a working solution, so its up to you choosing another one that is only working in certain circumstances, but you probably need to debug the [build-helper-maven-plugin](https://www.mojohaus.org/build-helper-maven-plugin/rootlocation-mojo.html) to understand whats going on.

@laeubi - Sorry, I completely forgot about that other solution you suggested. I went with ignoring the plugin execution for now. I might try that other workaround later. I had thought there might be value in opening it up again, due to the question about why it would fail on 3 modules, but not fail on the other 13, when they are all similarly situated using a path to the root of the multi-module build. For the 3 that are failing, they are not picking up the rootlocation property set by the build-helper-maven-plugin's rootlocation goal and giving the same error as above (the invalid path relative to the child module), but the other 13 seem to be picking it up the absolute path just fine, since they don't have the error.

This doesn't seem to be a problem with the build-helper-maven-plugin, so much as it has to do with some order of execution of the plugins in M2E, which I am not versed enough to know where to begin.

I will close the issue again. But, if you have any suggestions on why it might be failing for 3, but not the other 13, I'd be happy to read a response.

**Comment by laeubi** [comment]
It all depends on how you have configured it (e.g. what phase it uses compared to other plugins) and when/how you use that property (maven might interpolate that earlier as you want, or a plugin is caching the value or ...).

You can always open the Lifcycle Mapping View to see what phases are executed in what order by m2e
