### ISSUE TITLE
Lifecycle Mapping: Attached artifacts are not cleared completely between builds

### ISSUE THREAD

**Issue by pbull-oracle** [eclipse-m2e/m2e-core#137]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=562239

For JAR projects, I want the JAR to be installed to the local Maven repo during Eclipse builds.

To do that, I have altered the pom to set the m2e lifecycle mappings to execute jar:jar and install:install. A zip with a project is attached here: [project.zip](https://github.com/eclipse-m2e/m2e-core/files/6232139/project.zip). Import the project as a Maven project in your Eclipse workspace.

:heavy_check_mark: Passing scenario: Eclipse Restart
1. Restart Eclipse
2. "Build All" (no error)
3. **Restart Eclipse**
4. Change some Java code that will require a recompile
5. "Build All" (no error)
6. Check the local repo to see if the correct JAR was installed

:heavy_check_mark: Passing scenario: Maven Project Update
1. "Update Maven Project" > "OK"
2. "Build All" (no error)
3. **"Update Maven Project" > "OK"**
4. Change some Java code that will require a recompile
5. "Build All" (no error)
6. Check the local repo to see if the correct JAR was installed

:x: Failing scenario
1. "Update Maven Project" > "OK"
2. "Build All" (no error)
3. Change some Java code that will require a recompile
4. "Build All" (**error!**)
5. Check the local repo to see if the correct JAR was installed

```
You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. (org.apache.maven.plugins:maven-jar-plugin:3.1.1:jar:default-jar:package)

org.apache.maven.plugin.MojoExecutionException: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.
	at org.apache.maven.plugins.jar.AbstractJarMojo.execute(AbstractJarMojo.java:265)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1379)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1378)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:515)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:412)
	at org.eclipse.ui.actions.BuildAction$1.runInWorkspace(BuildAction.java:291)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by eeugeen** [comment]
Getting the same error when adding a lifecycle mapping to update JAR files in the described scenario.
