### ISSUE TITLE
Non existing but optional dependencies lead to resolving issue in target

### ISSUE THREAD

**Issue by glatuske** [eclipse-m2e/m2e-core#1402]
When a Maven dependency in target has non existing but optional dependencies this leads to an resolution error.
This behaviour exists since org.eclipse.m2e.pde.target 2.0.400.

To my understanding an optional dependency should must not be available in any attached Maven repository (including Maven Central).

In my case Saxon-HE has  dependency to axiom (which is not available as JAR).

```
<dependency>
	<groupId>net.sf.saxon</groupId>
	<artifactId>Saxon-HE</artifactId>
	<version>10.9</version>
	<type>jar</type>
</dependency>
```
```
<dependency>
      <groupId>org.apache.ws.commons.axiom</groupId>
      <artifactId>axiom</artifactId>
      <version>1.2.15</version>
      <optional>true</optional>
</dependency>
```

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="saxon-he">
	<locations>
		<location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>net.sf.saxon</groupId>
					<artifactId>Saxon-HE</artifactId>
					<version>10.9</version>
					<type>jar</type>
				</dependency>
			</dependencies>
		</location>
	</locations>
</target>
```

```
eclipse.buildId=4.27.0.20230309-1200
java.version=17.0.7
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.m2e.pde.target
Error
Tue May 30 10:39:26 CEST 2023
net.sf.saxon:Saxon-HE:jar:10.9 is not a bundle and cannot be automatically bundled as such  (Can't collect dependencies!)

org.eclipse.core.runtime.CoreException: Can't collect dependencies!
	at org.eclipse.m2e.pde.target.MavenTargetBundle.lambda$2(MavenTargetBundle.java:159)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.pde.target.MavenTargetBundle.getWrappedArtifact(MavenTargetBundle.java:136)
	at org.eclipse.m2e.pde.target.MavenTargetBundle.<init>(MavenTargetBundle.java:102)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.addBundleForArtifact(MavenTargetLocation.java:356)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveDependency(MavenTargetLocation.java:269)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveArtifacts(MavenTargetLocation.java:170)
	at org.eclipse.m2e.pde.target.MavenTargetLocation.resolveBundles(MavenTargetLocation.java:157)
	at org.eclipse.pde.internal.core.target.AbstractBundleContainer.resolve(AbstractBundleContainer.java:96)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:429)
	at org.eclipse.pde.internal.ui.editor.targetdefinition.TargetEditor$TargetChangedListener$1.run(TargetEditor.java:606)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.apache.ws.commons.axiom:axiom:jar:1.2.15 (absent): org.apache.ws.commons.axiom:axiom:jar:1.2.15 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:364)
	at org.eclipse.m2e.pde.target.shared.MavenBundleWrapper.getWrappedArtifact(MavenBundleWrapper.java:99)
	at org.eclipse.m2e.pde.target.MavenTargetBundle.lambda$2(MavenTargetBundle.java:140)
	... 13 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.apache.ws.commons.axiom:axiom:jar:1.2.15 (absent): org.apache.ws.commons.axiom:axiom:jar:1.2.15 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:456)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:352)
	... 15 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: org.apache.ws.commons.axiom:axiom:jar:1.2.15 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:204)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:180)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:565)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:504)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:433)
	... 17 more
```

**Comment by laeubi** [comment]
> To my understanding an optional dependency should must not be available in any attached Maven repository (including Maven Central).

Optional only means it is not required to be included transitive, normally you can exclude unwanted artifacts:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="saxon-he">
	<locations>
		<location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>net.sf.saxon</groupId>
					<artifactId>Saxon-HE</artifactId>
					<version>10.9</version>
					<type>jar</type>
				</dependency>
			</dependencies>
                        <exclude>org.apache.ws.commons.axiom:axiom:1.2.15</exclude>
		</location>
	</locations>
</target>
```

but this won't help her as it happens in the wrapping bundle phase.

Do you think you can add this as an junit test to the existing testsuite as part of a PR?

**Comment by laeubi** [comment]
I think `OSGiMetadataGenerationTest` is a good place as it seems to happen there.

**Comment by glatuske** [comment]
I have create additional test cases: https://github.com/glatuske/m2e-core/blob/missing-optional-dependencies/org.eclipse.m2e.pde.target.tests/src/org/eclipse/m2e/pde/target/tests/OSGiMetadataGenerationTest.java

Even with <exclude>org.apache.ws.commons.axiom:axiom:1.2.15</exclude> the resolution still fails.

**Comment by laeubi** [comment]
@glatuske I played around with this a bit but it is quite tricky, even if I was able to make it work to detect it as missing, this currently bubbles up because we try to intercept all failures, so the question is, should we allow that errors in dependencies are ignored?!? because this can then lead to faulty manifests generated, on the other hand until now the dependecies are ignored all together so this is the maybe better than nothing...

**Comment by laeubi** [comment]
It seems PDE currently do not support reporting warnings quite good, I'll for now disable the warning code:
- https://github.com/eclipse-pde/eclipse.pde/issues/656
