### ISSUE TITLE
Regression in launching without a project location

### ISSUE THREAD

**Issue by kjsmita6** [eclipse-m2e/m2e-core#1427]
We have code that runs `archetype:crawl` which doesn't require a project, and we set the ATTR_POM_DIR to

```java
workingCopy.setAttribute(MavenLaunchConstants.ATTR_POM_DIR, "${workspace_loc}");
```
This has been this way for probably 5 years or more with no issues. Upon running this launch code in the latest Eclipse 4.28, the following error appears:
```
java.lang.IllegalArgumentException: Path must include project and resource name: /pom.xml
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2164)
	at org.eclipse.core.internal.resources.Container.getFile(Container.java:196)
	at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.readEnforcedJavaVersion(MavenLaunchDelegate.java:248)
	at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.getVMInstall(MavenLaunchDelegate.java:224)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getBootpathExt(AbstractJavaLaunchConfigurationDelegate.java:363)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getVMSpecificAttributesMap(AbstractJavaLaunchConfigurationDelegate.java:679)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.getVMRunnerConfiguration(JavaLaunchDelegate.java:92)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:160)
	at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.launch(MavenLaunchDelegate.java:133)
```

Even if you launch using the UI, setting "project location" to `${workspace_loc}`, the launch dialog does not tell you this isn't allowed and you are able to launch, getting the same error in the Error Log immediately. You can't even properly edit the configuration in this state, every action you will get a popup error message.

![image](https://github.com/eclipse-m2e/m2e-core/assets/9405706/f98c738b-c26c-4d6b-87a7-3d7ab43bcb15)

This is a regression caused by https://github.com/eclipse-m2e/m2e-core/commit/32dc6407c919bb8eb8217df4a3ccddff18ab1ed4, and m2e no longer supports running such goals without a project (even though Maven does).

Please provide a temporary workaround in the meantime.

## System Information

Eclipse Platform
Version: 2023-06 (4.28)
Build id: I20230605-0440

Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.3.0.20230523-2033	org.eclipse.m2e.feature
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.2.100.20230523-1752	org.eclipse.m2e.pde.feature

**Comment by HannesWell** [comment]
Thanks @kwin for providing the fix.
@kjsmita6 you can try the latest snapshot that includes it when the current master branch build succeeds from:
https://download.eclipse.org/technology/m2e/snapshots/latest/
