### ISSUE TITLE
NoSuchMethodError: org.eclipse.lsp4e.LanguageServiceAccessor.getActiveLanguageServers

### ISSUE THREAD

**Issue by lrozenblyum** [eclipse-m2e/m2e-core#1473]
While trying the nightly m2e-core 2.4.100.20230705-1302 (in Eclipse 2023-06) due to https://github.com/eclipse-m2e/m2e-core/issues/1414 I'm facing multiple issues.

Here is one of them: when editing pom.xml an error is issued

```
!ENTRY org.eclipse.equinox.preferences 4 2 2023-07-11 10:57:24.502
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".
!STACK 0
java.lang.NoSuchMethodError: 'java.util.List org.eclipse.lsp4e.LanguageServiceAccessor.getActiveLanguageServers(java.util.function.Predicate)'
	at org.eclipse.m2e.editor.lemminx.MavenRuntimeClasspathProvider.lambda$0(MavenRuntimeClasspathProvider.java:54)
	at org.eclipse.m2e.core.internal.preferences.MavenConfigurationImpl.preferenceChange(MavenConfigurationImpl.java:210)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:841)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:844)
	at org.eclipse.core.internal.preferences.EclipsePreferences.putBoolean(EclipsePreferences.java:869)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:624)
	at org.eclipse.jface.preference.BooleanFieldEditor.doStore(BooleanFieldEditor.java:169)
	at org.eclipse.jface.preference.FieldEditor.store(FieldEditor.java:681)
	at org.eclipse.jface.preference.FieldEditorPreferencePage.performOk(FieldEditorPreferencePage.java:348)
	at org.eclipse.m2e.core.ui.internal.preferences.MavenPreferencePage.performOk(MavenPreferencePage.java:151)
	at org.eclipse.jface.preference.PreferencePage.performApply(PreferencePage.java:457)
	at org.eclipse.m2e.core.ui.internal.preferences.MavenPreferencePage.performApply(MavenPreferencePage.java:145)
	at org.eclipse.jface.preference.PreferencePage.lambda$1(PreferencePage.java:289)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by mickaelistria** [comment]
Can you please tell the exact version of org.eclipse.m2e.editor.lemminx and org.eclipse.lsp4e you're running (from Help > About > Intallation Details > Plugins)?

**Comment by lrozenblyum** [comment]
@mickaelistria 
org.eclipse.m2e.editor.lemminx: 2.0.3.20230520-0934
org.eclipse.lsp4e: 0.21.0.v20230517-2120

Is it possible I'm using incompatible lemminx and have to install it also from the nightly builds?

**Comment by mickaelistria** [comment]
You'll need https://github.com/eclipse-m2e/m2e-core/commit/a53bf967a299984f91fd1ac4c3bf86bafe03e6e0 which is only present in newer versions of org.eclipse.m2e.editor.lemminx. Please make sure you update to latest version of this plugin.

**Comment by lrozenblyum** [comment]
Thanks @mickaelistria 
After installing `org.eclipse.m2e.editor.lemminx` 2.0.4.20230630-2007
the problem is gone.

Closing this issue and will try hard to create minimal test cases for other problems (somehow could be related to test-jar resolution changes which cause compilation errors now).
