### ISSUE TITLE
NPE while opening pom.xml in flatpak

### ISSUE THREAD

**Issue by vkadlcik** [eclipse-m2e/m2e-core#149]
I run the flatpak variant of Eclipse and have m2e present. When I'm opening pom.xml then a NPE appears in the workspace log:

```
!ENTRY org.eclipse.wildwebdeveloper.xml 4 0 2021-04-01 09:50:34.955
!MESSAGE 
!STACK 0
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1019)
        at java.base/java.util.Map.of(Map.java:1327)
        at org.eclipse.m2e.editor.lemminx.InitializationOptionsProvider.toLemMinXOptions(InitializationOptionsProvider.java:26)
        at org.eclipse.m2e.editor.lemminx.InitializationOptionsProvider.get(InitializationOptionsProvider.java:22)
        at org.eclipse.m2e.editor.lemminx.InitializationOptionsProvider.get(InitializationOptionsProvider.java:1)
        at org.eclipse.wildwebdeveloper.xml.internal.XMLExtensionRegistry.getInitiatizationOptions(XMLExtensionRegistry.java:135)
        at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.getInitializationOptions(XMLLanguageServer.java:158)
        at org.eclipse.lsp4e.LanguageServerWrapper.lambda$5(LanguageServerWrapper.java:352)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

My system is Fedora 33 (x86_64) with the following flatpaks:
```
# flatpak list
Name                                             Application ID                                Version           Branch           Installation
Slack                                            com.slack.Slack                               4.14.0            stable           system
Eclipse IDE for Java Developers                  org.eclipse.Java                              4.19              stable           system
Freedesktop Platform                             org.freedesktop.Platform                      20.08.6           20.08            system
default                                          org.freedesktop.Platform.GL.default                             20.08            system
openh264                                         org.freedesktop.Platform.openh264             2.1.0             2.0              system
GNOME Application Platform version 40            org.gnome.Platform                                              40               system
```

I installed m2e using CLI:
```
flatpak run org.eclipse.Java -noSplash -application org.eclipse.equinox.p2.director -repository http://download.eclipse.org/releases/2021-03 -i org.eclipse.m2e.feature.feature.group
```
The result is Eclipse 4.19 with org.eclipse.m2e.feature 1.17.2.20210219-1922.

Steps to reproduce the problem:

- File > New > Project... > Maven > Maven Project > Next>
- In the New Maven Project dialog window:
  - Enable "Create a simple project (skip archetype selection)"
  - Next>
  - Artifact:
    - Group Id: org.example.vk
    - Artifact Id: org.example.vk.p1
    - Name: org.example.vk.p1
  - Finish
- In Package Explorer, find and double-click pom.xml
- In CLI, look into the workspace log (_workspace_/.metadata/.log)

**Comment by vkadlcik** [comment]
If it's more about flatpak than m2e, let's move this to https://github.com/flathub/org.eclipse.Java

**Comment by akurtakov** [comment]
It's a good place for that bug. @mickaelistria would you please investigate whether you can reproduce and fix.

**Comment by mickaelistria** [comment]
The root cause is that m2e settings files are not found on Flatpak because Maven is not installed. It shouldn't be a cause of issues though.
Patch was merged as https://github.com/eclipse-m2e/m2e-core/commit/77d5d177d168d3eded2ee837771cb36bd51911c0 ,
@vkladich can you please try installing snapshots from https://download.eclipse.org/technology/m2e/snapshots/1.18.0 into Flatpak and see whether this works for you?

**Comment by vkadlcik** [comment]
@mickaelistria Yes, works fine, I'm closing this. Thanks!

Note on verification: The m2e snapshot can't be installed into the org.eclipse.Java flatpak because of a version conflict. However it installs fine into the latest nightly of http://eclipse.matbooth.co.uk/flatpak/nightly/. For the record, I used build I20210405-1800 of the org.eclipse.Sdk flatpak and 1.18.0.20210402-1458 of m2e.
