### ISSUE TITLE
Disable error logging when m2e tries to obtain source bundles but fails

### ISSUE THREAD

**Issue by merks** [eclipse-m2e/m2e-core#1569]
I have all these errors in my log:

![image](https://github.com/eclipse-m2e/m2e-core/assets/208716/ee048276-44bc-4997-b136-713d92b7b75d)

E.g.,
```
org.eclipse.core.runtime.CoreException: Could not resolve artifact org.eclipse.orbit.bundles:org.apache.httpcomponents.httpcore:jar:sources:4.4.16-SNAPSHOT
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$6(MavenImpl.java:584)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:553)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:538)
	at org.eclipse.m2e.core.internal.MavenArtifactIdentifier.resolveSourceLocation(MavenArtifactIdentifier.java:193)
	at org.eclipse.m2e.pde.target.MavenPluginSourcePathLocator.locateSource(MavenPluginSourcePathLocator.java:56)
	at org.eclipse.pde.internal.core.SourceLocationManager.lambda$0(SourceLocationManager.java:325)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.pde.internal.core.SourceLocationManager.searchExtensionLocations(SourceLocationManager.java:329)
	at org.eclipse.pde.internal.core.SourceLocationManager.findSourcePath(SourceLocationManager.java:88)
	at org.eclipse.pde.internal.core.ClasspathUtilCore.getSourceAnnotation(ClasspathUtilCore.java:193)
	at org.eclipse.pde.internal.core.PDEClasspathContainer.addExternalPlugin(PDEClasspathContainer.java:82)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addPlugin(RequiredPluginsClasspathContainer.java:383)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:328)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:340)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.addDependency(RequiredPluginsClasspathContainer.java:309)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.computePluginEntriesByModel(RequiredPluginsClasspathContainer.java:198)
	at org.eclipse.pde.internal.core.RequiredPluginsClasspathContainer.getClasspathEntries(RequiredPluginsClasspathContainer.java:123)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3278)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:3436)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2521)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.getRootInfos(DeltaProcessingState.java:335)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.initializeRoots(DeltaProcessingState.java:283)
	at org.eclipse.jdt.internal.core.DeltaProcessor.processResourceDelta(DeltaProcessor.java:1955)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2157)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:501)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:321)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:311)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:174)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:458)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1586)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1616)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1127)
	at org.eclipse.core.internal.resources.Project.open(Project.java:1183)
	at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:297)
	at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
	at org.eclipse.oomph.targlets.core.WorkspaceIUInfo.importIntoWorkspace(WorkspaceIUInfo.java:108)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$3.run(WorkspaceIUImporter.java:176)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2473)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:147)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$2.run(WorkspaceIUImporter.java:117)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:75)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$ImportProjectsJob.run(WorkspaceIUImporter.java:216)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Missing org.eclipse.orbit.bundles:org.apache.httpcomponents.httpcore:jar:sources:4.4.16-SNAPSHOT
```
I don't really want those filling up my log and I didn't ask for m2e find sources for me.  I don't even have m2e natures on my projects.

I'd like a way to disable the logging because such errors suggests something is quite seriously wrong...

**Comment by HannesWell** [comment]
> I don't really want those filling up my log and I didn't ask for m2e find sources for me. I don't even have m2e natures on my projects.

Would warnings or info level entries be ok? Because if one wants the sources but it fails some kind of notification might be of interest. On the other hand adding yet another preference for such a specific use-case seems a bit too much.
