### ISSUE TITLE
Try to rename artifactId in eclipse-SDK-4.30M1-win32-x86_64.zip

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-m2e/m2e-core#1591]
I just installed eclipse-SDK-4.30M1-win32-x86_64.zip.
I added M2E - Maven Integration for Eclipse.
This is my installed software:

![Screenshot 2023-10-31 095056](https://github.com/eclipse-m2e/m2e-core/assets/48506054/08f38cc2-6e19-4903-840d-394199b6f15f)

I am trying to change the artifactId:
 
![Screenshot 2023-10-31 095431](https://github.com/eclipse-m2e/m2e-core/assets/48506054/1085be87-2f36-44bb-bff3-1dc6b20d5151)

I am getting:
java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/corext/refactoring/rename/RenameJavaProjectProcessor
	at org.eclipse.m2e.refactoring.rename.MavenRenameWizard.<init>(MavenRenameWizard.java:31)
	at org.eclipse.m2e.refactoring.rename.RenameArtifactHandler.rename(RenameArtifactHandler.java:65)
	at org.eclipse.m2e.refactoring.rename.RenameArtifactHandler.execute(RenameArtifactHandler.java:52)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:302)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:236)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jdt.internal.corext.refactoring.rename.RenameJavaProjectProcessor cannot be found by org.eclipse.m2e.refactoring_2.0.301.20230809-1423
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 42 more

Since this is a custom-built setup, I might be missing something.
 
Any ideas ?

**Comment by eitan-rosenberg** [comment]
Update:
Actually, I think I see the class org.eclipse.jdt.internal.corext.refactoring.rename.RenameJavaProjectProcessor 
undrer eclipse\plugins in 
org.eclipse.jdt.core.manipulation.source_1.20.0.v20230927-1806.jar

**Comment by fbricon** [comment]
The file was moved in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/810/files#diff-a0b1ead407849786938df22e325589a9206788923a027edd830c8670920013e1

m2e needs to update its dependency to the bundle providing it

**Comment by HannesWell** [comment]
> I hope that it will be fixed soon....

If you are a interested in having this fixed sooner, a PR to fix this would be more than welcome. :)

**Comment by eitan-rosenberg** [comment]
> > I hope that it will be fixed soon....
> 
> If you are a interested in having this fixed sooner, a PR to fix this would be more than welcome. :)

I have to admit that I am not qualified to do that.
You are dealing here with an 72 retired programmer...
I will wait.

**Comment by HannesWell** [comment]
> > If you are a interested in having this fixed sooner, a PR to fix this would be more than welcome. :)
> 
> I have to admit that I am not qualified to do that.
> You are dealing here with an 72 retired programmer...
> I will wait.

No Problem, this is now fixed with #1595.

You can try it out in about half an hour using the snapshots.

**Comment by eitan-rosenberg** [comment]
Thanks.

It is working just fine now.
