### ISSUE TITLE
"MESSAGE UI freeze" + stacktrace logged while opening the New Maven Project dialog

### ISSUE THREAD

**Issue by vkadlcik** [eclipse-m2e/m2e-core#160]
I'm looking at the latest Eclipse SDK + m2e snapshots. While opening the New Maven Project dialog, the following gets logged:
```
!ENTRY org.eclipse.ui.monitoring 2 0 2021-04-06 14:36:05.693
!MESSAGE UI freeze of 0.62s at 14:36:05.065
!SUBENTRY 1 org.eclipse.ui.monitoring 1 0 2021-04-06 14:36:05.694
!MESSAGE Sample at 14:36:05.399 (+0.334s)
Thread 'main' tid=1 (RUNNABLE)
!STACK 0
Stack Trace
	at java.base@11.0.10/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base@11.0.10/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
	at java.base@11.0.10/java.lang.Class.getDeclaredFields(Class.java:2248)
	at com.google.inject.spi.InjectionPoint.getDeclaredFields(InjectionPoint.java:760)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:670)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:378)
	at org.eclipse.sisu.wire.DependencyAnalyzer.analyzeImplementation(DependencyAnalyzer.java:224)
	at org.eclipse.sisu.wire.DependencyAnalyzer.visit(DependencyAnalyzer.java:156)
	at org.eclipse.sisu.wire.DependencyAnalyzer.visit(DependencyAnalyzer.java:1)
	at com.google.inject.internal.ProviderInstanceBindingImpl.acceptTargetVisitor(ProviderInstanceBindingImpl.java:70)
	at org.eclipse.sisu.wire.ElementAnalyzer.visit(ElementAnalyzer.java:177)
	at org.eclipse.sisu.wire.ElementAnalyzer.visit(ElementAnalyzer.java:1)
	at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:99)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:77)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
	at org.eclipse.m2e.core.internal.MavenPluginActivator.newPlexusContainer(MavenPluginActivator.java:278)
	at org.eclipse.m2e.core.internal.MavenPluginActivator.getArchetypeManager(MavenPluginActivator.java:396)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizardArchetypePage.createViewer(MavenProjectWizardArchetypePage.java:283)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizardArchetypePage.createControl(MavenProjectWizardArchetypePage.java:196)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizard.createPageControls(MavenProjectWizard.java:134)
    ...
```

My configuration:

- Fedora 33 x86_64
- java-11-openjdk-11.0.10.0.9-0.fc33.x86_64
- Eclipse:
  - SDK: eclipse-platform-I20210204-2320-linux-gtk-x86_64.tar.gz
  - m2e: org.eclipse.m2e.feature 1.18.0.20210402-1458 of http://download.eclipse.org/technology/m2e/snapshots/1.18.0/latest

Steps to reproduce:

1. File > New > Project... > Maven > Maven Project > Next>
2. When the New Maven Project dialog appears look at the workspace log

**Comment by vkadlcik** [comment]
Full workspace log: [workspace.log](https://github.com/eclipse-m2e/m2e-core/files/6265065/workspace.log)
Eclipse configuration taken from Help > About: [configuration.txt](https://github.com/eclipse-m2e/m2e-core/files/6265067/configuration.txt)
Eclipse setup script (destructive!): [setup.sh.txt](https://github.com/eclipse-m2e/m2e-core/files/6265082/setup.sh.txt)

**Comment by mickaelistria** [comment]
The issue is that `MavenPluginActivator.newPlexusContainer()` can be a long running operation, and all its callers as well; but it's used synchronously in the wizard, causing a UI Freeze which itself is logged.
One solution would be that `MavenProjectWizardArchetypePage` just triggers a job or a future to invoke `getArchetypeManager()` and reacts to it by making the necessary updates in UI asynchronously.
Realistically, it's not a big enough issue and the fix is not trivial enough to hope for high priority fix on this one.
