### ISSUE TITLE
NPE when updating Maven project

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#1605]
The following NPE is thrown when updating a Maven project

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.project.IMavenProjectFacade.getArtifactKey()" because "facade" is null
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.updateMavenProject(MavenProjectCache.java:119)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:476)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:367)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:319)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:388)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1097)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This happens with 2023-09 with m2e 2.4.100.

**Comment by kwin** [comment]
This can only happen if `newFacade` is set to `null` in https://github.com/eclipse-m2e/m2e-core/blob/0d7583dc4e451a487230d2b11d29355eddb6335a/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java#L467 (either due to the returned map being empty or at least not containing an entry for the POM)

**Comment by HannesWell** [comment]
Can you somehow reproduce this in a debugged Eclipse?

**Comment by kwin** [comment]
Unfortunately I cannot reproduce. However error handling should be improved so that a more meaningful exception is thrown.

**Comment by HannesWell** [comment]
> However error handling should be improved so that a more meaningful exception is thrown.

Sounds good. Can you provide a PR?

**Comment by dmatej** [comment]
Seen today on latest Eclipse IDE by several plugins (based on stacktrace):

```
SESSION 2024-07-04 20:06:44.743 -----------------------------------------------
eclipse.buildId=4.32.0.20240606-1231
java.version=21.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=cs_CZ
Framework arguments:  -cssTheme none -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -cssTheme none -product org.eclipse.epp.package.jee.product

This is a continuation of log file /media/data-samsung/data/dmatej/work/workspaces/glassfish/.metadata/.bak_0.log
Created Time: 2024-07-04 21:49:18.949

!ENTRY org.eclipse.core.resources 4 2 2024-07-04 21:49:18.949
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.project.IMavenProjectFacade.getArtifactKey()" because "facade" is null
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.invalidateProjectFacade(MavenProjectCache.java:88)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.updateMavenProject(MavenProjectCache.java:116)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:479)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:370)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:322)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:146)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:84)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rombert** [comment]
Still an issue 

eclipse.buildId=4.35.0.20250306-0811
    M2E - Maven Integration for Eclipse	2.8.0.20250224-0720	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.project.IMavenProjectFacade.getArtifactKey()" because "facade" is null
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.invalidateProjectFacade(MavenProjectCache.java:88)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectCache.updateMavenProject(MavenProjectCache.java:116)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:479)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:370)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:322)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:146)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:84)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:458)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:278)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1077)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rombert** [comment]
@kwin, with the following changes

```diff
diff --git a/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java b/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java
index bad2ec7a..888af465 100644
--- a/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java
+++ b/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java
@@ -467,7 +467,12 @@ public class ProjectRegistryManager implements ISaveParticipant {
             MavenProject mavenProject = getMavenProject(newFacade);
             if(!allProcessedPoms.contains(newFacade.getPom())) {
               // facade from workspace state that has not been refreshed yet
-              newFacade = readMavenProjectFacades(Collections.singletonList(pom), newState, context, monitor).get(pom);
+              Map<IFile, MavenProjectFacade> projectFacades = readMavenProjectFacades(Collections.singletonList(pom), newState, context, monitor);
+              newFacade = projectFacades.get(pom);
+              if ( newFacade == null ) {
+                throw new CoreException(new Status(IStatus.ERROR, IMavenConstants.PLUGIN_ID,
+                    "Failed reading project facade for pom " + pom + ". No match found in " + projectFacades));
+              }
             } else {
               // recreate facade instance to trigger project changed event
               // this is only necessary for facades that are refreshed because their dependencies changed
```

I get the following error

```
Failed reading project facade for pom L/cq-quickstart/pom.xml. No match found in {}
```

FWIW I was updating a different project at the time.

Any ideas for further debugging?

**Comment by rombert** [comment]
I suspect the flow is the following:

- IMavenToolbox#readMavenProjects is invoked - https://github.com/eclipse-m2e/m2e-core/blob/4cccdd49773cb81064661c42a57b0c582325d9f6/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java#L768-L769
- Building the project fails, even at the minimal configuration level since the parent pom cannot be resolved. The value  - MavenExecutionResult - does not have a MavenProject : https://github.com/eclipse-m2e/m2e-core/blob/4cccdd49773cb81064661c42a57b0c582325d9f6/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/IMavenToolbox.java#L123-L131
- The following code is not executed and the facadeMap is not populated - https://github.com/eclipse-m2e/m2e-core/blob/4cccdd49773cb81064661c42a57b0c582325d9f6/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/ProjectRegistryManager.java#L782-L787

If that is the case this is a rare but expected condition and the code must be ready to handle a null `newFacade` and (probably) continue gracefully.

My current thinking is that the condition should be ignored since if the project does not build the error should already be visible via markers so it would be ok to just continue processing.

Thoughts?

**Comment by laeubi** [comment]
@rombert please provide a PR with your proposed fix. At best this would be covered by a test here:

https://github.com/eclipse-m2e/m2e-core/tree/main/org.eclipse.m2e.core.tests

**Comment by rombert** [comment]
@laeubi - I created a draft PR with my fix at https://github.com/eclipse-m2e/m2e-core/pull/1971 . The tests will take a bit of time as I don't have any experience with m2e.

But this will allow others  to validate the fix and maybe point out any problems with it in the meantime.

**Comment by marco-brandizi** [comment]
Hi all, maybe my experience will be useful: I've just struggled for hours to build a [project of mine](https://github.com/marco-brandizi/jutils), and eventually, I discovered (from the Error Log View) that I had parent POMs not in the project, but in a series of other projects.

The strange thing is that I was building only the project at issue and this doesn't depend at all on the others. My understanding is that Eclipse (or m2e) causes those other rebuilds (or checks) anyway.
