### ISSUE TITLE
"java.io.IOException: No space left on device" when downloading Maven repository index in flatpak

### ISSUE THREAD

**Issue by vkadlcik** [eclipse-m2e/m2e-core#162]
I use the flatpak variant of Eclipse and have m2e present. I enabled m2e's "Download repository index updates on startup", restarted Eclipse, the updates started to download but didn't finish. Instead, this appeared in the workspace log:
```!MESSAGE Unable to update index for central|https://repo.maven.apache.org/maven2
!STACK 0
java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:285)
	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
	at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
	at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
	at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:278)
	at java.base/java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:123)
	at org.apache.lucene.store.OutputStreamIndexOutput.writeBytes(OutputStreamIndexOutput.java:53)
	at org.apache.lucene.store.DataOutput.copyBytes(DataOutput.java:278)
	at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:91)
	at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4670)
	at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:492)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:459)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:503)
	at org.apache.lucene.index.DocumentsWriter.postUpdate(DocumentsWriter.java:377)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:467)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
	at org.apache.maven.index.updater.IndexDataReader.readIndex(IndexDataReader.java:101)
	at org.apache.maven.index.updater.DefaultIndexUpdater.unpackIndexData(DefaultIndexUpdater.java:387)
	at org.apache.maven.index.updater.DefaultIndexUpdater.loadIndexDirectory(DefaultIndexUpdater.java:202)
	at org.apache.maven.index.updater.DefaultIndexUpdater.access$300(DefaultIndexUpdater.java:76)
	at org.apache.maven.index.updater.DefaultIndexUpdater$LuceneIndexAdaptor.setIndexFile(DefaultIndexUpdater.java:518)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:736)
	at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:161)
	at org.eclipse.m2e.core.internal.index.nexus.NexusIndexManager.updateRemoteIndex(NexusIndexManager.java:1139)
	at org.eclipse.m2e.core.internal.index.nexus.NexusIndexManager.updateIndex(NexusIndexManager.java:1083)
	at org.eclipse.m2e.core.internal.index.nexus.NexusIndexManager.lambda$0(NexusIndexManager.java:657)
	at org.eclipse.m2e.core.internal.index.nexus.IndexUpdaterJob.run(IndexUpdaterJob.java:74)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Suppressed: java.io.IOException: No space left on device
		at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
		at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
		at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
		at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
		at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:285)
		at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
		at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
		at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
		at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:278)
		at java.base/java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
		at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
		at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
		at org.apache.lucene.store.OutputStreamIndexOutput.close(OutputStreamIndexOutput.java:68)
		at org.apache.lucene.codecs.lucene50.Lucene50CompoundFormat.write(Lucene50CompoundFormat.java:105)
		... 20 more
		Suppressed: java.io.IOException: No space left on device
			at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
			at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
			at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
			at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
			at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:285)
			at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
			at java.base/java.nio.channels.Channels.writeFully(Channels.java:97)
			at java.base/java.nio.channels.Channels$1.write(Channels.java:172)
			at org.apache.lucene.store.FSDirectory$FSIndexOutput$1.write(FSDirectory.java:278)
			at java.base/java.util.zip.CheckedOutputStream.write(CheckedOutputStream.java:73)
			at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
			at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
			at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
			at org.apache.lucene.store.OutputStreamIndexOutput.close(OutputStreamIndexOutput.java:70)
			... 21 more
```
What's strange is that I was monitoring the disk usage for the whole time (all the filesystems) but I didn't see any shortage. Namely, /tmp, /var/tmp, /home and /run/user/_UID_ looked sufficient and didn't show any significant usage growth. So I don't know what filesystem I need to expand, if any at all.

My system is Fedora 34 (x86_64) with the following flatpaks:
```
# flatpak list
Name                                             Application ID                            Version       Branch       Origin                Installation
Eclipse IDE for Java Developers                  org.eclipse.Java                          4.19          stable       flathub               system
default                                          org.freedesktop.Platform.GL.default                     20.08        flathub               system
openh264                                         org.freedesktop.Platform.openh264         2.1.0         2.0          flathub               system
GNOME Application Platform version 40            org.gnome.Platform                                      40           flathub               system
GNOME Software Development Kit version 40        org.gnome.Sdk                                           40           flathub               system
```
I installed m2e using CLI:
```
flatpak run org.eclipse.Java -noSplash -application org.eclipse.equinox.p2.director -repository http://download.eclipse.org/releases/2021-03 -i org.eclipse.m2e.feature.feature.group
```
In essence, it's Eclipse 4.19 with m2e 1.17.2. (But I've tried the latest nightlies of the Eclipse flatpak with m2e 1.18 with the same result.)

Steps to reproduce on a clean Eclipse installation and with no ~/.m2:
- In Window > Preferences > Maven, enable "Download repository index updates on startup", then click "Apply and Close"
- Create a Maven project ("Create a simple project (skip archetype selection)")
- Restart Eclipse
- Open the Progress view to see the download task running in background
- In a terminal window, follow the workspace log
- In another terminal window, follow disk usage (e.g. periodical "df -h")

It's quite possible that there indeed is a disk space problem on my system but the logged exception doesn't give me much information. On the other hand, maybe there's a problem in Eclipse+flatpak because my (naive?) monitoring didn't see any shortage.

FWIW, I've found a workaround: ```flatpak run --filesystem=/tmp org.eclipse.Java ...``` uses /tmp for temporary files. The download task needs something like 6.7 gigabytes.

**Comment by vkadlcik** [comment]
Full workspace log: [workspace.log](https://github.com/eclipse-m2e/m2e-core/files/6272473/workspace.log)
Eclipse configuration from Help > About: [configuration.txt](https://github.com/eclipse-m2e/m2e-core/files/6272474/configuration.txt)

**Comment by laeubi** [comment]
Repository index is no longer used in m2e
