### ISSUE TITLE
Guide: Contributing to Eclipse m2eclipse incomplete.

### ISSUE THREAD

**Issue by G-Ork** [eclipse-m2e/m2e-core#1636]
I try to setup an development environment following the [guide](https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md) using the eclipse installer. After the provision i have:

Version: 2023-12 (4.30.0)
Build id: 20231201-2043

and m2e-core and m2e-core-tests.

1. I get errors that do not resolve after IDE restart like stated in [Bullet 10 of developer-resources](https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md#-developer-resources). 

2. To which location should the [test-environment](https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md#%EF%B8%8F-setting-up-the-rcptt-test-environment) be exported? 
The wizzard warns: _Destination directory must be specified._

3. If i just export in the current directory i get th following error.
<img width="492" alt="grafik" src="https://github.com/eclipse-m2e/m2e-core/assets/28452503/c1f7633d-ce96-42ff-b64a-36ded3ff99e5"> I guess some magic is missing.

`Baseline problems found! Project version: 2.0.5.20240102-1111, baseline version: 2.0.5.20231113-2319, suggested version: 2.0.6 (org.eclipse.tycho:tycho-baseline-plugin:4.0.4:verify:baseline-check:package)	org.eclipse.m2e.editor.lemminx		line 0	Maven Build Participant Problem
Failed to execute mojo org.eclipse.rcptt:rcptt-maven-plugin:2.5.4:execute {execution: default-execute} (org.eclipse.rcptt:rcptt-maven-plugin:2.5.4:execute:default-execute:compile)

org.eclipse.core.runtime.CoreException: Failed to execute mojo org.eclipse.rcptt:rcptt-maven-plugin:2.5.4:execute {execution: default-execute}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$2(MavenBuilderImpl.java:154)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:134)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot execute RCPTT tests. Something is corrupted during prepare goal. Is lifecycle have been modified?
	at org.eclipse.rcptt.maven.ExecuteMojo.validatePreparation(ExecuteMojo.java:350)
	at org.eclipse.rcptt.maven.ExecuteMojo.execute(ExecuteMojo.java:113)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
	pom.xml	/org.eclipse.m2e.rcptt.tests	line 25	Maven Build Problem
Failed to execute mojo org.eclipse.rcptt:rcptt-maven-plugin:2.5.4:resources {execution: default-resources} (org.eclipse.rcptt:rcptt-maven-plugin:2.5.4:resources:default-resources:generate-resources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo org.eclipse.rcptt:rcptt-maven-plugin:2.5.4:resources {execution: default-resources}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$2(MavenBuilderImpl.java:154)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:134)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.MojoFailureException: The explicit location /opt/java/eclipse/eclipse-2023-12-m2e/git/m2e-core/org.eclipse.m2e.rcptt.tests/../products/m2e-ide/target/products/m2e-ide-linux.gtk.x86_64.tar.gz is not valid
	at org.eclipse.rcptt.maven.util.CoordResolver.resolveFile(CoordResolver.java:207)
	at org.eclipse.rcptt.maven.util.CoordResolver.resolve(CoordResolver.java:84)
	at org.eclipse.rcptt.maven.PrepareMojo.unpackApps(PrepareMojo.java:117)
	at org.eclipse.rcptt.maven.PrepareMojo.execute(PrepareMojo.java:42)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
	pom.xml	/org.eclipse.m2e.rcptt.tests	line 25	Maven Build Problem
`

**Comment by mickaelistria** [comment]
Have you tried closing the org.eclipse.m2e.rcptt.tests project?

**Comment by G-Ork** [comment]
I've tried but it does not help. I reverted all changed .settings files and bring the working copy back to checked in state and build from shell with maven outside eclipse. This works for me. 

I will repeat this to be sure tomorrow.
