### ISSUE TITLE
EclipseLogger can throw NPE if throwable is null

### ISSUE THREAD

**Issue by szarnekow** [eclipse-m2e/m2e-core#1652]
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Throwable.getMessage()" because "t" is null
	at org.eclipse.m2e.core.internal.embedder.EclipseLogger.warn(EclipseLogger.java:71)
	at org.apache.maven.monitor.logging.DefaultLog.warn(DefaultLog.java:72)
[snip]
```

I think the logger should be very robust and not fail on absent throwables.

**Comment by laeubi** [comment]
@szarnekow do you like to propose a PR?
