### ISSUE TITLE
java.nio.file.InvalidPathException if settings.xml localRepository is absolute

### ISSUE THREAD

**Issue by ahoehma** [eclipse-m2e/m2e-core#1695]
Since I updated to latest m2e my project is broken.

After the error occurred I tried to cleanup my project and re-import everything into eclipse but then I got for each module the same error:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 44: D:\Dev\git\coc\spice-configuration-cluster\D:\Dev\ApacheMaven\repository\co\leantechniques\maven-buildtime-extension\3.0.5\maven-buildtime-extension-3.0.5.pom.lastUpdated
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.io.File.toPath(File.java:2401)
	at org.eclipse.aether.internal.impl.DefaultTrackingFileManager.read(DefaultTrackingFileManager.java:56)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.read(DefaultUpdateCheckManager.java:461)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:156)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:586)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:525)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:234)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
	at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:179)
	at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:306)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:212)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveCoreExtension(DefaultPluginDependenciesResolver.java:155)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveExtension(BootstrapCoreExtensionManager.java:174)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveCoreExtensions(BootstrapCoreExtensionManager.java:115)
	at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.loadCoreExtensions(BootstrapCoreExtensionManager.java:99)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.loadCoreExtensions(PlexusContainerManager.java:357)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.newPlexusContainer(PlexusContainerManager.java:222)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.aquire(PlexusContainerManager.java:176)
	at org.eclipse.m2e.core.internal.embedder.PlexusContainerManager.getComponentLookup(PlexusContainerManager.java:204)
	at org.eclipse.m2e.core.embedder.MavenModelManager.readMavenModel(MavenModelManager.java:118)
	at org.eclipse.m2e.core.project.LocalProjectScanner.readMavenProjectInfo(LocalProjectScanner.java:125)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:94)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:110)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:110)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:110)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:110)
	at org.eclipse.m2e.core.project.LocalProjectScanner.scanFolder(LocalProjectScanner.java:110)
	at org.eclipse.m2e.core.project.LocalProjectScanner.run(LocalProjectScanner.java:65)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenImportWizardPage.lambda$14(MavenImportWizardPage.java:385)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

I'm running under windows ... no problems until yet.

I have a .mvn/extensions.xml in my project:

```
<?xml version="1.0" encoding="UTF-8"?>
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
  <extension>
    <groupId>co.leantechniques</groupId>
    <artifactId>maven-buildtime-extension</artifactId>
    <version>3.0.5</version>
  </extension>
  <extension>
    <groupId>me.qoomon</groupId>
    <artifactId>maven-git-versioning-extension</artifactId>
    <version>9.7.0</version>
  </extension>
  <extension>
    <groupId>org.apache.maven.extensions</groupId>
    <artifactId>maven-build-cache-extension</artifactId>
    <version>1.1.0</version>
  </extension>
  <extension>
    <groupId>io.takari.maven</groupId>
    <artifactId>takari-smart-builder</artifactId>
    <version>0.6.4</version>
  </extension>
</extensions>
```

I'm using:

Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.6.0.20240219-2341	org.eclipse.m2e.feature

**Comment by ahoehma** [comment]
Hmmm. I did some experiments ... not sure about the results :-)

1. I commented out first extension + try to import project -> errors
2. I commented out all extensions + try to import project -> works now
3. I commented IN all extensions again + try to import project -> works now too

But after import ... same errors as before:

```
Errors running builder 'Maven Project Builder' on project 'util'.

java.nio.file.InvalidPathException: Illegal char <:> at index 44: D:\Dev\git\coc\spice-configuration-cluster\D:\Dev\ApacheMaven\repository\io\netty\netty-bom\4.1.107.Final\netty-bom-4.1.107.Final.pom.lastUpdated
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.io.File.toPath(File.java:2401)
	at org.eclipse.aether.internal.impl.DefaultTrackingFileManager.read(DefaultTrackingFileManager.java:56)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.read(DefaultUpdateCheckManager.java:461)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:156)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:586)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:525)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:278)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:172)
	at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:1178)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:486)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:455)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:612)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:375)
	at org.eclipse.m2e.core.internal.IMavenToolbox.readMavenProjects(IMavenToolbox.java:126)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$11(ProjectRegistryManager.java:764)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:454)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:335)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readMavenProjectFacades(ProjectRegistryManager.java:760)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:392)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:366)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:318)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:146)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:84)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:454)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:335)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:274)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1079)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:296)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:352)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:441)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:444)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:555)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:503)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:585)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:207)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:300)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by ahoehma** [comment]
More results:

I imported my multi-module-project now without any extension.  Import works but the whole m2e building etc. is not working because of the the path error.

**Comment by laeubi** [comment]
For me it looks like a configuration problem e.g. in your `settings.xml` your are probably using a relative/invalid path somewhere?

**Comment by laeubi** [comment]
> Since I updated to latest m2e my project is broken.

Snapshot or release?

**Comment by ahoehma** [comment]
@laeubi  I'm using snapshot I guess ... I'm installing from  https://download.eclipse.org/technology/m2e/snapshots/latest/

my settings.xml contains something like that:
`<localRepository>D:\Dev\ApacheMaven\repository</localRepository>`
but nothing fancy else ... and it was working until yesterday :)

**Comment by ahoehma** [comment]
I tried also to setup an external mvn but I think the embedded mvn is used for everything except start launchers.

![image](https://github.com/eclipse-m2e/m2e-core/assets/548214/fd977f2a-8a68-40c1-96d4-00fd21e19a9e)

**Comment by laeubi** [comment]
@ahoehma can you try if `<localRepository>D:/Dev/ApacheMaven/repository</localRepository>` is making a difference?

I suspect that for some reason this is interpreted as a relative path instead of an absolute one

**Comment by ahoehma** [comment]
@laeubi I changed the localRepository but with same results.

**Comment by ahoehma** [comment]
@laeubi  I think the new code which calculate the path is not correct.

**Comment by ahoehma** [comment]
I duplicated my settings.xml to settings-m2e.xml and use this in eclipse. (cmdline maven still using my other settings.xml).

And I changed this

`<localRepository>../../../Dev/ApacheMaven/repository</localRepository>`

And now it works :)

Workaround.

**Comment by ahoehma** [comment]
Man könnte sowas hier versuchen:

```
Path p = Paths.get(localRepositoryPath);
if (!p.isAbsolute()) {
...
} else {
...
}
```

**Comment by laeubi** [comment]
@ahoehma this should hopefully fix that:
- https://github.com/eclipse-m2e/m2e-core/pull/1696

if that is merged and snapshot is deployed it would be great if you can confirm / test it!

**Comment by laeubi** [comment]
Snapshot should be available!
