### ISSUE TITLE
M2E's Mac build fails when executing m2e.rcptt.tests

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#1766]
The mac build of m2e fails for some time in `org.eclipse.m2e.rcptt.tests` while launching the rcptt test runtime.
From the log below it looks like some bundles are missing, but I wonder why this is only the case for mac?
We have one profile for mac, but actually I don't expect that to interact with the rcptt test?

@ptziegler you set them up, can you tell why this happens only on Mac?
@kwin IIRC you are on Mac, aren't you? Can you tell or test locally what happens?

```
[INFO] --- rcptt-maven-plugin:2.5.4:execute (default-execute) @ org.eclipse.m2e.rcptt.tests ---
[INFO] Runner command line is /bin/sh -c cd '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/runner/eclipse' && '/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9.0/arm64/Contents/Home/bin/java' '-Xms128m' '-Xmx256m' '-Dorg.eclipse.rcptt.runner.returnTestFailure=true' '-jar' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/runner/eclipse/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar' '-application' 'org.eclipse.rcptt.runner.headless' '-runnerPlatform' 'swt' '-consoleLog' '-data' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/runner-workspace' '-aut' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/aut/Eclipse.app/Contents/Eclipse' '-autWsPrefix' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/aut-ws-' '-autConsolePrefix' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/aut-console-' '-q7report' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/org.eclipse.m2e.rcptt.tests.report' '-htmlReport' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/org.eclipse.m2e.rcptt.tests.html' '-junitReport' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/surefire-reports/TEST-org.eclipse.m2e.rcptt.tests.xml' '-import' '/Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/projects/org.eclipse.m2e.rcptt.tests' '-testOptions' 'execTimeout=1800;testExecTimeout=300' '-timeout' '1800' '-shutdownListenerPort' '9425'
[INFO] The execution timeout is set to 1800 seconds
[INFO] !SESSION 2024-05-25 11:22:02.232 -----------------------------------------------
[INFO] eclipse.buildId=unknown
[INFO] java.version=21.0.3
[INFO] java.vendor=Eclipse Adoptium
[INFO] BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
[INFO] Framework arguments:  -application org.eclipse.rcptt.runner.headless -runnerPlatform swt -aut /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/aut/Eclipse.app/Contents/Eclipse -autWsPrefix /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/aut-ws- -autConsolePrefix /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/aut-console- -q7report /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/org.eclipse.m2e.rcptt.tests.report -htmlReport /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/org.eclipse.m2e.rcptt.tests.html -junitReport /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/surefire-reports/TEST-org.eclipse.m2e.rcptt.tests.xml -import /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/projects/org.eclipse.m2e.rcptt.tests -testOptions execTimeout=1800;testExecTimeout=300 -timeout 1800 -shutdownListenerPort 9425
[INFO] Command-line arguments:  -application org.eclipse.rcptt.runner.headless -runnerPlatform swt -consoleLog -data /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/runner-workspace -aut /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/aut/Eclipse.app/Contents/Eclipse -autWsPrefix /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/aut-ws- -autConsolePrefix /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/aut-console- -q7report /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/org.eclipse.m2e.rcptt.tests.report -htmlReport /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/results/org.eclipse.m2e.rcptt.tests.html -junitReport /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/surefire-reports/TEST-org.eclipse.m2e.rcptt.tests.xml -import /Users/runner/work/m2e-core/m2e-core/org.eclipse.m2e.rcptt.tests/target/projects/org.eclipse.m2e.rcptt.tests -testOptions execTimeout=1800;testExecTimeout=300 -timeout 1800 -shutdownListenerPort 9425
[INFO] 
[INFO] !ENTRY org.eclipse.ecf.provider.filetransfer.httpclient5 4 0 2024-05-25 11:22:03.189
[INFO] !MESSAGE FrameworkEvent ERROR
[INFO] !STACK 0
[INFO] org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ecf.provider.filetransfer.httpclient5 [68]
[INFO]   Unresolved requirement: Import-Package: org.apache.hc.client5.http; version="[5.1.3,6.0.0)"
[INFO] 
[INFO] 	at org.eclipse.osgi.container.Module.start(Module.java:463)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
[INFO] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[INFO] 
[INFO] !ENTRY org.eclipse.equinox.http.jetty 4 0 2024-05-25 11:22:03.196
[INFO] !MESSAGE FrameworkEvent ERROR
[INFO] !STACK 0
[INFO] org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.http.jetty [87]
[INFO]   Unresolved requirement: Import-Package: org.eclipse.equinox.http.servlet; version="[1.2.0,2.0.0)"
[INFO]     -> Export-Package: org.eclipse.equinox.http.servlet; bundle-symbolic-name="org.eclipse.equinox.http.servlet"; bundle-version="1.7.400.v20221006-1531"; version="1.2.0"
[INFO]        org.eclipse.equinox.http.servlet [89]
[INFO]          Unresolved requirement: Import-Package: org.apache.commons.fileupload; version="[1.2.2,2.0.0)"; resolution:="optional"
[INFO]          Unresolved requirement: Import-Package: org.apache.commons.fileupload.disk; version="[1.2.2,2.0.0)"; resolution:="optional"
[INFO]          Unresolved requirement: Import-Package: org.apache.commons.fileupload.servlet; version="[1.2.2,2.0.0)"; resolution:="optional"
[INFO]          Unresolved requirement: Import-Package: org.osgi.service.http.context; version="[1.1.0,1.2.0)"
[INFO]            -> Export-Package: org.osgi.service.http.context; bundle-symbolic-name="org.eclipse.osgi.services"; bundle-version="3.11.100.v20221006-1531"; version="1.1.0"; uses:="org.osgi.framework,javax.servlet.http"
[INFO]               org.eclipse.osgi.services [151]
[INFO]                 Unresolved requirement: Require-Bundle: org.osgi.service.metatype; bundle-version="[1.4.0,1.5.0)"; visibility:="reexport"
[INFO]          Unresolved requirement: Import-Package: org.osgi.service.http; version="[1.2.0,1.3.0)"
[INFO]            -> Export-Package: org.osgi.service.http; bundle-symbolic-name="org.eclipse.osgi.services"; bundle-version="3.11.100.v20221006-1531"; version="1.2.1"; uses:="javax.servlet,javax.servlet.http"
[INFO] 
[INFO] 	at org.eclipse.osgi.container.Module.start(Module.java:463)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
[INFO] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[INFO] 
[INFO] !ENTRY org.eclipse.equinox.http.servlet 4 0 2024-05-25 11:22:03.196
[INFO] !MESSAGE FrameworkEvent ERROR
[INFO] !STACK 0
[INFO] org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.http.servlet [89]
[INFO]   Unresolved requirement: Import-Package: org.apache.commons.fileupload; version="[1.2.2,2.0.0)"; resolution:="optional"
[INFO]   Unresolved requirement: Import-Package: org.apache.commons.fileupload.disk; version="[1.2.2,2.0.0)"; resolution:="optional"
[INFO]   Unresolved requirement: Import-Package: org.apache.commons.fileupload.servlet; version="[1.2.2,2.0.0)"; resolution:="optional"
[INFO]   Unresolved requirement: Import-Package: org.osgi.service.http.context; version="[1.1.0,1.2.0)"
[INFO]     -> Export-Package: org.osgi.service.http.context; bundle-symbolic-name="org.eclipse.osgi.services"; bundle-version="3.11.100.v20221006-1531"; version="1.1.0"; uses:="org.osgi.framework,javax.servlet.http"
[INFO]        org.eclipse.osgi.services [151]
[INFO]          Unresolved requirement: Require-Bundle: org.osgi.service.metatype; bundle-version="[1.4.0,1.5.0)"; visibility:="reexport"
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[INFO] 
[INFO] !ENTRY org.eclipse.pde.runtime 4 0 2024-05-25 11:22:03.204
[INFO] !MESSAGE FrameworkEvent ERROR
[INFO] !STACK 0
[INFO] org.osgi.framework.BundleException: Could not resolve module: org.eclipse.pde.runtime [161]
[INFO]   Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.202.0,4.0.0)"
[INFO] 
[INFO] 	at org.eclipse.osgi.container.Module.start(Module.java:463)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
[INFO] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[INFO] 
[INFO] !ENTRY org.eclipse.rcptt.core.swt 4 0 2024-05-25 11:22:03.205
[INFO] !MESSAGE FrameworkEvent ERROR
[INFO] !STACK 0
[INFO] org.osgi.framework.BundleException: Could not resolve module: org.eclipse.rcptt.core.swt [175]
[INFO]   Unresolved requirement: Require-Bundle: org.eclipse.jface.databinding
[INFO] 
[INFO] 	at org.eclipse.osgi.container.Module.start(Module.java:463)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
[INFO] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
[INFO] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
[INFO] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
[INFO] Started at Sat May 25 11:22:03 UTC 2024
[INFO] RCPTT Runner version: 2.5.5
[INFO] Initializing target platform...
[INFO] Begin task: Create AUT configuration
[INFO] progress: Resolving Target Contents...
[INFO] progress: Reading plug-ins
Error:  org.eclipse.core.runtime.CoreException: No JVM for architecture x86_64 is registered
Error:  	at org.eclipse.rcptt.launching.target.TargetPlatformManager.throwOnError(TargetPlatformManager.java:50)
Error:  	at org.eclipse.rcptt.launching.target.TargetPlatformManager.createTargetPlatform(TargetPlatformManager.java:104)
Error:  	at org.eclipse.rcptt.internal.launching.ext.Q7TargetPlatformManager.createTargetPlatform(Q7TargetPlatformManager.java:125)
Error:  	at org.eclipse.rcptt.runner.util.TargetPlatformChecker.initializeTargetPlatform(TargetPlatformChecker.java:114)
Error:  	at org.eclipse.rcptt.runner.util.TargetPlatformChecker.initAndCheckTargetPlatform(TargetPlatformChecker.java:68)
Error:  	at org.eclipse.rcptt.runner.HeadlessRunner.performCoolThings(HeadlessRunner.java:50)
Error:  	at org.eclipse.rcptt.runner.HeadlessRunnerApp.start(HeadlessRunnerApp.java:54)
Error:  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
Error:  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
Error:  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
Error:  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
Error:  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
Error:  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Error:  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
Error:  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
Error:  	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Error:  	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
[INFO] Runner exit code is: 62
```

**Comment by HannesWell** [comment]
When reading
```
[INFO] progress: Reading plug-ins
Error:  org.eclipse.core.runtime.CoreException: No JVM for architecture x86_64 is registered
```
It remembered me that the GH workflows for mac recently switched from x86_64 to aarch64, so my guess is that this is related, especially since it searches for a x86_64 JVM but mac runs on aarch64.
Since https://github.com/eclipse-m2e/m2e-core/pull/1079 we at least have an aarch64 environment defined.

**Comment by ptziegler** [comment]
> It remembered me that the GH workflows for mac recently switched from x86_64 to aarch64, so my guess is that this is related, especially since it searches for a x86_64 JVM but mac runs on aarch64.

That's also my suspicion. Without a Mac to test myself I can only speculate, but this sound very much like the Eclipse IDE can't be launched so the test fails during the setup phase.

The test is indeed running on aarch64, so the error makes sense:

> [INFO] BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
> Error:  org.eclipse.core.runtime.CoreException: No JVM for architecture x86_64 is registered

**Comment by ptziegler** [comment]
Looking at https://github.com/eclipse/org.eclipse.rcptt/pull/38, aarch64 might not even be supported by RCPTT 😦

**Comment by HannesWell** [comment]
> Looking at [eclipse/org.eclipse.rcptt#38](https://github.com/eclipse/org.eclipse.rcptt/pull/38), aarch64 might not even be supported by RCPTT 😦

:/ I feared that this could be the case. Maybe the RCPTT maintainer can help.

**Comment by ptziegler** [comment]
I've created https://github.com/eclipse-m2e/m2e-core/pull/1767 to test everything with a newer version of RCPTT
