### ISSUE TITLE
cxf-codegen-plugin with 'wsdl2java' goal shows a problem

### ISSUE THREAD

**Issue by vincenzocaselli** [eclipse-m2e/m2e-core#190]
In pom.xml, if using CXF for generating Java sources from a given WSDL, with a block similar to the following:

```
<plugin>
	<groupId>org.apache.cxf</groupId>
	<artifactId>cxf-codegen-plugin</artifactId>
	<version>3.2.1</version>
	<executions>
		<execution>
			<id>generate-sources</id>
			<phase>generate-sources</phase>
			<configuration>
				<sourceRoot>${project.build.directory}/generated/cxf</sourceRoot>
				<wsdlOptions>
					<wsdlOption>
						<wsdl>${basedir}/src/main/resources/wsdl/abc.wsdl</wsdl>
						<wsdlLocation>classpath:abc.wsdl</wsdlLocation>
					</wsdlOption>
				</wsdlOptions>
			</configuration>
			<goals>
				<goal>wsdl2java</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Eclipse shows the Problem below.

Tested on: 

- Linux Arch and Windows 10
- Eclipse 2020-12 and 2021-03
- Oracle JDK 1.8 in Preferences and Oracle JDK 15 for Eclipse (eclipse.ini)
 

Execution generate-sources of goal org.apache.cxf:cxf-codegen-plugin:3.2.1:wsdl2java failed: A required class was missing while executing org.apache.cxf:cxf-codegen-plugin:3.2.1:wsdl2java: javax/xml/bind/annotation/adapters/HexBinaryAdapter
-----------------------------------------------------
realm =    plugin>org.apache.cxf:cxf-codegen-plugin:3.2.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-codegen-plugin/3.2.1/cxf-codegen-plugin-3.2.1.jar
urls[1] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
urls[2] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-archiver/1.2/plexus-archiver-1.2.jar
urls[3] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-io/1.0.1/plexus-io-1.0.1.jar
urls[4] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-core/3.2.1/cxf-core-3.2.1.jar
urls[5] = file:/home/vincenzo/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar
urls[6] = file:/home/vincenzo/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
urls[7] = file:/home/vincenzo/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.2/xmlschema-core-2.2.2.jar
urls[8] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-common/3.2.1/cxf-tools-common-3.2.1.jar
urls[9] = file:/home/vincenzo/.m2/repository/org/apache/velocity/velocity-engine-core/2.0/velocity-engine-core-2.0.jar
urls[10] = file:/home/vincenzo/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar
urls[11] = file:/home/vincenzo/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
urls[12] = file:/home/vincenzo/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar
urls[13] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-xjc/2.2.11/jaxb-xjc-2.2.11.jar
urls[14] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
urls[15] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar
urls[16] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-core/3.2.1/cxf-tools-wsdlto-core-3.2.1.jar
urls[17] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-validator/3.2.1/cxf-tools-validator-3.2.1.jar
urls[18] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-bindings-soap/3.2.1/cxf-rt-bindings-soap-3.2.1.jar
urls[19] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-databinding-jaxb/3.2.1/cxf-rt-databinding-jaxb-3.2.1.jar
urls[20] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-wsdl/3.2.1/cxf-rt-wsdl-3.2.1.jar
urls[21] = file:/home/vincenzo/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar
urls[22] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-databinding-jaxb/3.2.1/cxf-tools-wsdlto-databinding-jaxb-3.2.1.jar
urls[23] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-jaxws/3.2.1/cxf-tools-wsdlto-frontend-jaxws-3.2.1.jar
urls[24] = file:/home/vincenzo/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
urls[25] = file:/home/vincenzo/.m2/repository/org/apache/commons/commons-text/1.1/commons-text-1.1.jar
urls[26] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-javascript/3.2.1/cxf-tools-wsdlto-frontend-javascript-3.2.1.jar
urls[27] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-javascript/3.2.1/cxf-rt-javascript-3.2.1.jar
urls[28] = file:/home/vincenzo/.m2/repository/org/springframework/spring-core/4.3.12.RELEASE/spring-core-4.3.12.RELEASE.jar
urls[29] = file:/home/vincenzo/.m2/repository/org/springframework/spring-beans/4.3.12.RELEASE/spring-beans-4.3.12.RELEASE.jar
urls[30] = file:/home/vincenzo/.m2/repository/org/springframework/spring-context/4.3.12.RELEASE/spring-context-4.3.12.RELEASE.jar
urls[31] = file:/home/vincenzo/.m2/repository/org/springframework/spring-aop/4.3.12.RELEASE/spring-aop-4.3.12.RELEASE.jar
urls[32] = file:/home/vincenzo/.m2/repository/org/springframework/spring-expression/4.3.12.RELEASE/spring-expression-4.3.12.RELEASE.jar
urls[33] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
urls[34] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant-launcher/1.10.1/ant-launcher-1.10.1.jar
urls[35] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant-nodeps/1.8.1/ant-nodeps-1.8.1.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------
 (org.apache.cxf:cxf-codegen-plugin:3.2.1:wsdl2java:generate-sources:generate-sources)

org.apache.maven.plugin.PluginExecutionException: Execution generate-sources of goal org.apache.cxf:cxf-codegen-plugin:3.2.1:wsdl2java failed: A required class was missing while executing org.apache.cxf:cxf-codegen-plugin:3.2.1:wsdl2java: javax/xml/bind/annotation/adapters/HexBinaryAdapter
-----------------------------------------------------
realm =    plugin>org.apache.cxf:cxf-codegen-plugin:3.2.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-codegen-plugin/3.2.1/cxf-codegen-plugin-3.2.1.jar
urls[1] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
urls[2] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-archiver/1.2/plexus-archiver-1.2.jar
urls[3] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-io/1.0.1/plexus-io-1.0.1.jar
urls[4] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-core/3.2.1/cxf-core-3.2.1.jar
urls[5] = file:/home/vincenzo/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar
urls[6] = file:/home/vincenzo/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
urls[7] = file:/home/vincenzo/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.2/xmlschema-core-2.2.2.jar
urls[8] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-common/3.2.1/cxf-tools-common-3.2.1.jar
urls[9] = file:/home/vincenzo/.m2/repository/org/apache/velocity/velocity-engine-core/2.0/velocity-engine-core-2.0.jar
urls[10] = file:/home/vincenzo/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar
urls[11] = file:/home/vincenzo/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
urls[12] = file:/home/vincenzo/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar
urls[13] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-xjc/2.2.11/jaxb-xjc-2.2.11.jar
urls[14] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
urls[15] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar
urls[16] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-core/3.2.1/cxf-tools-wsdlto-core-3.2.1.jar
urls[17] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-validator/3.2.1/cxf-tools-validator-3.2.1.jar
urls[18] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-bindings-soap/3.2.1/cxf-rt-bindings-soap-3.2.1.jar
urls[19] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-databinding-jaxb/3.2.1/cxf-rt-databinding-jaxb-3.2.1.jar
urls[20] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-wsdl/3.2.1/cxf-rt-wsdl-3.2.1.jar
urls[21] = file:/home/vincenzo/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar
urls[22] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-databinding-jaxb/3.2.1/cxf-tools-wsdlto-databinding-jaxb-3.2.1.jar
urls[23] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-jaxws/3.2.1/cxf-tools-wsdlto-frontend-jaxws-3.2.1.jar
urls[24] = file:/home/vincenzo/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
urls[25] = file:/home/vincenzo/.m2/repository/org/apache/commons/commons-text/1.1/commons-text-1.1.jar
urls[26] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-javascript/3.2.1/cxf-tools-wsdlto-frontend-javascript-3.2.1.jar
urls[27] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-javascript/3.2.1/cxf-rt-javascript-3.2.1.jar
urls[28] = file:/home/vincenzo/.m2/repository/org/springframework/spring-core/4.3.12.RELEASE/spring-core-4.3.12.RELEASE.jar
urls[29] = file:/home/vincenzo/.m2/repository/org/springframework/spring-beans/4.3.12.RELEASE/spring-beans-4.3.12.RELEASE.jar
urls[30] = file:/home/vincenzo/.m2/repository/org/springframework/spring-context/4.3.12.RELEASE/spring-context-4.3.12.RELEASE.jar
urls[31] = file:/home/vincenzo/.m2/repository/org/springframework/spring-aop/4.3.12.RELEASE/spring-aop-4.3.12.RELEASE.jar
urls[32] = file:/home/vincenzo/.m2/repository/org/springframework/spring-expression/4.3.12.RELEASE/spring-expression-4.3.12.RELEASE.jar
urls[33] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
urls[34] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant-launcher/1.10.1/ant-launcher-1.10.1.jar
urls[35] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant-nodeps/1.8.1/ant-nodeps-1.8.1.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:171)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1380)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:276)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:329)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:332)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:384)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:405)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing org.apache.cxf:cxf-codegen-plugin:3.2.1:wsdl2java: javax/xml/bind/annotation/adapters/HexBinaryAdapter
-----------------------------------------------------
realm =    plugin>org.apache.cxf:cxf-codegen-plugin:3.2.1
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-codegen-plugin/3.2.1/cxf-codegen-plugin-3.2.1.jar
urls[1] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
urls[2] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-archiver/1.2/plexus-archiver-1.2.jar
urls[3] = file:/home/vincenzo/.m2/repository/org/codehaus/plexus/plexus-io/1.0.1/plexus-io-1.0.1.jar
urls[4] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-core/3.2.1/cxf-core-3.2.1.jar
urls[5] = file:/home/vincenzo/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.0.3/woodstox-core-5.0.3.jar
urls[6] = file:/home/vincenzo/.m2/repository/org/codehaus/woodstox/stax2-api/3.1.4/stax2-api-3.1.4.jar
urls[7] = file:/home/vincenzo/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.2/xmlschema-core-2.2.2.jar
urls[8] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-common/3.2.1/cxf-tools-common-3.2.1.jar
urls[9] = file:/home/vincenzo/.m2/repository/org/apache/velocity/velocity-engine-core/2.0/velocity-engine-core-2.0.jar
urls[10] = file:/home/vincenzo/.m2/repository/org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar
urls[11] = file:/home/vincenzo/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
urls[12] = file:/home/vincenzo/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar
urls[13] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-xjc/2.2.11/jaxb-xjc-2.2.11.jar
urls[14] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar
urls[15] = file:/home/vincenzo/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar
urls[16] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-core/3.2.1/cxf-tools-wsdlto-core-3.2.1.jar
urls[17] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-validator/3.2.1/cxf-tools-validator-3.2.1.jar
urls[18] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-bindings-soap/3.2.1/cxf-rt-bindings-soap-3.2.1.jar
urls[19] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-databinding-jaxb/3.2.1/cxf-rt-databinding-jaxb-3.2.1.jar
urls[20] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-wsdl/3.2.1/cxf-rt-wsdl-3.2.1.jar
urls[21] = file:/home/vincenzo/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar
urls[22] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-databinding-jaxb/3.2.1/cxf-tools-wsdlto-databinding-jaxb-3.2.1.jar
urls[23] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-jaxws/3.2.1/cxf-tools-wsdlto-frontend-jaxws-3.2.1.jar
urls[24] = file:/home/vincenzo/.m2/repository/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
urls[25] = file:/home/vincenzo/.m2/repository/org/apache/commons/commons-text/1.1/commons-text-1.1.jar
urls[26] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-tools-wsdlto-frontend-javascript/3.2.1/cxf-tools-wsdlto-frontend-javascript-3.2.1.jar
urls[27] = file:/home/vincenzo/.m2/repository/org/apache/cxf/cxf-rt-javascript/3.2.1/cxf-rt-javascript-3.2.1.jar
urls[28] = file:/home/vincenzo/.m2/repository/org/springframework/spring-core/4.3.12.RELEASE/spring-core-4.3.12.RELEASE.jar
urls[29] = file:/home/vincenzo/.m2/repository/org/springframework/spring-beans/4.3.12.RELEASE/spring-beans-4.3.12.RELEASE.jar
urls[30] = file:/home/vincenzo/.m2/repository/org/springframework/spring-context/4.3.12.RELEASE/spring-context-4.3.12.RELEASE.jar
urls[31] = file:/home/vincenzo/.m2/repository/org/springframework/spring-aop/4.3.12.RELEASE/spring-aop-4.3.12.RELEASE.jar
urls[32] = file:/home/vincenzo/.m2/repository/org/springframework/spring-expression/4.3.12.RELEASE/spring-expression-4.3.12.RELEASE.jar
urls[33] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
urls[34] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant-launcher/1.10.1/ant-launcher-1.10.1.jar
urls[35] = file:/home/vincenzo/.m2/repository/org/apache/ant/ant-nodeps/1.8.1/ant-nodeps-1.8.1.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:169)
	... 30 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
	at org.apache.cxf.maven_plugin.AbstractCodegenMoho.getDoneFile(AbstractCodegenMoho.java:587)
	at org.apache.cxf.maven_plugin.wsdl2java.WSDL2JavaMojo.generate(WSDL2JavaMojo.java:348)
	at org.apache.cxf.maven_plugin.AbstractCodegenMoho.execute(AbstractCodegenMoho.java:279)
	at org.apache.cxf.maven_plugin.wsdl2java.WSDL2JavaMojo.execute(WSDL2JavaMojo.java:511)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 30 more

**Comment by mickaelistria** [comment]
Invoking Maven mojos from m2e uses the IDE Java installation (Java 15); it's running it with current Java and not as a separate process. `HexBinaryAdapter` is not available in Java 15, causing this error.
There are newer releases of cxf-codegen-plugin which might be compatible with newer Java versions. Please give them a try.

**Comment by Lakshmi0211** [comment]
@mickaelistria 

Still, I'm able reproducing issue in OpenJDK 11. We do have any update regarding this issue.

**Comment by Lakshmi0211** [comment]
@laeubi 

Based on scope of my project. I'm migrating OpenJDK from 8 to 11. If i used Java 11 the entire project will be broken. Is there any other option for fixing the above issue.

**Comment by Lakshmi0211** [comment]
@laeubi 

Based on scope of my project. I'm migrating OpenJDK from 8 to 11. If i used Java 17 the entire project will be broken. Is there any other option for fixing the above issue.

**Comment by Lakshmi0211** [comment]
@laeubi 

Based on scope of my project. I'm migrating OpenJDK from 8 to 11. If i used Java 17 the entire project will be broken. Is there any other option for fixing the above issue.

**Comment by Lakshmi0211** [comment]
@laeubi 

Based on scope of my project. I'm migrating OpenJDK from 8 to 11. If i used Java 17 the entire project will be broken. Is there any other option for fixing the above issue.

**Comment by Lakshmi0211** [comment]
@laeubi 

Based on scope of my project. I'm migrating OpenJDK from 8 to 11. If i used Java 17 the entire project will be broken. Is there any other option for fixing the above issue.

**Comment by Lakshmi0211** [comment]
@laeubi 

Based on scope of my project. I'm migrating OpenJDK from 8 to 11. If i used Java 17 the entire project will be broken. Is there any other option for fixing the above issue.

**Comment by laeubi** [comment]
The JDK used for your IDE does not has to be the JDK you use for your project.
