### ISSUE TITLE
Latest snapshots of m2e fails to load the effective POM

### ISSUE THREAD

**Issue by gayanper** [eclipse-m2e/m2e-core#275]
```
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4893)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.SWT.error(SWT.java:4779)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:438)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:358)
	at org.eclipse.swt.custom.StyledText.setStyleRange(StyledText.java:10443)
	at org.eclipse.jface.text.TextViewer.addPresentation(TextViewer.java:4662)
	at org.eclipse.jface.text.TextViewer.changeTextPresentation(TextViewer.java:4770)
	at org.eclipse.jface.text.presentation.PresentationReconciler.applyTextRegionCollection(PresentationReconciler.java:562)
	at org.eclipse.jface.text.presentation.PresentationReconciler.processDamage(PresentationReconciler.java:551)
	at org.eclipse.jface.text.presentation.PresentationReconciler$InternalListener.textChanged(PresentationReconciler.java:215)
	at org.eclipse.jface.text.TextViewer.updateTextListeners(TextViewer.java:2709)
	at org.eclipse.jface.text.TextViewer$VisibleDocumentListener.documentChanged(TextViewer.java:397)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged2(AbstractDocument.java:748)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:717)
	at org.eclipse.jface.text.AbstractDocument.doFireDocumentChanged(AbstractDocument.java:701)
	at org.eclipse.jface.text.AbstractDocument.fireDocumentChanged(AbstractDocument.java:775)
	at org.eclipse.jface.text.AbstractDocument.set(AbstractDocument.java:1140)
	at org.eclipse.jface.text.AbstractDocument.set(AbstractDocument.java:1123)
	at org.eclipse.m2e.editor.pom.MavenPomEditor$LoadEffectivePomJob.run(MavenPomEditor.java:511)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Version: 1.18.2

**Comment by HannesWell** [comment]
I cannot confirm this.
Furthermore your Stack-trace shows another `IDocument` implementation than expected.
When I debug it, the document is `org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument` which does not inherit AbstractDocument.

Maybe your configuration is corrupted.
Can you set up a m2e developer environment as outlined in the Contributing guide and remote debug your Eclipse to see what the cause is?

**Comment by gayanper** [comment]
> I cannot confirm this.
> Furthermore your Stack-trace shows another `IDocument` implementation than expected.
> When I debug it, the document is `org.eclipse.wst.sse.core.internal.text.JobSafeStructuredDocument` which does not inherit AbstractDocument.
> 
> Maybe your configuration is corrupted.
> Can you set up a m2e developer environment as outlined in the Contributing guide and remote debug your Eclipse to see what the cause is?

I forgot to mention, I’m using the generic editor with lemminx maven plugin enabled force fully bu removing the SSE plugin.

**Comment by mickaelistria** [comment]
I can easily reproduce the exception without the WTP/SSE Editor (and even without the lemminx-based ediotr), but I don't think it's related to the effective pom loading.
Can you please verify in an older Eclipse release whether this same pom manages to have its effective pom loaded? i guess not.
I think this issue should then either be retitled to fpcus on the exception, or closed.

**Comment by mickaelistria** [comment]
The exception shouldn't happen any more. Please try latest snapshots to verify.
