### ISSUE TITLE
NPE when creating problem markers on a remote project

### ISSUE THREAD

**Issue by ivy-rew** [eclipse-m2e/m2e-core#310]
Having a remote project with an unsolvable  'system' scoped dependency in my workspace, a problem marker is being created for it. However, that operation fails with an NPE as IResource.getLocation() is being used, which can return null for remote projects.

I'll propose a fix for it.

```
java.lang.NullPointerException
	at org.eclipse.m2e.core.internal.markers.SourceLocationHelper.findLocation(SourceLocationHelper.java:89)
	at org.eclipse.m2e.core.internal.markers.MavenMarkerManager.toMavenProblemInfos(MavenMarkerManager.java:211)
	at org.eclipse.m2e.core.internal.markers.MavenMarkerManager.addMarkers(MavenMarkerManager.java:65)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$4(ProjectRegistryManager.java:750)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.execute(ProjectRegistryManager.java:1027)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readMavenProjectFacades(ProjectRegistryManager.java:735)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:431)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:364)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:315)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:409)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$1(ProjectConfigurationManager.java:358)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1370)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:357)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:343)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:325)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:314)
	at ch.ivyteam.ivy.project.internal.imprt.AbstractIvyArchiveFileSource.updateMaven(AbstractIvyArchiveFileSource.java:92)
	at ch.ivyteam.ivy.project.internal.imprt.AbstractIvyArchiveFileSource.prepareProject(AbstractIvyArchiveFileSource.java:77)
	at ch.ivyteam.ivy.project.internal.imprt.IvyProjectImportRunner.importProject(IvyProjectImportRunner.java:82)
	at ch.ivyteam.ivy.project.internal.imprt.IvyProjectImportRunner.runInWorkspace(IvyProjectImportRunner.java:57)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2312)
	at ch.ivyteam.ivy.project.internal.imprt.IvyProjectImportRunner.run(IvyProjectImportRunner.java:43)
	at ch.ivyteam.ivy.designer.project.ui.internal.ivyarchive.IvyArchiveImporter.run(IvyArchiveImporter.java:33)
	at ch.ivyteam.ivy.designer.project.ui.internal.ivyarchive.repo.IvyRepoImportProcessor.run(IvyRepoImportProcessor.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by mickaelistria** [comment]
Patch merged, thanks. Fix should be available snapshots in a dozen of minutes, when https://ci.eclipse.org/m2e/job/m2e/job/master/61/ completes.

**Comment by ivy-rew** [comment]
Thanks for the integration @mickaelistria  . Love to see a responsive community keeping m2e alive :+1:
