### ISSUE TITLE
Opening profile selection dialogue fails if hierarchy POM is only available via relative path

### ISSUE THREAD

**Issue by josple** [eclipse-m2e/m2e-core#366]
### Issue
We have a slightly complex POM (let's call it POM A) with the following POM hierarchy:
1. POM A declares POM B as it's parent and provides a relative path. POM B **is** published into the Maven repository
2. POM B declares POM C as it's parent and provides a relative path. POM C is **not** published into the Maven repository

When we open project A (with POM A) in the Eclipse IDE and attempt to open the profile selection dialogue box in the UI we get an error with the following error log:

> !MESSAGE Unable to open the Maven Profile selection dialog
!STACK 1
org.eclipse.core.runtime.CoreException: Could not resolve artifact POM-C:pom:Unversioned-SNAPSHOT
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$4(MavenImpl.java:804)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:772)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:749)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.resolvePomModel(ProfileManager.java:272)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getModelHierarchy(ProfileManager.java:220)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getModelHierarchy(ProfileManager.java:222)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getProfileDatas(ProfileManager.java:125)
	at org.eclipse.m2e.profiles.ui.internal.actions.ProfileSelectionHandler$GetProfilesJob.getAllProfiles(ProfileSelectionHandler.java:276)
	at org.eclipse.m2e.profiles.ui.internal.actions.ProfileSelectionHandler$GetProfilesJob.run(ProfileSelectionHandler.java:190)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Missing POM-C:pom:Unversioned-SNAPSHOT
!SUBENTRY 1 org.eclipse.m2e.core 4 -1 2021-10-11 12:12:22.278
!MESSAGE Could not resolve artifact POM-C:pom:Unversioned-SNAPSHOT
!SUBENTRY 2 org.eclipse.m2e.core 4 -1 2021-10-11 12:12:22.278
!MESSAGE Missing POM-C:pom:Unversioned-SNAPSHOT

We can work around this issue by opening the Maven project that contains POM C locally in the IDE. But it would be ideal if the POM could be resolved via the relative path so that we could avoid having to have this module open locally whenever we wish to change Maven profile selections. 

### System details
Eclipse Platform
- Version: 2021-03 (4.19)
- Build id: I20210303-1800

M2e version:
- Maven Integration for Eclipse	1.17.2.20210219-1922	org.eclipse.m2e.feature

**Comment by mickaelistria** [comment]
Would you be able to debug this issue and maybe provide a PR fixing it?
