### ISSUE TITLE
Content assist issues in Lemminx Maven POM XML editor

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-m2e/m2e-core#512]
_The Leminx Maven POM XML Editor content assistant generates wrong insertions, in some cases, that produce node duplications, broken nodes in text and throw the exceptions._ 

OK, let's see what I have now

```
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1***ASK FOR CODE COMPLETION***</version>
		</dependency>
```

I finally get the available versions!
Cool! It works?

Let's try to add another dependency, say org.mockito:mockito-core (REMEMBER, I started with an empty .m2 folder)

```
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
		</dependency>
***ASK FOR CODE COMPLETION***
```

no trace of mockito proposals (even if starting writing "mock")
commons-io is proposed (it's actually cached in the .m2 folder, maybe due to the Maven standard plugins)

Let's manually specify the groupId org.mockito (manually, because no code completion helps me here).
Then,

```
		<dependency>
			<groupId>org.mockito</groupId>
			***ASK FOR CODE COMPLETION***
		</dependency>
```

org.mockito:mockito-core is proposed and after acceptance I get

```
		<dependency>
			<groupId>org.mockito</groupId>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>4.1.0</version>
		</dependency>
```

so you see, the completion reinserts also the groupId, breaking the validity of the POM

Let's add <artifactId> and ask for completion

```
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>***ASK FOR CODE COMPLETION***</artifactId>
    </dependency>
```

mockito-core is proposed and after acceptance I get

```
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifact
       <version>4.1.0</version>Id>
    </dependency>
```

which again breaks the validity of the XML (see the broken XML elements after the insertion of the proposal)

after mockito was added (in the .m2 cache), e.g., after manually fixing the XML and saving the POM with a valid dependency of mockito

```
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
		</dependency>
***ASK FOR CODE COMPLETION***
	</dependencies>
```

only mockito-core (which has been cached as a Maven artifact in .m2) is proposed (not, e.g., mockito-all, which is NOT part of the local .m2 cache)

the same behavior can be seen with proposals in the plugins section (even in the pluginManagement)

In the meantime in the Error Log there are tons of this

```
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1163)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:137)
	at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.getLineInformation(BasicStructuredDocument.java:1461)
	at org.eclipse.lsp4e.LSPEclipseUtils.toOffset(LSPEclipseUtils.java:158)
	at org.eclipse.lsp4e.outline.SymbolsLabelProvider.getMaxSeverity(SymbolsLabelProvider.java:177)
	at org.eclipse.lsp4e.outline.SymbolsLabelProvider.getImage(SymbolsLabelProvider.java:154)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.findImage(NavigatorContentServiceLabelProvider.java:204)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getColumnImage(NavigatorContentServiceLabelProvider.java:112)
	at org.eclipse.ui.internal.navigator.NavigatorContentServiceLabelProvider.getImage(NavigatorContentServiceLabelProvider.java:104)
	at org.eclipse.ui.internal.navigator.NavigatorDecoratingLabelProvider$StyledLabelProviderAdapter.getImage(NavigatorDecoratingLabelProvider.java:63)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getImage(DelegatingStyledCellLabelProvider.java:198)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getImage(DecoratingStyledCellLabelProvider.java:171)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:124)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.update(DecoratingStyledCellLabelProvider.java:134)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	...
```

_Originally posted by @LorenzoBettini in https://github.com/eclipse-m2e/m2e-core/issues/441#issuecomment-992530718_

**Comment by mickaelistria** [comment]
This should be fixed in upcoming snapshot build, thanks to https://github.com/eclipse/lemminx-maven/commit/f3ce68f6bded185931ae6c0e49375773b4921558
