### ISSUE TITLE
POM Editor - Eclipse waiting then quitting

### ISSUE THREAD

**Issue by gsmet** [eclipse-m2e/m2e-core#514]
This one is a bit hard to reproduce and doesn't happen always.

But it happens quite often. I thought it was related to the size of the Quarkus BOM but I also had the issue opening the Quarkus CLI pom which is far smaller (but always with my workspace with the full Quarkus project - https://github.com/quarkusio/quarkus).

When it happens, I open a POM file, Eclipse becomes unresponsive and Gnome asks me if I want to wait. I click on Wait several times and then Eclipse quits abruptly.

I have this in my `.metadata/.log` but I have no idea if it's related:
```
!ENTRY org.eclipse.lsp4e 4 0 2022-01-21 13:26:21.312
!MESSAGE org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
!STACK 0
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
        at org.eclipse.lsp4e.LanguageServerWrapper.lambda$13(LanguageServerWrapper.java:425)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
        at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Happy to dig more if you want the content of some other files.

This is with Eclipse 2021-12 and:
```
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.19.0.20211116-0804	org.eclipse.m2e.feature
```

**Comment by mickaelistria** [comment]
I suspect this can be fixed, or at least improved, if using newer snapshots of m2e and lsp4e.

**Comment by arjantijms** [comment]
This happens a lot indeed with projects of all sizes and on Linux and macOS. I would have expected more reports of it though.

**Comment by laeubi** [comment]
@arjantijms @gsmet could you try the latest snapshot and report if the problem still persist?

**Comment by laeubi** [comment]
Great, thanks for the feedback.

**Comment by gsmet** [comment]
Yeah same here. I don't have this particular issues but I have several others. I need to create issues for them.

**Comment by arjantijms** [comment]
Yeah, issues include the editor generating "garbage" while trying to complete tags when editing. Sometimes it's so bad I need to open a pom.xml in text mode, as the autocompletion and copy paste keeps producing garbage in the pom. 

But like the hang it's not so easy to reproduce, or even describe what's going on.

**Comment by gsmet** [comment]
For me, it's very slow copy/paste sometimes not copying anything. I don't know if it's the selection that is slow or something else but it's getting very hard to make sure something has been copied. And it can take ages to paste something.
In the end, I do: selection - wait 3 seconds - copy - wait 3 seconds - paste (and the paste can take several seconds to be effective).

I also have problems with the autocompletion going crazy and looking for proposals in some weird places (and staying in progress). And also the same thing of never completing when it should be able to find something useful.

I have no idea if this is easily reproducible outside of my projects though.

For some changes, I end up using vim instead of the editor.

@arjantijms do you experience the same thing?

**Comment by laeubi** [comment]
If any of you can give some more details / examples in reproduce the issue it would be helpful to collect them here:

- https://github.com/eclipse/lemminx-maven/issues/288

**Comment by mickaelistria** [comment]
@gsmet Please report dedicate issues, ideally with steps to rerproduce.

**Comment by gsmet** [comment]
Yeah, so that's my problem and why I haven't opened issues yet. I have no idea how to reproduce this. It just started one day and has been nightmarish since then but I have no idea what's the starting point of this.

(and yes, I know it's not helpful but I thought asking Arjan if he was experiencing the same could help narrowing it down)

**Comment by arjantijms** [comment]
I don't see that particular issue with the slow copy/paste, although similarly to what was mentioned above issues with copying tags appearing garbled in the pom. 

Also a weird issue specifically with using the ant runner plugin and embedded ant tags; the editor keeps being focussed on an ant tag. When scrolling the pom down or up, it autoscrolls bag to that one tag.

As with all those issues, difficult to reproduce specifically, but still happen "all the time".

**Comment by laeubi** [comment]
@gsmet it even helps to note that you are experiencing the same issue in the linked ticket so probably you can share your OS (is it OS specific), or even a project you ar working on where it most often occurs... I think every pice helps.

**Comment by gsmet** [comment]
@laeubi OK, I'll try to get you some info. It happens with the Quarkus project and the whole workspace is Open Source so I can even share the workspace, the Eclipse install and the git repo if it can help you.

I'll do that soon.
