### ISSUE TITLE
NPE in org.eclipse.m2e.pde.ui.provider.DependencyNodeLabelProvider.<init>(DependencyNodeLabelProvider.java:30)

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#585]
I see the following in my log, followed by the exception reported in https://bugs.eclipse.org/bugs/show_bug.cgi?id=578775

org.osgi.framework.BundleException: Exception in org.eclipse.m2e.pde.ui.Activator.stop() of bundle org.eclipse.m2e.pde.ui.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:890)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1888)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1763)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError
	at org.eclipse.m2e.pde.ui.Activator.stop(Activator.java:33)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:870)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:862)
	... 13 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.disposeExec(java.lang.Runnable)" because "toQuery" is null
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:224)
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:242)
	at org.eclipse.m2e.pde.ui.provider.DependencyNodeLabelProvider.<init>(DependencyNodeLabelProvider.java:30)
	at org.eclipse.m2e.pde.ui.adapter.DependencyNodeAdapterFactory.<clinit>(DependencyNodeAdapterFactory.java:27)
	... 18 more
Root exception:
java.lang.ExceptionInInitializerError
	at org.eclipse.m2e.pde.ui.Activator.stop(Activator.java:33)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:870)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:862)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1046)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:376)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1888)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1763)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:275)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:208)
	at org.eclipse.osgi.container.Module.doStop(Module.java:660)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.disposeExec(java.lang.Runnable)" because "toQuery" is null
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:224)
	at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:242)
	at org.eclipse.m2e.pde.ui.provider.DependencyNodeLabelProvider.<init>(DependencyNodeLabelProvider.java:30)
	at org.eclipse.m2e.pde.ui.adapter.DependencyNodeAdapterFactory.<clinit>(DependencyNodeAdapterFactory.java:27)
	... 18 more

**Comment by iloveeclipse** [comment]
The [DependencyNodeAdapterFactory](https://github.com/eclipse-m2e/m2e-core/blob/10474ca5f0204e23f643c9b17a21bd7843926477/org.eclipse.m2e.pde.ui/src/org/eclipse/m2e/pde/ui/adapter/DependencyNodeAdapterFactory.java#L27) is initialized **on shutdown**. 
As we see it can't work if it was never used before :-)

**Comment by laeubi** [comment]
Please report this to JFace as this is cause by

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.disposeExec(java.lang.Runnable)" because "toQuery" is null
at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:224)
at org.eclipse.jface.resource.JFaceResources.getResources(JFaceResources.java:242)
```

Beside that, I will refactor all adapters in 2.0 to use the new Service Registration approach that will avoid such race conditions.

**Comment by iloveeclipse** [comment]
Nope. The client has to provide non null Display. The client in this case tries to get ResourceManager after Display is already disposed **or** from non-UI thread. That will never work and is also documented:
```	 * Returns the ResourceManager for the current display. May only be called
	 * from a UI thread.```

**Comment by laeubi** [comment]
> Nope. The client has to provide non null Display. The client in this case tries to get ResourceManager after Display is already disposed **or** from non-UI thread. That will never work and is also documented: `Returns the ResourceManager for the current display. May only be called from a UI thread.`

The "client" is not passing anything here and JFace should either take some action (e.g. return al null resource) here or throw a meaningful error message instead of running into a NPE.

**Comment by iloveeclipse** [comment]
OK, you mean you want exception with `May only be called from a UI thread.` message. That will not fix you problem, but yes, that can be done.

**Comment by laeubi** [comment]
The message should indicate the actual cause:

1. Display of thread `<younameit>` is already disposed
2. Thread `<younameit>` is not an UI thread.

if `JFaceResources.getResources(...)` is allowed to return null, an invalidated resource or whatever that would even be more appropriate then.

> That will not fix you problem

But it will give more clear indication about whats going wrong, the great power of exceptions compared to error codes is that they can carry additional context information that help the user and/or developer to understand the root cause of a problem without debugging the code.
