### ISSUE TITLE
org.codehaus.mojo:build-helper-maven-plugin:3.3.0:timestamp-property failed: date must not be null

### ISSUE THREAD

**Issue by theit** [eclipse-m2e/m2e-core#708]
Eclipse:
Version: 2022-06 M2 (4.24.0 M2)
Build id: 20220505-1344

m2e:
M2E - Maven Integration for Eclipse (includes Incubating components): 1.20.1.20220227-1319
M2E - PDE Integration: 1.20.0.20220208-0831
M2E - POM Editor using LemMinX language server (includes Incubating components): 1.18.4.20220127-1634

Java:
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)

Our project adds the build time into the Jar's manifest via the following snippet:

```xml
<properties>
    ...
    <maven.build.timestamp.format>yyyy-MM-dd_HH:mm:ss</maven.build.timestamp.format>
</properties>

<build>
    <plugins>
        ...
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>3.2.2</version>
            <configuration>
                <archive>
                    <manifestEntries>
                        ...
                        <Build-Time>${maven.build.timestamp}</Build-Time>
                    </manifestEntries>
                </archive>
            </configuration>
        </plugin>
    </plugins>
</build>
```

When building the project inside Jenkins, this doesn't work as desired because Maven uses UTC as time instead of the build machine's local time; see [MNG-5452](https://issues.apache.org/jira/browse/MNG-5452). Therefore I added the build-helper-maven-plugin to the `pom.xml` to create a local timestamp and slightly changed the jar plugin configuration:

```xml
<build>
    <plugins>
        ...
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>build-helper-maven-plugin</artifactId>
            <version>3.3.0</version>
            <executions>
                <execution>
                    <id>local-timestamp-property</id>
                    <phase>validate</phase>
                    <goals>
                        <goal>timestamp-property</goal>
                    </goals>
                    <configuration>
                        <name>local.build.timestamp</name>
                        <pattern>${maven.build.timestamp.format}</pattern>
                        <timeZone>Europe/Berlin</timeZone>
                        <timeSource>build</timeSource>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jar-plugin</artifactId>
            <version>3.2.2</version>
            <configuration>
                <archive>
                    <manifestEntries>
                        ...
                        <Build-Time>${local.build.timestamp}</Build-Time>
                    </manifestEntries>
                </archive>
            </configuration>
        </plugin>
    </plugins>
</build>
```

So far this works as expected, but now Eclipse shows a red "x" at the m-jar-p execution block to indicate an error:

```
Execution local-timestamp-property of goal org.codehaus.mojo:build-helper-maven-plugin:3.3.0:timestamp-property failed: date must not be null (org.codehaus.mojo:build-helper-maven-plugin:3.3.0:timestamp-property:local-timestamp-property:validate)

org.apache.maven.plugin.PluginExecutionException: Execution local-timestamp-property of goal org.codehaus.mojo:build-helper-maven-plugin:3.3.0:timestamp-property failed: date must not be null
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:336)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1423)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:117)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1422)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:55)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:117)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:156)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:103)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:198)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1024)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:254)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:311)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:400)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:403)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:514)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:462)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:544)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NullPointerException: date must not be null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.Calendar.setTime(Calendar.java:1793)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:978)
	at java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:971)
	at java.base/java.text.DateFormat.format(DateFormat.java:378)
	at org.codehaus.mojo.buildhelper.TimestampPropertyMojo.execute(TimestampPropertyMojo.java:225)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 31 more
```

When looking at the build-helper source code the error occurs at the following part:

```java
...
223        if ("build".equals(timeSource))
224        {
225            defineProperty( name, format.format( mavenSession.getStartTime() ) );
226        }
...
```

Obviously ```mavenSession.getStartTime()``` seems to return `null` when executing the mojo. This only occurs within Eclipse, not from the command line.

Is this a bug in m2e?

**Comment by laeubi** [comment]
This is more a "feature" (at least with current code) the start time is explicitly not set by maven.

**Comment by HannesWell** [comment]
> Do you have any solution/workaround/...? What about placing `<?m2e ignore?>` in the execution block? AFAIK this should only affect Eclipse, but nothing else...

You could create an "m2e-profile" that is only active in the IDE and configure the plug-in in a plugin-management section to have `<timeSource>current</timeSource>` set:
```
    <profile>
      <id>m2e</id>
      <activation>
        <property>
          <name>m2e.version</name>
        </property>
      </activation>
   <!--
   plugin configuration only for m2e.
   -->
    </profile>
```

When executing the project build in the IDE m2e injects the `m2e.version` into the Maven request so this profile is only activated in the IDE but not in a regular Maven build (unless you specified it yourself).

**Comment by theit** [comment]
> You could create an "m2e-profile" that is only active in the IDE and configure the plug-in in a plugin-management section to have `<timeSource>current</timeSource>` set:

Yes, but this would add lots of clutter to the pom.xml solely for the purpose of ignoring the (IMHO unnecessary) error that only occurs inside Eclipse. In our team a some colleagues prefer IntelliJ so they wouldn't benefit from that.

Is there anything to be said against using `<?m2e ignore?>` in the execution block? The project should be buildable normally via command line, the CI/CD server, and also from within Eclipse by right-click on the project > Run as... > Maven build... (package). The only side effect I see is that _using_ the project inside Eclipse prevents the plugin from being executed during the Eclipse-internal build so that (in my case) the property isn't defined when the jar plugin is being executed (if any). But that shouldn't matter...

**Comment by mickaelistria** [comment]
> there anything to be said against using <?m2e ignore?> in the execution block? 

No `<?m2e ignore?>` is good and should be advertised a bit more in m2e.

**Comment by HannesWell** [comment]
> Is there anything to be said against using `<?m2e ignore?>` in the execution block? The project should be buildable normally via command line, the CI/CD server, and also from within Eclipse by right-click on the project > Run as... > Maven build... (package). The only side effect I see is that _using_ the project inside Eclipse prevents the plugin from being executed during the Eclipse-internal build so that (in my case) the property isn't defined when the jar plugin is being executed (if any). But that shouldn't matter...

No there nothing against `<?m2e ignore?>`.

The m2e.version profiles are indeed quite verbose most of the time.

**Comment by HannesWell** [comment]
> > there anything to be said against using  in the execution block?
> 
> No. `<?m2e ignore?>` is good and should be advertised a bit more in m2e.

Yes it should be more advertised. Maybe the documentation at https://www.eclipse.org/m2e/documentation/m2e-documentation.html should be made available more prominent and updated.

**Comment by theit** [comment]
> > > there anything to be said against using  in the execution block?
> > 
> > 
> > No. `<?m2e ignore?>` is good and should be advertised a bit more in m2e.
> 
> Yes it should be more advertised. Maybe the documentation at https://www.eclipse.org/m2e/documentation/m2e-documentation.html should be made available more prominent and updated.

+1

I have only seen references to this in the release notes for [m2eclipse 1.7](https://www.eclipse.org/m2e/documentation/release-notes-17.html).

Anyway, thank you all for the hints and comments!

**Comment by laeubi** [comment]
> Yes it should be more advertised

I think we should fix the bug anyways, advertising to disable m2e seems not a profitable option :-D

**Comment by laeubi** [comment]
@theit can you provide a minimal reproducer project for this? I'm currently investigate some ways to make m2e behave more "like maven" so this could be a good test-case for this.

**Comment by laeubi** [comment]
Thanks for the example I used that now to create a test and propose a fix: https://github.com/eclipse-m2e/m2e-core/pull/728
