### ISSUE TITLE
pom.xml completion stuck

### ISSUE THREAD

**Issue by rombert** [eclipse-m2e/m2e-core#768]
I've seen this for a number of times, but since it did not seem to be resolved after the 2022-06 release I decided to report an issue.

When trying to use completions in the pom.xml editor the process never completes and seems stuck at '0 completed, 1 pending'.

![image](https://user-images.githubusercontent.com/21237/173091376-a5ba6ea8-3774-4c69-9f69-545c8b2864e5.png)

I did not notice something particularly wrong in the Eclipse error log or via thread dumps. Getting some thread dumps of the `org.eclipse.lemminx.XMLServerLauncher` process I can see that two ForkJoinPool.commonPool threads are blocked

```
Name: ForkJoinPool.commonPool-worker-2
State: TIMED_WAITING
Total blocked: 22  Total waited: 24,840

Stack trace: 
java.base@17.0.3/java.lang.Thread.sleep(Native Method)
app//org.eclipse.lemminx.extensions.maven.MavenLemminxWorkspaceReader.lambda$findArtifact$4(MavenLemminxWorkspaceReader.java:179)
app//org.eclipse.lemminx.extensions.maven.MavenLemminxWorkspaceReader$$Lambda$143/0x000000080034e710.get(Unknown Source)
java.base@17.0.3/java.util.Optional.or(Optional.java:313)
app//org.eclipse.lemminx.extensions.maven.MavenLemminxWorkspaceReader.findArtifact(MavenLemminxWorkspaceReader.java:175)
app//org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:306)
app//org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
app//org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:207)
app//org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:262)
app//org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:192)
app//org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:242)
app//org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1077)
app//org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:853)
app//org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:344)
app//org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:252)
app//org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:173)
app//org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:137)
app//org.eclipse.lemminx.extensions.maven.MavenProjectCache.parseAndCache(MavenProjectCache.java:132)
app//org.eclipse.lemminx.extensions.maven.MavenProjectCache.check(MavenProjectCache.java:106)
app//org.eclipse.lemminx.extensions.maven.MavenProjectCache.getProblemsFor(MavenProjectCache.java:99)
app//org.eclipse.lemminx.extensions.maven.participants.diagnostics.MavenDiagnosticParticipant.doDiagnostics(MavenDiagnosticParticipant.java:56)
app//org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:65)
app//org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:48)
app//org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:165)
app//org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:174)
app//org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:621)
app//org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$32(XMLTextDocumentService.java:589)
app//org.eclipse.lemminx.XMLTextDocumentService$$Lambda$60/0x000000080018f5e0.accept(Unknown Source)
java.base@17.0.3/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
java.base@17.0.3/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
java.base@17.0.3/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
java.base@17.0.3/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
java.base@17.0.3/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
java.base@17.0.3/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
java.base@17.0.3/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by marco-brandizi** [comment]
Same for me with 2022-03. Moreover, I used to be able to `Cmd`-click on something like a dependency or `<parent>` block and have the corresponding POM opened. Another similar feature was clicking on a `${property}` and being directed to the point where it's defined (including parent POMs).  

Now all of this has disappeared, despite having restarted a completely new workspace, Eclipse has become a buggy monster and I'm considering switching to another IDE, after about 20 years.

**Comment by mickaelistria** [comment]
Can you please share some minimal configuration (pom.xml, Maven settings...) to reproduce this issue?

**Comment by rombert** [comment]
I ran the tests with no Maven settings.xml . I could not reproduce the problem on a fresh workspace. I am not sure what can cause this kind of behaviour but I'm willing to try various things, in case anyone has ideas.

The pom.xml I used is from https://github.com/apache/sling-org-apache-sling-resourceresolver/ , but since it does not exhibit the problem on an empty workspace it probably does not matter too much.

**Comment by marco-brandizi** [comment]
I've enabled the DEBUG level in the Eclipse log, but the only thing I could notice is:

```log
2022-06-13 22:46:27.414 eclipse[36586:551087] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-13 22:46:27.414 eclipse[36586:551087] nil host used in call to allowsAnyHTTPSCertificateForHost:
2022-06-13 22:46:27.414 eclipse[36586:551087] nil host used in call to allowsSpecificHTTPSCertificateForHost
2022-06-13 22:46:27.414 eclipse[36586:551087] nil host used in call to allowsAnyHTTPSCertificateForHost:
```

Moreover, now I can occasionally get autocompletion for XML tags, eg, if I start typing `<dep`, it proposes me dependency, but after sometime it stops working again and shows "Computing proposals 0%".

I've never been able to click on a dependency, or on a `<parent>` and open the corresponding POM, a feature that was available in the past. This is still possible from the overview or the dependency hierarchy view (with double click), double doesn't work on the dependencies view.

So, it seems a problem with the content assist system. By the way, I can't find anywhere in the Eclipse preferences a way to inspect/change content assist options for m2e (settings for other editors have dedicated subsection, [example](https://i.stack.imgur.com/jhJEC.jpg))

**Comment by CarlosMOGoncalves** [comment]
Hello,
I would just like to second this issue.
There has been some instability since the older editor was replaced by the current one.
I am confident it was a good move, but it still has some issues. I have the exact same issues as reported above very frequently.

Sometimes it won't show any info when hovering over a dependency. Some other time I will CTRL-Click on a dependency to check its POM and it will just freeze. Eventually it all starts working decently.

For example, just ran some tests on my environement, just updated from 2022-03 to -06.
Whenever I start/restart Eclipse and immeadiately try to hover over one pom dependency it will do nothing and just throw this exception;

```
!ENTRY org.eclipse.lsp4e 4 0 2022-07-05 12:34:09.626
!MESSAGE TimeoutException
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverRegion(LSPTextHover.java:150)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverRegion(CompositeTextHover.java:101)
	at org.eclipse.jface.text.TextViewerHoverManager.computeInformation(TextViewerHoverManager.java:128)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1101)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager$MouseTracker.mouseHover(AbstractHoverInformationControlManager.java:511)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.lsp4e 4 0 2022-07-05 12:34:10.142
!MESSAGE TimeoutException
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:73)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

Eventually, it does start behaving properly.

Then there are some nagging issues, like this:
when hovering over a dependency, in order to get the info tootlip, it won't load it if the version is a replacement variable, such as below.
```
<dependency>
    <groupId>org.owasp.encoder</groupId>
    <artifactId>encoder</artifactId>
    <scope>compile</scope>
    <version>${owasp-encoder-version}</version>
</dependency>
```

However, it will properly load the tooltip even if there is no version stated (e.g. it has its dependency version on a parent pom). But it won't show you which version is it, which I think is really important so that you don't have to check its parent for it.

![M2E](https://user-images.githubusercontent.com/2636004/177320816-cd117249-053b-4e42-a83e-15986414df63.jpg)


All of this in version **1.20.1.20220227** (latest)

**Comment by mickaelistria** [comment]
@CarlosMOGoncalves Please report individual issues for seprate problems.

**Comment by marco-brandizi** [comment]
I've just installed Eclipse 4.25.0 and the versions of m2e reported in the figure below (auto-installed after having loaded the existing workspace).

The POM editor still has this bug regarding auto-completion.

![image](https://user-images.githubusercontent.com/534529/203605509-20cf936c-2e92-4c35-a725-b793b1b3e011.png)

**Comment by ahoehma** [comment]
I can confirm the reported issue(s) too.

For me the assistant in tab "pom.xml" in "Maven POM Editor" doesn't do anything.
No tooltips with version. No content assist for pom elements, no artifacts resolving, no version. Just nothing :)

Nothing in eclipse error-log.

I try to stay up2date with the bleeding edge version

![image](https://user-images.githubusercontent.com/548214/210974918-d20bfec2-cbe0-4ab0-81aa-c7abb1c2cb02.png)

**Comment by HannesWell** [comment]
> My "XML" Language Server was disabled .. so there was no support for pom.xml :( Now I enabled this server and everything is fine. No hanging etc.

You can leave it there. As you like. Maybe just make a bit more clear, what the initial message was and what is a new comment (only because it just changed so much).

Nevertheless unfortunately I still regularly experience this on Windows sometimes more sometimes less as reported in https://github.com/eclipse-m2e/m2e-core/issues/909. But this is a LanguageServer or LemMinX issue. Unfortunately at M2E we cant actually do anything (I know) about that.

**Comment by ahoehma** [comment]
> I can confirm the reported issue(s) too.
> 
> For me the assistant in tab "pom.xml" in "Maven POM Editor" doesn't do anything. No tooltips with version. No content assist for pom elements, no artifacts resolving, no version. Just nothing :)
> 
> Nothing in eclipse error-log.
> 
> I try to stay up2date with the bleeding edge version
> 
> ![image](https://user-images.githubusercontent.com/548214/210975031-deadf830-9ce9-41f1-8288-b2dbf966a3fa.png)

Invalid report from my side! :D

My "XML" Language Server was disabled .. so there was no support for pom.xml :(
Now I enabled this server and everything is fine. No hanging etc.

**Comment by mickaelistria** [comment]
I recently fixed an important issue in LSP4E, causing constant heavy and useless CPU usage than necessary in some cases. Would you mind trying latest snapshots of LSP4E to see if it makes things better for the pom.xml + SonarLint story?

**Comment by LorenzoBettini** [comment]
@mickaelistria I'd love to!
Could you please provide the update site to ensure I'm using the right one?

**Comment by LorenzoBettini** [comment]
Sorry if I bother you again. Adding that update site does not trigger any update... should I manually force the installation of LSP4J bundles?

**Comment by mickaelistria** [comment]
There may be some other incompatibility... Try browsing the site from the Install New Software dialog and selecting the LSP4E bundles explicitly.

**Comment by LorenzoBettini** [comment]
@mickaelistria it seems to work, maybe because installing the nightly versions of lsp4j doesn't make SonarLint start at all, maybe due to an incompatibility. So I cannot tell you whether this solves the problem. In some sense it does: it simply inhibits SonarLint ;)

**Comment by LorenzoBettini** [comment]
@mickaelistria on a second attempt, I managed to install the snapshot version of LSP4E and SonarLint. Things seem to have improved a lot!

**Comment by gnl42** [comment]
I'm seeing this with 2023-06. Very annoying
