### ISSUE TITLE
Reference to undefined variable artifactId.concat(".")

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#777]
I got this when trying to run a Archetype Build:

```
Exception while getting configuration attribute M2_PROPERTIES
org.eclipse.core.runtime.CoreException: Reference to undefined variable artifactId.concat(".")
	at org.eclipse.core.internal.variables.StringSubstitutionEngine.resolve(StringSubstitutionEngine.java:263)
	at org.eclipse.core.internal.variables.StringSubstitutionEngine.substitute(StringSubstitutionEngine.java:195)
	at org.eclipse.core.internal.variables.StringSubstitutionEngine.performStringSubstitution(StringSubstitutionEngine.java:91)
	at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:547)
	at org.eclipse.core.internal.variables.StringVariableManager.performStringSubstitution(StringVariableManager.java:347)
	at org.eclipse.m2e.internal.launch.LaunchingUtils.substituteVar(LaunchingUtils.java:30)
	at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.getProperties(MavenLaunchDelegate.java:197)
	at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.getProgramArguments(MavenLaunchDelegate.java:147)
	at org.eclipse.m2e.internal.launch.MavenLaunchDelegate.launch(MavenLaunchDelegate.java:96)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:803)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1021)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1224)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by laeubi** [comment]
This is cause by the following Archetype:

![grafik](https://user-images.githubusercontent.com/1331477/173740133-1b523371-d859-49f0-9edd-bfeba1943c81.png)

I think we should simply skip failed variable substitution here and use the raw value then.
