### ISSUE TITLE
vanilla install of eclipse 2022-06 m2e xml editor broken

### ISSUE THREAD

**Issue by jeacott1** [eclipse-m2e/m2e-core#861]
Hi all,
 so idk what is happening here.
 I upgraded from 2022-03 to 2022-06.
When I load a pom.xml, the maven editor opens, but the xml and Effective pom view look very different than previous versions.
the syntax highlighting etc looks like a normal xml editor instead of the usual pom editor.
none of the hover and show ${var} variable values works, and not even select Ctrl+I will indent - it just clears the selection.
to check it wasnt something off with my setup, 
I downloaded eclipse-jee-2022-06-R-win32-x86_64.zip, unpacked it, started it, created a new workspace and a new maven project.
nothing more - still broken. 

my maven xml editor looks like this:
![image](https://user-images.githubusercontent.com/16600100/181210138-105fdf77-f096-4ea7-a3ab-9389aa79ce02.png)

where it has always looked like this in the past:
![image](https://user-images.githubusercontent.com/16600100/181212248-a472cb9d-b528-421f-9ad3-ec599a0760ef.png)

I tried opening the new workspace with an older eclipse, and while the editor colours were of the new kind, at least the shortcuts worked and the ${variable} hovers work.

is there something messed up with the new workspace format and the m2e xml editor?

thanks.

**Comment by mickaelistria** [comment]
All this is expected to work. Can you please check in your <workspace>/.metadata/.log file whether some related information is logged?

**Comment by jeacott1** [comment]
@mickaelistria thanks for the response. 
I've deleted my .eclipse and .p2 directories now too, and created a fresh workspace just to be sure.
that seems to have helped a little - the xml editor still looks wrong, and ctrl+i etc still doesnt work, but the variable hovers are back.

I do have errors in the log.

summary log
```
!SESSION 2022-07-28 09:58:00.213 -----------------------------------------------
eclipse.buildId=4.24.0.I20220607-0700
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_AU
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data C:\Users
...
!ENTRY org.eclipse.jface 2 0 2022-07-28 09:58:04.377
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2022-07-28 09:58:04.377
!MESSAGE A conflict occurred for CTRL+SHIFT+T:
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@21e15093,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@62cf873a,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2022-07-28 09:58:04.377
!MESSAGE A conflict occurred for ALT+SHIFT+R:
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@21b3d356,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+R,
	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
		Rename the selected item,
		Category(org.eclipse.ui.category.file,File,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@294b045b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.egit.ui 2 0 2022-07-28 09:58:12.117
...

!ENTRY org.eclipse.wildwebdeveloper.xml 4 0 2022-07-28 09:58:59.621
!MESSAGE Error while getting URI 'platform:/plugin/org.eclipse.persistence.moxy/org/eclipse/persistence/jaxb/eclipselink_oxm_2_5.xsd' from plugin 'org.eclipse.jpt.common.eclipselink.core' : /org/eclipse/persistence/jaxb/eclipselink_oxm_2_5.xsd
!STACK 0
java.io.FileNotFoundException: /org/eclipse/persistence/jaxb/eclipselink_oxm_2_5.xsd
	at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
	at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
	at java.base/java.net.URL.openConnection(URL.java:1094)
	at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:115)
	at org.eclipse.core.internal.boot.PlatformURLConnection.getURLAsLocal(PlatformURLConnection.java:240)
	at org.eclipse.core.internal.runtime.PlatformURLConverter.toFileURL(PlatformURLConverter.java:37)
	at org.eclipse.core.runtime.FileLocator.toFileURL(FileLocator.java:263)
...
!ENTRY org.eclipse.lsp4e 4 0 2022-07-28 09:59:05.225
!MESSAGE BadLocationException
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1163)
...
!ENTRY org.eclipse.lsp4e 4 0 2022-07-28 09:59:05.227
!MESSAGE BadLocationException
!STACK 0
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
	at org.eclipse.jface.text.TreeLineTracker.getLineInformation(TreeLineTracker.java:1163)
	at org.eclipse.jface.text.AbstractLineTracker.getLineInformation(AbstractLineTracker.java:137)
	at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.getLineInformation(BasicStructuredDocument.java:1461)
	at org.eclipse.lsp4e.LSPEclipseUtils.toOffset(LSPEclipseUtils.java:164)
```

these errors seem related to this issue: https://github.com/eclipse/wildwebdeveloper/issues/802

 I'm not sure if they would affect m2e though?

**Comment by jeacott1** [comment]
@mickaelistria 
ok -So I have narrowed this down.
I made fresh installs of various versinos with fresh workspaces and cleared project files/settings etc - re-imported existing maven projects.
the last working version was eclipse-jee-2021-09-R-win32-x86_64.zip
the first version that ctrl+i,  ctrl+shift+/ etc stopped working was version eclipse-java-2021-12-R-win32-x86_64

I'm not sure when the editor look changed (colours) but all these have the newer look.
I'm guessing that upgrading vs fresh install has kept me (until now)  with the older colour format and other things working until my most recent update attempt to 2022-06.

**Comment by mickaelistria** [comment]
Do you use Dali/JPA ?

**Comment by jeacott1** [comment]
@mickaelistria  - I actually tried the jee and the plain java versions - both are broken - you'll notice above that its the eclipse-java version I mentioned that is dead (the jee version is too).
I do use JPA, although I rarely use the eclipse support.
My test project in my brand new test workspace was a vanilla architype generated project, no dependencies or support required for anything except maven/java.

to reproduce -  download and unzip eclipse-java-2021-12-R-win32-x86_64. 
run it.
let it create a new workspace.
then either copy in and import an existing trivial maven project or use eclipse to create one.
open the pom.xml - try crtl+i (or any other normal control).



.

**Comment by glhez** [comment]
Hello,
I had a similar trouble with an Oomph based install of 2022-06 and m2e: there was no longer any Language Servers available in Preferences. Without them, you won't have anything: I had the hunch to visit Eclipse logs found somewhere in my installation: `%ECLIPSE_INSTALL_HOME%\configuration\*.log`

```
!ENTRY org.eclipse.wildwebdeveloper.xml 4 0 2022-07-27 12:21:50.004
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper.xml [972]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

Some plugin is requiring Java 17 to work: I switched from Java 11 to Java 17 and the language server were available again.

**Comment by jeacott1** [comment]
@glhez nice theory, but out of the box install includes and uses its own java 17 jre.
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.3.v20220515-1416/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=11

**Comment by glhez** [comment]
@jeacott1 ok. Well, at least, if other get a similar problem this might help them.

**Comment by deslauriersp** [comment]
it seems that the m2e now uses the "structured text editor" instead of the XML editor
there are no more XML editor included with default install

the xml comments seems to be completly broken in the structured text editor
I have installed the eclipse xml editor plugin (from WTP) which works well
but i can't (or don't know how) tell m2e pom editor to use the XML editor

**Comment by deslauriersp** [comment]
https://git.eclipse.org/c/m2e/m2e-core.git/commit/?id=47e4ff869009a69138d70042fcfcc89047cdfe04

this suggest that the "MavenStructuredEditor" is configurable:

```
"Use GenericEditor as fallback editor if MavenStructuredEditor couldn't
be loaded via extension point"
```

**Comment by mickaelistria** [comment]
>   the xml comments seems to be completly broken / other XML editor feature aren't implemented

Please report dedicated issues about specific bugs or missing features.

**Comment by deslauriersp** [comment]
As per m2e 2.0.1 release note : **Removed legacy WTP-SSE based editor**
https://github.com/eclipse-m2e/m2e-core/blob/master/RELEASE_NOTES.md#removed-legacy-wtp-sse-based-editor
```
The legacy textual editor is removed as it doesn't receive enough update/maintenance. The editor based on Generic Editor and LemMinX-Maven is now the only one distributed by m2e.
```
We have lost the WTP xml editor integration. Maybe the "code completion" works, but as for every thing XML, it's a disaster.

From the menu (and the keyboard shorcut), when I choose "block comment" it does not nothing.

If I do a line comment, the closing tag "-->" goes to a second line, an XML compilation exception is reported, and I loose the "line numbers" on the left hand side of the editor.   

Formatting semi-works, indentation is wrong.

**Comment by deslauriersp** [comment]
> > the xml comments seems to be completly broken / other XML editor feature aren't implemented
> 
> Please report dedicated issues about specific bugs or missing features.

The tile of this issue is "xml editor broken"
I think this is what we are talking about

**Comment by deslauriersp** [comment]
And this seems to have nothing to do with m2e. Editing any XML file with the generic editor is a catastrophy.

**Comment by mickaelistria** [comment]
"broken" is not a sufficiently precise term to be actionable. Please refine what are the specific things that are not working, details to reproduce the issue from a vanilla installation, details about the environment...

**Comment by deslauriersp** [comment]
I am sorry I wasn't specific enough

> From the menu (and the keyboard shorcut), when I choose "block comment" it does not nothing.
> 
> If I do a line comment, the closing tag "-->" goes to a second line, invalid XML reported, an eclipse exception pops-up, and I loose the "line numbers" on the left hand side of the editor.

What I meant was :

A) download the 2022‑09 for java dev, on windows.

B) I try using block comment... (using menu or shortcut key) it doesn't do anything.

C) I add a comment   using menu-> source -> line comment (or keyboard shortcut ctrl-shift-c)
for me, I get a xml validation error, eclipse reports an exception, and the line numbers in the editor disappeared.

short of typing the comment by hand and formatting everything by hand, XML comments, whatever use case, don't seem to work.

same results within the source tab of the pom editor (m2e) or to any XML file with the "generic editor".

as I said, it doesn't look like a m2e issue in the end. just that m2e is now integrated with an editor which xml editing functions seems to have issues. 

same results with widows binary on STS 4.16.0, STS 4.16.1, eclipse 2022‑09 for java dev, all vanilla installs

**Comment by jeacott1** [comment]
@deslauriersp yep - its all quite useless now. idk how eclipse expect to be taken seriously when key parts of the ide experience keep being broken/lost. I love eclipse - I loathe intellij idea, but this kind of thing does make it harder to justify the effort.

**Comment by mickaelistria** [comment]
I've opened https://github.com/eclipse/wildwebdeveloper/issues/979 about block comments.

> C) I add a comment using menu-> source -> line comment (or keyboard shortcut ctrl-shift-c) for me, I get a xml validation error, eclipse reports an exception, and the line numbers in the editor disappeared.

I cannot reproduce it.

**Comment by deslauriersp** [comment]
thanks for your efforts. I will try to open a specific issue from XML comments, with MD5 checksum, demo maven projects, to import as "import existing maven project"
