### ISSUE TITLE
apt preferences are broken on latest m2e release

### ISSUE THREAD

**Issue by martinlippert** [eclipse-m2e/m2e-core#896]
It looks like the latest m2e release contains a broken version of the apt ui bundle.

The problem is based on this commit:
https://github.com/eclipse-m2e/m2e-core/commit/8b876a6748d8858578ee5894c40a872affc0e052

It changed the return types of many methods. One of those methods is used here:
https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.apt.ui/src/org/eclipse/m2e/apt/ui/preferences/AnnotationProcessingSettingsPage.java#L290

While the source is still compatible with the change made to the return type (from array to collection), the compiled code is not compatible and breaks with:

```
java.lang.NoSuchMethodError: 'org.eclipse.m2e.core.project.IMavenProjectFacade[] org.eclipse.m2e.core.project.IMavenProjectRegistry.getProjects()'
	at org.eclipse.m2e.apt.ui.preferences.AnnotationProcessingSettingsPage.getImpactedProjects(AnnotationProcessingSettingsPage.java:290)
	at org.eclipse.m2e.apt.ui.preferences.AnnotationProcessingSettingsPage.updateImpactedProjects(AnnotationProcessingSettingsPage.java:245)
	at org.eclipse.m2e.apt.ui.preferences.AnnotationProcessingSettingsPage.performOk(AnnotationProcessingSettingsPage.java:205)
	at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:905)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:461)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

It looks like the bundle for m2e.apt.ui got compiled before that change (has a bundle version of July 3 whereas the return type changed with a commit on July 5) and ships that version as part of the latest m2e release, instead of an updated, recompiled version that contains the right code for the changed return type.

To reproduce:
Go to the preferences of m2e APT, change something, hit apply button. Error shows up in the Error Log view.

**Comment by kdvolder** [comment]
More detailed reproduction steps are in the ticket martin linked above. I am repeating them here for convenience:

- start with a clean / new workspace
- open Preferences
- Go to Maven >> Annotation Processing
- Change annotation processing mode from 'Do not ...' to 'Automatically ...' 
- Click 'Apply And Close'
- Click 'Yes' on the popup that asks whether you want to rebuild projects after the change.

Observe:
- error popup 
![image](https://user-images.githubusercontent.com/1002156/189386139-166b8027-3470-49ed-b3c3-648381d79d6f.png)
- also the error is in the Eclipse error log.

**Comment by HannesWell** [comment]
> It looks like the bundle for m2e.apt.ui got compiled before that change (has a bundle version of July 3 whereas the return type changed with a commit on July 5) and ships that version as part of the latest m2e release, instead of an updated, recompiled version that contains the right code for the changed return type.

I have reproduced this issue and your explanation totally makes sense. Tycho's p2-plugin even showed a warning about that, but since it is just a warning (and warnings from that plug-in are very common) this is was not noticed:
```
[INFO] --- tycho-p2-plugin:2.7.4:p2-metadata (p2-metadata) @ org.eclipse.m2e.apt.ui ---
[WARNING] MavenProject: org.eclipse.m2e:org.eclipse.m2e.apt.ui:2.0.0-SNAPSHOT @ /home/jenkins/agent/workspace/m2e_master/org.eclipse.m2e.apt.ui/.tycho-consumer-pom.xml: baseline and build artifacts have same version but different contents
   no-classifier: different
      META-INF/ECLIPSE_.RSA: present in baseline only
      META-INF/ECLIPSE_.SF: present in baseline only
      org/eclipse/m2e/apt/ui/preferences/AnnotationProcessingSettingsPage.class: different
   classifier-sources: different
      META-INF/ECLIPSE_.RSA: present in baseline only
      META-INF/ECLIPSE_.SF: present in baseline only

[INFO] MavenProject: org.eclipse.m2e:org.eclipse.m2e.apt.ui:2.0.0-SNAPSHOT @ /home/jenkins/agent/workspace/m2e_master/org.eclipse.m2e.apt.ui/.tycho-consumer-pom.xml
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]
```

A simple enforced qualifier update will solve this.

**Comment by martinlippert** [comment]
Is there a chance to get a new release version of m2e out that includes this fix sometime soon?

**Comment by mickaelistria** [comment]
> Is there a chance to get a new release version of m2e out that includes this fix sometime soon?

Done. https://github.com/eclipse-m2e/m2e-core/releases/tag/2.0.5

**Comment by martinlippert** [comment]
Awesome!!! Many many thanks!!!

**Comment by HannesWell** [comment]
> > Is there a chance to get a new release version of m2e out that includes this fix sometime soon?
> 
> Done. https://github.com/eclipse-m2e/m2e-core/releases/tag/2.0.5

Please note that we keep [m2e/releases/latest](https://download.eclipse.org/technology/m2e/releases/latest) to be [m2e/releases/2.0.1](https://download.eclipse.org/technology/m2e/releases/2.0.1/) due to https://github.com/eclipse-m2e/m2e-core/issues/887 until Eclipse 4.25 is released on Wednesday.

In general you can also use M2E's snapshot repos that always contain the latest master-branch state.
There are
- https://download.eclipse.org/technology/m2e/snapshots/latest/
- https://download.eclipse.org/technology/m2e/snapshots/<version-under-development>/
If you don't want to stay on snapshots forever you can use the version-specfic repo that will vanish after the corresponding release.
