### ISSUE TITLE
An internal error occurred during: "Updating Maven Project"

### ISSUE THREAD

**Issue by glassfox** [eclipse-m2e/m2e-core#908]
After upgrade to eclipse 2022-09 thrown the following exception:

An internal error occurred during: "Updating Maven Project".
'org.eclipse.core.resources.IProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getProject()'

**Comment by mickaelistria** [comment]
Can you please provide minimal steps to reproduce from a fresh workspace?

**Comment by glassfox** [comment]
Workspace with many java projects.

Following log:
```
!ENTRY org.eclipse.core.jobs 4 2 2022-09-13 14:27:27.430
!MESSAGE An internal error occurred during: "Updating Maven Project".
!STACK 0
java.lang.NoSuchMethodError: 'org.eclipse.core.resources.IProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getProject()'
	at org.jboss.tools.maven.apt.internal.AbstractAptProjectConfigurator.configureRawClasspath(AbstractAptProjectConfigurator.java:154)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.invokeJavaProjectConfigurators(AbstractJavaProjectConfigurator.java:227)
	at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:186)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:125)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:475)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:469)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:413)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:407)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1093)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:338)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment]
Seems very similar to https://github.com/eclipse-m2e/m2e-core/issues/896
Can you please try installing snapshots from https://download.eclipse.org/technology/m2e/snapshots/latest and report whether this fixes your issue?

**Comment by glassfox** [comment]
not helped. same error

**Comment by mickaelistria** [comment]
Sorry, I didn't notice. jbosstools variant of m2e-apt must be uninstalled. It's not compatible with newer m2e and the capability of the jbosstools-m2e-apt support were merged in directly m2e project so the extra feature is not necessary.

**Comment by glassfox** [comment]
I have installed "m2e-apt 1.5.4"
I required it for code generation. Uninstall it ?

**Comment by mickaelistria** [comment]
m2e-apt from m2e repo is ok; the one from jbosstools ( `org.jboss.tools.maven.apt` ) is not. The later must be removed.

**Comment by glassfox** [comment]
jbosstools I do not have.

**Comment by mickaelistria** [comment]
Your stack trace says you have.

**Comment by glassfox** [comment]
Only if a part of "m2e-apt 1.5.4". Ill try to remove

**Comment by mickaelistria** [comment]
Thanks.
