### ISSUE TITLE
Unknown referenced nature: org.eclipse.m2e.core.maven2Nature

### ISSUE THREAD

**Issue by johnthad** [eclipse-m2e/m2e-core#911]
Eclipse just updated to 2022-09 (4.25.0). It will no longer open my principal workspace which had one open project that uses Maven. Instead I get the Overview page and a problem alert `An internal error occurred during: "Loading referenced grammars". com/ibm/icu/util/StringTokenizer`,

I can switch to a different workspace with several different Maven projects. However there each tell me "Unknown referenced nature: org.eclipse.m2e.core.maven2Nature". Maven does not appear in either the IDE or project Preferences dialogs.

I have tried installing both release/latest and snapshot/latest. Neither work.

Oops! Forgot to add:

I am running Eclipse under OpenJDK 11 (amazon-corretto-11.0.16.9.1-macosx-x64.pkg). The projects use OpenJDK 8 (amazon-corretto-8.322.06.1-macosx-x64.pkg). I'm using a Mac Mini with macOS Catalina (10.15.7).

**Comment by mickaelistria** [comment]
Can you please check your `<workspace>/.metadata/.log` file for possible additional details?

**Comment by johnthad** [comment]
Thanks for the quick reply. In the log I find 

`Caused by: java.lang.ClassNotFoundException: com.ibm.icu.util.StringTokenizer cannot be found by org.eclipse.wst.xml.core_1.2.600.v202207121749`

I do not find the terms `natures` or `maven2Nature` in the log.

What else should I look for?

**Comment by johnthad** [comment]
Eclipse just asked me to install some updates, apparently from snapshots (from the dates 20220912). I did, with similar results. At line 300 of the log I see the error below. There are other m2e error in the log.

`@ 300

!ENTRY org.eclipse.equinox.p2.core 4 0 2022-09-14 13:33:59.855
!MESSAGE Provisioning exception
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: No repository found at http://download.eclipse.org/technology/m2e/releases/.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.fail(CachingRepositoryManager.java:386)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:277)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Artifact.loadRepository(CachingRepositoryManager.java:585)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:131)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:125)
	at org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository.load(CompositeArtifactRepository.java:496)
	at org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository.addChild(CompositeArtifactRepository.java:177)
	at org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository.<init>(CompositeArtifactRepository.java:99)
	at org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepositoryFactory.load(CompositeArtifactRepositoryFactory.java:120)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.factoryLoad(ArtifactRepositoryManager.java:92)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
	at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:446)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager.loadRepository(CachingRepositoryManager.java:229)
	at org.eclipse.oomph.p2.internal.core.CachingRepositoryManager$Artifact.loadRepository(CachingRepositoryManager.java:585)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:131)
	at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:125)
	at org.eclipse.equinox.p2.engine.ProvisioningContext.getLoadedRepository(ProvisioningContext.java:189)
	at org.eclipse.equinox.p2.engine.ProvisioningContext.getLoadedArtifactRepositories(ProvisioningContext.java:163)
	at org.eclipse.equinox.p2.engine.ProvisioningContext.getArtifactRepositories(ProvisioningContext.java:149)
	at org.eclipse.equinox.internal.p2.engine.phases.Sizing.completePhase(Sizing.java:98)
	at org.eclipse.equinox.internal.p2.engine.Phase.postPerform(Phase.java:254)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:105)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:80)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:48)
	at org.eclipse.equinox.internal.p2.ui.ProvUI.getSize(ProvUI.java:266)
	at org.eclipse.equinox.internal.p2.ui.dialogs.SizeComputingWizardPage$1.run(SizeComputingWizardPage.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 1000 2022-09-14 13:33:59.855
!MESSAGE No repository found at http://download.eclipse.org/technology/m2e/releases/.
`

**Comment by laeubi** [comment]
I noticed the same when upgrading a previous install of Eclipse. even though m2e is installed, it seems it can't be used anymore, all projects lost their maven nature and classpath container.

**Comment by mickaelistria** [comment]
The issue is probably that the installation uses newer/official icu bundle while WST.XML still references classes of the Orbit's fork, that happened to have been removed. As a result, wst.xml fails to be loaded in the IDE, and the same thing happens to everything that depends on it, including m2e.
Issue should be reported to wst.xml project, so the standard StringTokenizer from Java API is used instead.

**Comment by mickaelistria** [comment]
Closing it here as the issue and fix don't belong to m2e.

**Comment by laeubi** [comment]
@mickaelistria m2e is stop working completely, and even if it caused by a library used by m2e I think it should be tracked / pushed forward by m2e as well, e.g can we export a surrogate, add a missing dependency or something so not *Everyone is broken* that upgrades to a new m2e release!

**Comment by laeubi** [comment]
> Issue should be reported to wst.xml project, so the standard StringTokenizer from Java API is used instead.

As you seem to have the best knowledge about the possible root cause, would it be possible to report the issue there and link it here fro reference?

**Comment by mickaelistria** [comment]
I'll need more details about the stacktrace to be sure about how to best report/troubleshoot it.

> In the log I find Caused by: java.lang.ClassNotFoundException: com.ibm.icu.util.StringTokenizer cannot be found by org.eclipse.wst.xml.core_1.2.600.v202207121749

Can you please share your full .log file?

**Comment by laeubi** [comment]
@johnthad can you please check what JVM is used to **run** you eclipse instance? I just noticed that in my case the problem seem that a while back I set it to Java 11 but m2e 2.x now strictly requires a Java 17 JVM so maybe the 

> Caused by: java.lang.ClassNotFoundException: com.ibm.icu.util.StringTokenizer cannot be found by

Is just a [red hering](https://en.wikipedia.org/wiki/Red_herring)?

**Comment by kwin** [comment]
There is already https://bugs.eclipse.org/bugs/show_bug.cgi?id=580367

**Comment by mickaelistria** [comment]
Can you please share the result of `ls plugins/` ?

**Comment by deepakab03** [comment]
Facing the same issue after Eclipse update - M2E has disappeared and I get the same missing Maven nature issue.. 
As an aside I am using an external JDK configured int he eclipse.ini file via the -vm parameter and not the Eclipse embedded JRE. This is so that Eclipse can access our org repository, it is not able to with the embedded option

How do I get it M2E back?

**Comment by mickaelistria** [comment]
@johnthad This is not the list of plugins, the content of this metadata folder isn't what I need. What I'm looking for is the list of plugins on disk, in the plain `plugins` folder of the installation, besides the binary.

**Comment by johnthad** [comment]
Sorry. Do you mean from the ~/.p2/pool/ folder? Attached is `ls /Users/thad/.p2/pool/plugins > ~/Downloads/plugins.txt`

[plugins.txt](https://github.com/eclipse-m2e/m2e-core/files/9578422/plugins.txt)

**Comment by mickaelistria** [comment]
Ah, it's using the installer and p2 pool, that makes things a bit more complex.
So let's try something else: in Help > About > Installation Details > Plugins, can you please list what remains when you filter `icu` ?

**Comment by johnthad** [comment]
Unicode, Inc.  ICU4J       67.1                   com.ibm.icu
    Eclipse Orbit  ICU4J Base  58.2.0.v20170418-1837  com.ibm.icu.base

**Comment by mickaelistria** [comment]
OK, so the issue is that Webtools binds to the `com.ibm.icu.base` instead of `com.ibm.icu` because its `Import-Package: com.ibm.icu` directive matches the Export-Package of both.
com.ibm.icu.base is a very bad bundle and it was abandoned and not shipped any longer with Eclipse IDE sine 2020. It should be plainly remove. Every installation that uses it is vulnerable to this issue. A solution is to simply delete it maybe.

**Comment by johnthad** [comment]
I'm willing to try, but how? There's no remove option in that plugins list. Do I shutdown Eclipse and run `rm /.p2/pool/plugins/com.ibm.icu.base_58.2.0.v20170418-1837.jar`? It's the only `com.ibm.icu.base` I see in `/.p2/pool/plugins`. (There are none in the workspace).

Should I remove the Eclipse Orbit sites from "Available Software Sites" first (to keep it from coming back)?

**Comment by mickaelistria** [comment]
>  Do I shutdown Eclipse and run rm /.p2/pool/plugins/com.ibm.icu.base_58.2.0.v20170418-1837.jar? 

That's the idea, but just rename it first so it case things are more broken, you can at least restore to current state.
Note that maybe there is some other plugin you've installed that requires it and then may stop working because this bundle is not available...

> Should I remove the Eclipse Orbit sites from "Available Software Sites" first (to keep it from coming back)?

You can remove the old ones and just keep the most recent.

**Comment by johnthad** [comment]
No joy. I'm moved `com.ibm.icu.base_58.2.0.v20170418-1837.jar` but now instead of the normal Welcome tab I get the Welcome tab shows error below.

So maybe we must wait on the fix @kwin pointed out from Eclipse (com.ibm.icu.base_58.2.0.v20170418-1837.jar)?

    java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.intro.IIntroPart.getTitle()" because "this.introPart" is null
      at org.eclipse.ui.internal.ViewIntroAdapterPart.init(ViewIntroAdapterPart.java:180)
      at org.eclipse.ui.internal.ViewReference.initialize(ViewReference.java:129)
      at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:344)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
      at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
      at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
      at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
      at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:403)
      at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:330)
      at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
      at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
      at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
      at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
      at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:544)
      at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:528)
      at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
      at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
      at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1209)
      at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
      at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
      at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
      at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
      at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
      at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
      at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:658)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
      at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1083)
      at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
      at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
      at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
      at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
      at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
      at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
      at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
      at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
      at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
      at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:36)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
      at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
      at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
      at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by johnthad** [comment]
With or without `com.ibm.icu.base_58.2.0.v20170418-1837.jar`, if I close the Welcome tab, the Maven nature is back. However running Maven -> Update Project one my one project show the error:

    An internal error occurred during: "Updating Maven Project".
    'org.apache.maven.project.MavenProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getMavenProject()'

**Comment by laeubi** [comment]
### As mentioned before, please check first that your Eclipse IDE **is running with Java 17**!

The other issues might be annoying and maybe they influence some of m2e functionality, but that m2e completely stop working is  most likely one uses a 
```
-vm
/some/path/to/java11/bin
```

**Comment by johnthad** [comment]
> ### As mentioned before, please check first that your Eclipse IDE **is running with Java 17**!
> 
> 
> 
> The other issues might be annoying and maybe they influence some of m2e functionality, but that m2e completely stop working is  most likely one uses a 
> 
> ```
> 
> -vm
> 
> /some/path/to/java11/bin
> 
> ```

Yes. I am running Eclipse with Java 17 (Amazon Corretto).

**Comment by laeubi** [comment]
Can you clear the error log and restart eclipse then looking for any other errors?

**Comment by johnthad** [comment]
> Can you clear the error log and restart eclipse then looking for any other errors?

There is a log from a startup attached to a comment above, `eclipse-v4_25-log.txt`, (https://github.com/eclipse-m2e/m2e-core/issues/911#issuecomment-1248154810). 

I am away from the office with that machine today. I've been unable to launch Eclipse via remote desktop from here; it crashes. I don't want to mess up the working Eclipse on my Mac Mini here, but I'll see if I can install a fresh copy of 2022-09 to a different location. Otherwise I'll pursue this further on Monday.

**Comment by johnthad** [comment]
Success! I have Eclipse 4.25/2022-09 working here (on a Mac Mini). I launched 4.24 with Java 17 and ran the updates. There was a hiccup when 4.25 first opened--attempting to rebuild my project with Maven -> Update Project gave an error. From the log, 

    !ENTRY org.eclipse.core.jobs 4 2 2022-09-16 07:55:27.861
    !MESSAGE An internal error occurred during: "Updating Maven Project".
    !STACK 0
    java.lang.NoSuchMethodError: 'org.apache.maven.project.MavenProject org.eclipse.m2e.core.project.configurator.ProjectConfigurationRequest.getMavenProject()'
      at com.google.gdt.eclipse.maven.configurators.AbstracMavenProjectConfigurator.configure(AbstracMavenProjectConfigurator.java:74)
      at com.google.gdt.eclipse.maven.configurators.MavenProjectConfigurator.configure(MavenProjectConfigurator.java:124)
      at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:125)
      at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:475)
      at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
      at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
      at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:469)
      at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$4(ProjectConfigurationManager.java:413)
      at java.base/java.util.Collection.removeIf(Collection.java:576)
      at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:407)
      at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:339)
      at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
      at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
      at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
      at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1093)
      at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:338)
      at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
      at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
      at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

The UI offered 2 options to correct the problem. I didn't copy those down, but it was something like using internal or external resources. I chose internal, and the project rebuilt. I was able to launch the project with Tomcat 9 and access it with cURL. The projects in my other Maven workspace rebuilt without error.

When I'm in my office Monday, I believe I will just do a clean install of Eclipse there (and use the update sites list from this Mac).

For completeness, here is information from About Eclipse regarding the m2e installed software and the `com.ibm.icu` plugin.

Installed sofware, filtered for m2e

    Eclipse IDE for Java Developers 4.25.0.20220908-1200  epp.package.java  Eclipse Packaging Project
      M2E - Maven Integration for Eclipse 2.0.4.20220904-1703 org.eclipse.m2e.feature.feature.group Eclipse.org - m2e
      M2E - POM Editor using LemMinX language server (includes Incubating components) 2.0.0.20220729-1256 org.eclipse.m2e.lemminx.feature.feature.group Eclipse.org - m2e
      M2E - SLF4J over Logback Logging  2.0.0.20220717-0848 org.eclipse.m2e.logback.feature.feature.group Eclipse.org - m2e
    m2e-wtp - Maven Integration for WTP 1.5.2.20220906-1452 org.eclipse.m2e.wtp.feature.feature.group Eclipse.org - m2e-wtp


Plugins, filtered for icu

    Unicode, Inc. ICU4J 67.1  com.ibm.icu
    Eclipse Orbit ICU4J 67.1.0.v20200706-1749 com.ibm.icu

**Comment by johnthad** [comment]
I don't know if this case should be reopened, but I wanted to add that I'm not the only one seeing the `"SSE core task scheduler startup"` error (see https://stackoverflow.com/a/73821375/1316011). My stack trace:

	!ENTRY org.eclipse.core.jobs 4 2 2022-09-23 12:41:24.927
	!MESSAGE An internal error occurred during: "SSE core task scheduler startup".
	!STACK 0
	java.lang.NoClassDefFoundError: com/ibm/icu/util/StringTokenizer
		at org.eclipse.wst.sse.core.utils.StringUtils.unpack(StringUtils.java:777)
		at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.getScannedProjects(TaskScanningJob.java:295)
		at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.projectHasNotBeenFullyScanned(TaskScanningJob.java:152)
		at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.addProject(TaskScanningJob.java:118)
		at org.eclipse.wst.sse.core.internal.tasks.TaskScanningScheduler.enqueue(TaskScanningScheduler.java:137)
		at org.eclipse.wst.sse.core.internal.tasks.TaskScanningScheduler.startup(TaskScanningScheduler.java:117)
		at org.eclipse.wst.sse.core.internal.SSECorePlugin.lambda$0(SSECorePlugin.java:96)
		at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:166)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Caused by: java.lang.ClassNotFoundException: com.ibm.icu.util.StringTokenizer cannot be found by org.eclipse.wst.sse.core_1.2.800.v202207121749
		at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:487)
		at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
		at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
		... 9 more

In my experience, I can say that after a fresh install and configuration of 2022-09, I did not see the `StringTokenizer` error until two items updated:

    Mylyn WikiText  3.0.43.202209151832 org.eclipse.mylyn.wikitext_feature.feature.group    Eclipse Mylyn
    
    M2E - Maven Integration for Eclipse 2.0.5.20220912-1211 org.eclipse.m2e.feature.feature.group   Eclipse.org - m2e

As I [noted in my reply](https://stackoverflow.com/a/73830897/1316011), the StringTokenizer error appeared immediately after Eclipse restarted (when I tried to Update Maven Project).

My solution was to once again delete and reinstall the IDE. I'm dismissing attempts to update Mylyn to 3.0.42 and M2E 2.0.5 has not happened so far. Now I'm facing an error that I've also see on my office machine, and I'm left with [a clumsy workaround](https://stackoverflow.com/questions/73832953).
