### ISSUE TITLE
Dependency is not resolved when in non-public nexus (causing ctrl-hover not working)

### ISSUE THREAD

**Issue by ca-stefan-cordes** [eclipse-m2e/m2e-core#959]
We have some dependencies and parents in our non-public available nexus repository and the m2e plugin does not find the parent even the repository is in my user settings.xml

```
	<profiles>
		<profile>
			<id>default</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<repository>
					<id>nexus-public-proxy-repo</id>
					<name>nexus-public-proxy-repo</name>
					<url>https://nexus.canda.com/repository/public</url>
				</repository>
			</repositories>

```

The com\retail-sc\maven-base\2020.9.1-1 is fine, too  _remote.repositories
```
#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Oct 01 10:53:39 CEST 2022
maven-base-2020.9.1-1.pom>nexus-public-proxy-repo=
```

Failure even after "Force Update Snapshots"

![image](https://user-images.githubusercontent.com/50696194/193401616-6dc320e1-0493-4ff7-80f6-a330a2695b09.png)

mvn compile works fine on console
![image](https://user-images.githubusercontent.com/50696194/193401637-b6053415-fce2-4525-83a6-a7941accfe9b.png)

**Workaround** is to force reading all artifacts with a mirror statement:
```
	<mirrors>
	     <mirror>
			<id>centralMirror</id>
			<mirrorOf>*</mirrorOf>
			<name>Local m2 Mirror</name>
			<url>https://nexus.canda.com/repository/public</url>
		</mirror>
	</mirrors>
```
(Drawback is that our nexus would need to handle all traffic and all artifacts)

With mirror the error is gone and the Ctrl-Hover is working as expected:
![image](https://user-images.githubusercontent.com/50696194/193401931-a71ba56c-a468-4c14-83ac-59e81fd65ed3.png)

Eclipse Version: 2022-06 (4.24.0)
Build id: 20220609-1112

![installed-m2e-versions](https://user-images.githubusercontent.com/50696194/193402568-16963568-118c-4944-8f1c-0f362a76e088.png)

**Comment by mickaelistria** [comment]
Can you please go to the Problems view and show the full line with details for the marker you're seeing? The error may come from m2e, or from the underlying LemMinX langage server used by the editor. The problem details will help to figure that out.

**Comment by ca-stefan-cordes** [comment]
![image](https://user-images.githubusercontent.com/50696194/193409201-5cb7a479-f633-4d6a-8813-ac3455c7ef01.png)

Non-resolvable parent POM for com.retail-sc.commons:rsc-base-types:${revision}: Could not find artifact com.retail-sc:maven-base:pom:2020.9.1-1 in central (https://repo.maven.apache.org/maven2)

Type is "Language Servers"

**Comment by Renan-Di** [comment]
Any updates on the problem? Same situation here, we have an internal repo configured in a profile activated by properties inside our settings.xml.
Eclipse build and artifact resolution is fine, but trying to open pom editor rises the error(Non resolvable pom parent) or using `Maven > Select active profiles`, when closing the editor the error disapears. We are currently in version 2.2, in an older version of m2e plugin(1.6) it works fine, also deleting the file _remote.repositories causes the error to disapear until next time we redownload this artifact.

.log
```
!ENTRY org.eclipse.m2e.profiles.ui 4 0 2023-04-28 10:40:51.254
!MESSAGE Unable to open the Maven Profile selection dialog
!STACK 1
org.eclipse.core.runtime.CoreException: Could not resolve artifact com.example:super_parent_pom:pom:0.22.0
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$6(MavenImpl.java:584)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:553)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:538)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.resolvePomModel(ProfileManager.java:380)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.buildParentModel(ProfileManager.java:255)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getModelHierarchy(ProfileManager.java:235)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getModelHierarchy(ProfileManager.java:237)
	at org.eclipse.m2e.profiles.core.internal.management.ProfileManager.getProfileDatas(ProfileManager.java:147)
	at org.eclipse.m2e.profiles.ui.internal.actions.ProfileSelectionHandler$GetProfilesJob.getAllProfiles(ProfileSelectionHandler.java:283)
	at org.eclipse.m2e.profiles.ui.internal.actions.ProfileSelectionHandler$GetProfilesJob.run(ProfileSelectionHandler.java:199)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: Missing com.example:super_parent_pom:pom:0.22.0
!SUBENTRY 1 org.eclipse.m2e.core 4 -1 2023-04-28 10:40:51.255
!MESSAGE Could not resolve artifact com.example:super_parent_pom:pom:0.22.0
!SUBENTRY 2 org.eclipse.m2e.core 4 0 2023-04-28 10:40:51.255
!MESSAGE Missing com.example:super_parent_pom:pom:0.22.0
```

**Comment by laeubi** [comment]
> Any updates on the problem? Same situation here, we have an internal repo configured in a profile activated by properties inside our settings.xml.

If you want to push this forward, the best would be to provide a test or at least a reproducer project.

**Comment by pbodnar** [comment]
Hi, I don't have an exact reproducer, but if it helps, here are some related problems observed:

If there is an error downloading an artifact from a repository and the artifact is successfully downloaded from another repository thereafter (because of changing available repositories in settings.xml), it looks like the m2e's (or LemMinX's?) language server is not able to cope with this until I _**restart the whole Eclipse**_. I.e. no matter what I do, I keep getting this error:

> Non-resolvable parent POM for org.apache.logging.log4j:log4j:2.20.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.logging:logging-parent:pom:9 (present, but unavailable): org.apache.logging:logging-parent:pom:9 failed to transfer from https://repo.example.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.logging:logging-parent:pom:9 from/to nexus (https://repo.example.com/nexus/content/groups/public): Access denied to https://repo.example.com/nexus/content/groups/public/org/apache/logging/logging-parent/9/logging-parent-9.pom. Error code 403, 

I think this differs from the "good old days" (2020 - 2021?) before the LS got introduced, when it was enough just to remove the infamous `_remote.repositories` file (or maybe another one, not sure now) from the given `.m2` artifact folder and run "Update Maven Project" in Eclipse. Now it looks like Eclipse remembers the download failure "forever" - until it gets stopped.

Also, I'm not sure if this issue cannot be somehow behind the LS slow start: eclipse/lemminx-maven/issues/406. On the project I had the problem described above, it took even about 20 minutes (!) until getting rid of "Could not get hover information due to timeout after 1000 miliseconds" and Eclipse finally started to show hovers in the POM editor. Interestingly enough, the LS Java process used just about 0,5% CPU for all that time - some temporary deadlock, networking issue?
