### ISSUE TITLE
NullPointer in lsp4e causes POM editor to stop functioning after installing specific plugin

### ISSUE THREAD

**Issue by TomBenjamins** [eclipse-m2e/m2e-core#960]
I Have encountered a strange problem with the new M2e Lemminx POM editor in eclipse 2022-09 and I do not know if this is a M2E of a specific qwickie plugin issue.

I have only encountered it yesterday because before updating to 2022-09 I used to use the legacy M2E POM editor, which did not display this behavior.

Here are the reproduction steps:

1. Install a clean Eclipse JEE 2022-09 and import a Maven project with a POM in any workspace.
2. See the the new M2e Lemminx based POM editor is working, code completion works, hover works.
3. install the qwickie plugin from the eclipse marketplace (I use this plugin for legacy wicket development)
![image](https://user-images.githubusercontent.com/3390629/193417381-cf0565ee-5873-4d08-8424-7c1c240dfd48.png)
4. restart eclipse
5. Open the pom editor again and hover and code completion is failing with multiple instances of the following error:

eclipse.buildId=4.25.0.I20220831-1800

java.version=18.0.2.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/D:/eclipse-workspace/ -product org.eclipse.epp.package.jee.product

org.eclipse.lsp4e
Error
Sat Oct 01 17:48:31 CEST 2022
java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "url" is null

java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "url" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.getProtocol()" because "url" is null
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.createURI(XMLCatalogs.java:132)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.lambda$3(XMLCatalogs.java:87)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getWTPExtensionCatalog(XMLCatalogs.java:65)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.getAllCatalogs(XMLCatalogs.java:52)
	at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLPreferenceConstants.storePreferencesToLemminxOptions(XMLPreferenceConstants.java:90)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.mergeCustomInitializationOptions(XMLLanguageServer.java:168)
	at org.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.getInitializationOptions(XMLLanguageServer.java:163)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:241)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

![image](https://user-images.githubusercontent.com/3390629/193417608-f13af1f5-5222-4135-8da4-a1dbe42022b2.png)

6. uninstall qwickie plugin from eclipse marketplace and restart system
7. everything works as expected. 

Hope you can enlighten me what is the problem here,

greetings,
Tom

**Comment by mickaelistria** [comment]
Reading 
Cannot invoke "java.net.URL.getProtocol()" because "url" is null
at org.eclipse.wildwebdeveloper.xml.internal.ui.preferences.XMLCatalogs.createURI(XMLCatalogs.java:132)`,  I think there are 2 problems, and both deserve to be fixed:
1. qwickie seems to contribute a XML catalog URL that is incorrect.
2. Wild Web Developer reads this URL and fails hardly. It should be changed to be logged and not breaking.

Please rerport the issue to each project. Then when one of the fixes is deployed, m2e will automatically be fixed transitively.

**Comment by TomBenjamins** [comment]
@mickaelistria Qwickie on github does not seem to allow me to add an issue, so to be on the safe side I reported an issue to the Wild Web Developer github, hopefully they can fix the overall problem of crashing while trying to parse an incorrect URL.

greetings, 

Tom

**Comment by mickaelistria** [comment]
Let's close it here as m2e can't do anything here. https://github.com/eclipse/wildwebdeveloper/issues/897 is where the fun should happen.

**Comment by TomBenjamins** [comment]
Ok, if you say so..
