### ISSUE TITLE
 Cannot invoke "org.eclipse.m2e.core.embedder.IMaven.lookup(java.lang.Class)" because the return value of "org.eclipse.m2e.core.internal.MavenPluginActivator.getMaven()" is null

### ISSUE THREAD

**Issue by sratz** [eclipse-m2e/m2e-core#966]
Consider the following:

```
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo.bar</groupId>
  <artifactId>baz</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho.extras</groupId>
        <artifactId>tycho-eclipserun-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>run-director</id>
            <goals>
              <goal>eclipse-run</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <applicationsArgs>
                <args>-consoleLog</args>
                <args>-application</args>
                <args>org.eclipse.equinox.p2.artifact.repository.mirrorApplication</args>
                <args>-source</args>
                <args>mvn:org.eclipse.jetty:jetty-p2:11.0.7:zip:p2site</args>
                <args>-destination</args>
                <args>-destination</args>
                <args>dummy</args>
              </applicationsArgs>
              <jvmArgs>
                <jvmArg>-Declipse.p2.mirrors=false</jvmArg>
              </jvmArgs>
              <repositories>
                <repository>
                  <layout>p2</layout>
                  <url>https://download.eclipse.org/releases/2022-06</url>
                </repository>
              </repositories>
              <dependencies>
                <dependency>
                  <artifactId>org.apache.felix.scr</artifactId>
                  <type>p2-installable-unit</type>
                </dependency>
                <dependency>
                  <artifactId>org.eclipse.equinox.p2.repository.tools</artifactId>
                  <type>p2-installable-unit</type>
                </dependency>
                <dependency>
                  <artifactId>org.eclipse.equinox.p2.core.feature.feature.group</artifactId>
                  <type>p2-installable-unit</type>
                </dependency>
                <dependency>
                  <artifactId>org.eclipse.osgi.compatibility.state</artifactId>
                  <type>p2-installable-unit</type>
                </dependency>
                <dependency>
                  <artifactId>org.eclipse.core.net</artifactId>
                  <type>p2-installable-unit</type>
                </dependency>
                <dependency>
                  <artifactId>org.eclipse.m2e.core</artifactId><!-- Support mvn: URLs -->
                  <type>p2-installable-unit</type>
                </dependency>
              </dependencies>
              <bundleStartLevel>
                <!-- Start m2e bundle to register mvn: schema -->
                <bundle>
                  <id>org.eclipse.m2e.core</id>
                  <level>4</level>
                  <autoStart>true</autoStart>
                </bundle>
              </bundleStartLevel>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
```

This uses tycho-eclipserun to bring up a minimal Eclipse runtime and execute the p2 mirroring application.

The source repository is given as `mvn:` syntax, hence the `org.eclipse.m2e.core` bundle is added as a dependency and set to auto-start, so that the URL scheme is registered early-on.

This works perfectly well with the m2e 1.18.4 shipped as part of Eclipse 2022-06.

However, when I change the above from
```
                  <url>https://download.eclipse.org/releases/2022-06</url>
```
to
```
                  <url>https://download.eclipse.org/releases/2022-09</url>
```
which includes m2e-core 2.0.3, things start to break:

```
!ENTRY org.eclipse.osgi 4 0 2022-10-05 19:10:46.832
!MESSAGE Application error
!STACK 1
org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at mvn:org.eclipse.jetty:jetty-p2:11.0.7:zip:p2site/artifacts.xml.
        at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:252)
        at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.getLocalFile(SimpleArtifactRepositoryFactory.java:68)
        at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:92)
        at org.eclipse.equinox.internal.p2.artifact.repository.simple.SimpleArtifactRepositoryFactory.load(SimpleArtifactRepositoryFactory.java:80)
        at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.factoryLoad(ArtifactRepositoryManager.java:92)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:787)
        at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:685)
        at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository(ArtifactRepositoryManager.java:131)
        at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.addRepository(AbstractApplication.java:156)
        at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.initializeRepos(AbstractApplication.java:124)
        at org.eclipse.equinox.p2.internal.repository.tools.MirrorApplication.run(MirrorApplication.java:200)
        at org.eclipse.equinox.p2.internal.repository.tools.MirrorApplication.start(MirrorApplication.java:91)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.embedder.IMaven.lookup(java.lang.Class)" because the return value of "org.eclipse.m2e.core.internal.MavenPluginActivator.getMaven()" is null
        at org.eclipse.m2e.core.internal.MavenPluginActivator.getRepositorySystem(MavenPluginActivator.java:205)
        at org.eclipse.m2e.core.internal.MvnProtocolHandlerService$MavenURLConnection.connect(MvnProtocolHandlerService.java:98)
        at org.eclipse.m2e.core.internal.MvnProtocolHandlerService$MavenURLConnection.getInputStream(MvnProtocolHandlerService.java:123)
        at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:120)
        at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I am not 100% sure, bit this seems like a side-effect of 25d6833f9cf78e0c423155c9d8381f0db8eaa9d0 or 5500f96afb038ac5c05a295fe9f6a7ab334d6d34.

I tried to debug things, and apparently the dependencies of the `IMaven / MavenImpl` service are not satisfied:
It has a reference dependency to
```
<reference name="containerManager" interface="org.eclipse.m2e.core.internal.embedder.PlexusContainerManager" field="containerManager"/>
```
which in turn has a reference dependency to
```
<reference name="workspace" interface="org.eclipse.core.resources.IWorkspace" field="workspace"/>
```
which is not satisfied in the minimal example above, where `org.eclipse.core.resources` is not auto-started.

Interestingly, the original component XML files after 25d6833f9cf78e0c423155c9d8381f0db8eaa9d0 did not contains these dependencies:
https://github.com/eclipse-m2e/m2e-core/blob/25d6833f9cf78e0c423155c9d8381f0db8eaa9d0/org.eclipse.m2e.core/OSGI-INF/org.eclipse.m2e.core.internal.embedder.MavenImpl.xml

What's needed to get the `mvn:` scheme registered as early as possible without the need to have `org.eclipse.core.resources` loaded?

**Comment by laeubi** [comment]
> What's needed to get the mvn: scheme registered as early as possible without the need to have org.eclipse.core.resources loaded?

Obviously you need to start  `org.eclipse.core.resources` :-)

I'm not sure if it is really possible to refactor that code to work without a workspace ... Just for the sake of the function i wonder if you actually need newer eclipse release here if you just want to mirror things? Another option would be to use tycho for mirroring that also supports the mvn protocol directly...

**Comment by sratz** [comment]
> Obviously you need to start `org.eclipse.core.resources` :-)

I tried it and it actually works!

However, these two errors are thrown upfront (after that things work as expected):

```
!ENTRY org.eclipse.m2e.core 4 0 2022-10-05 19:32:48.745
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:228)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:550)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1401)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.prebind(DependencyManager.java:434)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:550)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1401)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.prebind(DependencyManager.java:434)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:671)
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:310)
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:593)
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:74)
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:460)
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:949)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
        at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
        at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
        at org.eclipse.osgi.container.Module.start(Module.java:486)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: org.osgi.framework.ServiceException: Deadlock while trying to acquire use lock <missing argument>.
        at org.eclipse.osgi.internal.serviceregistry.ServiceUse.checkDeadLock(ServiceUse.java:281)
        at org.eclipse.osgi.internal.serviceregistry.ServiceUse.lock(ServiceUse.java:253)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:544)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:550)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1401)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
        ... 93 more

!ENTRY org.eclipse.m2e.core 4 0 2022-10-05 19:32:48.750
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:228)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:550)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1401)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.field.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:550)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager.doInvokeBindMethod(DependencyManager.java:2078)
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethod(DependencyManager.java:2061)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeBindMethod(SingleComponentManager.java:443)
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeBindMethodLate(DependencyManager.java:1998)
        at org.apache.felix.scr.impl.ComponentRegistry$2.run(ComponentRegistry.java:578)
        at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:114)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.osgi.framework.ServiceException: Deadlock while trying to acquire use lock <missing argument>.
        at org.eclipse.osgi.internal.serviceregistry.ServiceUse.checkDeadLock(ServiceUse.java:281)
        at org.eclipse.osgi.internal.serviceregistry.ServiceUse.lock(ServiceUse.java:253)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:544)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
        at org.apache.felix.scr.impl.manager.SingleRefPair.getServiceObject(SingleRefPair.java:88)
        at org.apache.felix.scr.impl.inject.methods.BindMethod.getServiceObject(BindMethod.java:675)
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2612)
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.prebind(DependencyManager.java:434)
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1830)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1060)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:955)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
        ... 31 more

```



> I'm not sure if it is really possible to refactor that code to work without a workspace

It appears to have worked on m2e-core 1.x. I don't see any reference from `IMaven` to anything workspace related, so I wonder why that's needed.



> Just for the sake of the function i wonder if you actually need newer eclipse release here if you just want to mirror things?

This mirroring thing was just to provide a minimal example. What I'm actually doing is calling is more like the following
```
          <plugin>
            <groupId>org.eclipse.tycho.extras</groupId>
            <artifactId>tycho-eclipserun-plugin</artifactId>
            <version>3.0.0</version>
            <executions>
              <execution>
                <id>run-director</id>
                <goals>
                  <goal>eclipse-run</goal>
                </goals>
                <phase>package</phase>
                <configuration>
                  <applicationsArgs>
                    <args>-consoleLog</args>
                    <args>-data</args>
                    <args>${director.data}</args>
                    <args>-application</args>
                    <args>org.eclipse.equinox.p2.director</args>
                    <args>-repository</args>
                    <args>${director.repo}</args>
                    <args>-installIU</args>
                    <args>${director.installIU}</args>
                    <args>-destination</args>
                    <args>${director.destination}</args>
                    <args>-profile</args>
                    <args>${director.profile}</args>
                    <args>-profileProperties</args>
                    <args>org.eclipse.update.install.features=true</args>
                    <args>-roaming</args>
                    <args>-p2.os</args>
                    <args>${director.os}</args>
                    <args>-p2.ws</args>
                    <args>${director.ws}</args>
                    <args>-p2.arch</args>
                    <args>${director.arch}</args>
                  </applicationsArgs>
                  <jvmArgs>
                    <jvmArg>-Declipse.p2.mirrors=false</jvmArg>
                  </jvmArgs>
                  <repositories>
                    <repository>
                      <layout>p2</layout>
                      <url>mvn:org.eclipse.download.releasetrain:2022-09:202209141001:zip</url>
                    </repository>
                  </repositories>
                  ...
```
to call the p2 director and build a package with specific features installed.

I'd like to keep up with the latest Eclipse releases everywhere in our pipeline, so I also try to use the latest and greatest for such utility steps.

But also in this case, maybe defining a product and using tycho's materialize-product could be an alternative that I might look at.

**Comment by laeubi** [comment]
> It appears to have worked on m2e-core 1.x. I don't see any reference from `IMaven` to anything workspace related, so I wonder why that's needed.

Actually before maven indirectly activated the Resource Plugin, this is now changed to we do not activate it to early...

> But also in this case, maybe defining a product and using tycho's materialize-product could be an alternative that I might look at.

There is also https://tycho.eclipseprojects.io/doc/3.0.0/tycho-extras/tycho-p2-extras-plugin/mirror-mojo.html maybe this works for you?

**Comment by laeubi** [comment]
I'll close thos for now as it is not really m2e related and it seems you have a working workaround (starting the resources bundle), please let me know if anything can be improved here.
