### ISSUE TITLE
Adding archetype catalog breaks Maven integration

### ISSUE THREAD

**Issue by ospringauf** [eclipse-m2e/m2e-core#971]
On a fresh installation of Eclipse 2022-09 (JEE):
Add a remote archtetype catalog (https://nexus..../archetype-catalog.xml) via Preferences/Maven/Archetypes. Click on "Verify", everything looks good. 

After next restart of the IDE:
* Preferences/Maven/Archetypes shows error "The currently displayed page contains invalid values"
* **Cannot create a new Maven project** (File / New / Maven Project -> nothing happens)

The error log contains an "Unhandled event loop exception" exception:

```
eclipse.buildId=4.25.0.I20220831-1800
java.version=17.0.4.1
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/C:/campus/starterkit/eclipse-workspace/

org.eclipse.ui
Error
Thu Oct 06 12:47:02 CEST 2022
Unhandled event loop exception

java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.getActiveArchetypeCatalogs()" because "archetypeManager" is null
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizardArchetypePage.createViewer(MavenProjectWizardArchetypePage.java:248)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizardArchetypePage.createControl(MavenProjectWizardArchetypePage.java:174)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.m2e.core.ui.internal.wizards.MavenProjectWizard.createPageControls(MavenProjectWizard.java:147)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:744)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:636)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:119)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

To me, it looks like the file `.metadata\.plugins\org.eclipse.m2e.core\archetypesInfo.xml` contains invalid data. Resetting the file to the initial state removes the error (but also my archetype catalog).

**Comment by ospringauf** [comment]
Same thing happens when opening an existing workspace that contains custom archetype catalog settings --> could be related to #957

**Comment by laeubi** [comment]
> Add a remote archtetype catalog (`https://nexus..../archetype-catalog.xml`) via Preferences/Maven/Archetypes. Click

Any public accessible example one can use to try that out?

**Comment by laeubi** [comment]
> To me, it looks like the file `.metadata\.plugins\org.eclipse.m2e.core\archetypesInfo.xml` contains invalid data. Resetting the file to the initial state removes the error (but also my archetype catalog).

Can you share the file or does it contain sensitive data?

**Comment by ospringauf** [comment]
> > Add a remote archtetype catalog (`https://nexus..../archetype-catalog.xml`) via Preferences/Maven/Archetypes. Click
> 
> Any public accessible example one can use to try that out?

Yes - for instance, adding https://repo1.maven.org/maven2/archetype-catalog.xml causes the same issue. 
Here's the content of `.metadata\.plugins\org.eclipse.m2e.core\archetypesInfo.xml`:

```
<?xml version="1.0" encoding="UTF-8"?><archetypeCatalogs><catalog type="system" id="internal" enabled="true"/><catalog type="system" id="defaultLocal" enabled="true"/><catalog type="remote" location="https://repo1.maven.org/maven2/archetype-catalog.xml" description="repo1" enabled="true"/></archetypeCatalogs>
```

**Comment by benjamin-cartereau** [comment]
Same issue here with our internal catalog...

**Comment by bvfalcon** [comment]
I have the same problem. Some research:
1) `<catalog type="remote" location=`

Parser [waits for](https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/archetype/ExtensionReader.java#L99) `url`, not `location`

2) In Log I have errors
<details><summary>java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.getArchetypeCatalogs()" because "this.archetypeManager" is null</summary>

java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.getArchetypeCatalogs()" because "this.archetypeManager" is null
	at org.eclipse.m2e.core.ui.internal.preferences.MavenArchetypesPreferencePage.createFieldEditors(MavenArchetypesPreferencePage.java:252)
	at org.eclipse.jface.preference.FieldEditorPreferencePage.createContents(FieldEditorPreferencePage.java:227)
	at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:244)
	at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1433)
	at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1196)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1188)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:630)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:660)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:657)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:821)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:818)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1191)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:284)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:438)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
</details>

and before it also error
<details><summary>java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.newRemoteCatalogFactory(String, String, boolean, boolean)" because the return value of "org.eclipse.m2e.core.ui.internal.M2EUIPluginActivator.getArchetypePlugin()" is null</summary>

!MESSAGE bundle org.eclipse.m2e.core.ui:2.0.2.20221113-1617 (1530)[org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin(109)] : The activate method has thrown an exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.newRemoteCatalogFactory(String, String, boolean, boolean)" because the return value of "org.eclipse.m2e.core.ui.internal.M2EUIPluginActivator.getArchetypePlugin()" is null
	at org.eclipse.m2e.core.ui.internal.archetype.ArchetypeCatalogsWriter$ArchetypeCatalogsContentHandler.startElement(ArchetypeCatalogsWriter.java:185)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1387)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at org.eclipse.m2e.core.ui.internal.archetype.ArchetypeCatalogsWriter.readArchetypeCatalogs(ArchetypeCatalogsWriter.java:87)
	at org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.readCatalogs(ArchetypePlugin.java:188)
	at org.eclipse.m2e.core.ui.internal.archetype.ArchetypePlugin.activate(ArchetypePlugin.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:531)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1002)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:975)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:920)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:218)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:215)
	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:114)
	at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:48)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:568)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:542)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:660)
	at org.osgi.util.tracker.ServiceTracker.addingService(ServiceTracker.java:416)
</details>

**Comment by laeubi** [comment]
@bvfalcon do you like to propose a patch/PR?

**Comment by bvfalcon** [comment]
> @bvfalcon do you like to propose a patch/PR?

I hope do that. Now it seems that error in parsing XML. For this next lines in stacktrace speak:
`
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at org.eclipse.m2e.core.ui.internal.archetype.ArchetypeCatalogsWriter.readArchetypeCatalogs(ArchetypeCatalogsWriter.java:87)
`
but for this moment all files that I see have correct XML-syntax.

**Comment by deamn** [comment]
Same error on Eclipse 2022-12 (JEE)

**Comment by ifnoword** [comment]
> To me, it looks like the file .metadata\.plugins\org.eclipse.m2e.core\archetypesInfo.xml contains invalid data. 

Yes. I ran into the same issue and this seems to be the cause. Below is how I am able to get rid of `"archetypeManager" is null` issue.
I didn't start with a fresh installation. I upgraded from a older Eclipse version so the new 2022-12 inherited an `archetypesInfo.xml` from the older version. Below is how it used to look like. Apparently "MyOrg Archetype Catalog" was causing the issue.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<archetypeCatalogs>
    <catalog type="system" id="myOrgRepoIndexer" enabled="true"/>
    <catalog type="system" id="internal" enabled="true"/>
    <catalog type="system" id="defaultLocal" enabled="true"/>
    <catalog type="system" id="https://repo1.maven.org/maven2/archetype-catalog.xml" enabled="true"/>
    <catalog type="remote" location="http://myOrgRepo/archetype-catalog.xml" description="MyOrg Archetype Catalog" enabled="true"/>
</archetypeCatalogs>
```
I removed the "MyOrg Archetype Catalog" entry from the xml file, saved it, and then restarted Eclipse. Now the "New Maven Project" opens successfully.
I check the `archetypesInfo.xml` again and it looks like below. Eclipse seems to remove the "myOrgRepoIndexer" by itself.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<archetypeCatalogs>
    <catalog type="system" id="internal" enabled="true"/>
    <catalog type="system" id="defaultLocal" enabled="true"/>
    <catalog type="system" id="https://repo1.maven.org/maven2/archetype-catalog.xml" enabled="true"/>
</archetypeCatalogs>
```
However, I have to point out, this is not a real turn-around because if I add "MyOrg Archetype Catalog" back using Window -> Preferences -> Maven -> Archetypes -> Add Remote Catalog. The issue will come up again after Eclipse restarts, which means, the support for remote archetype catalog is still broken.

**Comment by laeubi** [comment]
@bvfalcon I'm currently looking into this, so thanks for the analysis

> PS. No, hipotese has not confirmed: parsing XML only discloses the error, but the error itself is [here](https://github.com/eclipse-m2e/m2e-core/blob/2.0.5/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/M2EUIPluginActivator.java#L184). I don't understand, why this call retuns null.

When the component activates it reads the catalogue so if this fails the serve can not be activated and the service will be null in the next calls.

**Comment by laeubi** [comment]
Okay it seems to be a recursive call that causes the NPE, the first call to the catalogue causes the loading of the service which in turn  then again access the static method, as it is currently initializing then no service is returned...
