### ISSUE TITLE
Checkout as maven project gets stuck on Resolving plugin dependencies

### ISSUE THREAD

**Issue by to-fr** [eclipse-m2e/m2e-core#984]
Problem mentioned in #522 still persists.

"Importing Maven projects" gets stuck on 92%.
I have to kill eclipse using the task manager.

```
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2022-09 (4.25.0)
Build id: 20220908-1902
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.4.1+1
Java version: 17.0.4.1
```

This time it comes directly from m2e.core:

```
"Worker-12: Importing Maven projects" #69 prio=5 os_prio=0 cpu=8437.50ms elapsed=1104.31s tid=0x00000158e1f210b0 nid=0x3088 in Object.wait()  [0x00000003c77fd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.4.1/Native Method)
	- waiting on <no object reference available>
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:1042)
	- locked <0x0000000703200000> (a java.util.Collections$SynchronizedSet)
	at org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.removeFolder(GeneratedSourceFolderManager.java:508)
	at org.eclipse.jdt.apt.core.internal.generatedfile.GeneratedSourceFolderManager.folderNamePreferenceChanged(GeneratedSourceFolderManager.java:321)
	at org.eclipse.jdt.apt.core.internal.AptProject.preferenceChanged(AptProject.java:81)
	at org.eclipse.jdt.apt.core.util.AptConfig.setString(AptConfig.java:969)
	at org.eclipse.jdt.apt.core.util.AptConfig.setGenSrcDir(AptConfig.java:917)
	at org.eclipse.m2e.apt.internal.AbstractAptConfiguratorDelegate.configureProject(AbstractAptConfiguratorDelegate.java:165)
	at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.lambda$0(AbstractAptProjectConfigurator.java:92)
	at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator$$Lambda$1585/0x0000000801202ac0.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.apt.internal.AbstractAptProjectConfigurator.configure(AbstractAptProjectConfigurator.java:85)
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:125)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$6(ProjectConfigurationManager.java:475)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1575/0x0000000801176d70.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:469)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:278)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$1(ProjectConfigurationManager.java:165)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$$Lambda$1476/0x000000080104d0f8.call(Unknown Source)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:138)
	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob$1.doCreateMavenProjects(ImportMavenProjectsJob.java:70)
	at org.eclipse.m2e.core.ui.internal.wizards.AbstractCreateMavenProjectsOperation.run(AbstractCreateMavenProjectsOperation.java:57)
	at org.eclipse.m2e.core.ui.internal.wizards.ImportMavenProjectsJob.runInWorkspace(ImportMavenProjectsJob.java:79)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

[threaddump.txt](https://github.com/eclipse-m2e/m2e-core/files/9762862/threaddump.txt)

**Comment by Akkusativobjekt** [comment]
We are facing the same issue with:

Eclipse eclipse-dsl-2022-09-R-win32-x86_64
Version: 2022-09 (4.25.0)
Build id: 4.25.0.I20220831-1800
OS: Windows 10 x86_64
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.4.1+1
Java version: 17.0.4.1
M2E 2.0.0.20220705-1221

**Comment by wlanger** [comment]
We are facing the issue during Maven update of project, with version prior M2E 2.x it is always working, same workspace, same Maven projects...
Quite annoying :-(

**Comment by Akkusativobjekt** [comment]
Are there any plans to address this issue?

**Comment by laeubi** [comment]
At least a standalone project with steps to reproduce the problem would be required, even better a full test-case.

**Comment by laeubi** [comment]
@wlanger @Akkusativobjekt @to-fr  Is there any public reproducer project for this problem?

The Stacktrace seems similar to:
- https://github.com/eclipse-m2e/m2e-core/issues/1226

**Comment by to-fr** [comment]
I am currently trying to narrow it down.

**Comment by laeubi** [comment]
It seems to be related to importing a project from the version control using SCM connectors, can someone approve this? I tried to setup the subversive connector but it seems not be compatible with m2e 2.x ..

**Comment by laeubi** [comment]
I now was able to reproduce this with git-team provider and an example project.

**Comment by laeubi** [comment]
In about half an hour ([when this build has completed](https://ci.eclipse.org/m2e/job/m2e/job/master/527/)) there should be a new snapshot available you can use this p2 repository:

https://download.eclipse.org/technology/m2e/snapshots/latest/

@davidmichaelkarr @wlanger @Akkusativobjekt @to-fr it would be good to check if that really fixes the issues you are seeing.

**Comment by Akkusativobjekt** [comment]
Thank you for the snapshot version. I will test it and then report back

**Comment by laeubi** [comment]
@to-fr thanks for confirmation! I think the missing icon should be unrelated as m2e do not modify the eclipse icon in such a way (or I'm not aware of it).

**Comment by laeubi** [comment]
The fix for this issue was gently sponsored by [ivv GmbH](https://www.ivv.de/).

**Comment by Akkusativobjekt** [comment]
I can also confirm that the issue no longer occurs. Thank you for the fix

**Comment by HannesWell** [comment]
> Is there a release date set for a version with this fix?

Not yet, but we plan to do one soon. Probably within the next one or two weeks.
